<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:ns0="http://sura.com.pa/GestionarActividadDocumento/" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:tns="http://xmlns.sura.com/MensajeIntegracion/DominioProceso/BPMMI/V1" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:dpropro="http://www.sura.com/ObjetoEmpresarial/DominioProceso/Proceso/V1"
                xmlns:dcomcom="http://xmlns.sura.com/ObjetoEmpresarial/DominioComun/Comun/V1">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../wsdl/GestionarActividadDocumento.wsdl"/>
            <oracle-xsl-mapper:rootElement name="GestionarActividadDocumentoReq" namespace="http://sura.com.pa/GestionarActividadDocumento/"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../../../ComponentesComunes/WSDL/xsd/DominioProceso/BPM/V1/ProcesoMIV1.xsd"/>
            <oracle-xsl-mapper:rootElement name="CrearActividadBPMMsjSol" namespace="http://xmlns.sura.com/MensajeIntegracion/DominioProceso/BPMMI/V1"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [THU OCT 21 16:45:12 COT 2021].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:CrearActividadBPMMsjSol>
         <tns:CabeceraSol>
            <xsl:if test="/ns0:GestionarActividadDocumentoReq/ns0:CABECERA/ns0:CODIGO_OPERACION">
               <dcomcom:CodigoOperacion>
                  <xsl:value-of select="/ns0:GestionarActividadDocumentoReq/ns0:CABECERA/ns0:CODIGO_OPERACION"/>
               </dcomcom:CodigoOperacion>
            </xsl:if>
            <xsl:if test="/ns0:GestionarActividadDocumentoReq/ns0:CABECERA/ns0:FECHA_PROCESAMIENTO">
               <dcomcom:FechaProcesamiento>
                  <xsl:value-of select="/ns0:GestionarActividadDocumentoReq/ns0:CABECERA/ns0:FECHA_PROCESAMIENTO"/>
               </dcomcom:FechaProcesamiento>
            </xsl:if>
            <xsl:if test="/ns0:GestionarActividadDocumentoReq/ns0:CABECERA/ns0:FECHA_TRANSACCION">
               <dcomcom:FechaTransaccion>
                  <xsl:value-of select="/ns0:GestionarActividadDocumentoReq/ns0:CABECERA/ns0:FECHA_TRANSACCION"/>
               </dcomcom:FechaTransaccion>
            </xsl:if>
            <xsl:if test="/ns0:GestionarActividadDocumentoReq/ns0:CABECERA/ns0:ID_TRANSACCION_OSB">
               <dcomcom:IdTransaccionOsb>
                  <xsl:value-of select="/ns0:GestionarActividadDocumentoReq/ns0:CABECERA/ns0:ID_TRANSACCION_OSB"/>
               </dcomcom:IdTransaccionOsb>
            </xsl:if>
            <xsl:if test="/ns0:GestionarActividadDocumentoReq/ns0:CABECERA/ns0:SISTEMA_DESTINO">
               <dcomcom:SistemaDestino>
                  <xsl:value-of select="/ns0:GestionarActividadDocumentoReq/ns0:CABECERA/ns0:SISTEMA_DESTINO"/>
               </dcomcom:SistemaDestino>
            </xsl:if>
            <xsl:if test="/ns0:GestionarActividadDocumentoReq/ns0:CABECERA/ns0:SISTEMA_ORIGEN">
               <dcomcom:SistemaOrigen>
                  <xsl:value-of select="/ns0:GestionarActividadDocumentoReq/ns0:CABECERA/ns0:SISTEMA_ORIGEN"/>
               </dcomcom:SistemaOrigen>
            </xsl:if>
         </tns:CabeceraSol>
         <xsl:if test="/ns0:GestionarActividadDocumentoReq/ns0:IdUsuario">
            <tns:IdUsuario>
               <xsl:value-of select="/ns0:GestionarActividadDocumentoReq/ns0:IdUsuario"/>
            </tns:IdUsuario>
         </xsl:if>
         <xsl:if test="/ns0:GestionarActividadDocumentoReq/ns0:IdProceso">
            <tns:IdProceso>
               <xsl:value-of select="/ns0:GestionarActividadDocumentoReq/ns0:IdProceso"/>
            </tns:IdProceso>
         </xsl:if>
         <xsl:if test="/ns0:GestionarActividadDocumentoReq/ns0:TipoReferencia">
            <tns:TipoReferencia>
               <xsl:value-of select="/ns0:GestionarActividadDocumentoReq/ns0:TipoReferencia"/>
            </tns:TipoReferencia>
         </xsl:if>
         <xsl:if test="/ns0:GestionarActividadDocumentoReq/ns0:IdPlantillaActividad">
            <tns:IdPlantillaActividad>
               <xsl:value-of select="/ns0:GestionarActividadDocumentoReq/ns0:IdPlantillaActividad"/>
            </tns:IdPlantillaActividad>
         </xsl:if>
         <tns:ParametrosActividad>
            <xsl:for-each select="/ns0:GestionarActividadDocumentoReq/ns0:ParametrosActividad/ns0:Parametro">
               <dcomcom:ParametroActividad Elemento="{ns0:Nombre}">
                  <dcomcom:Valor>
                     <xsl:value-of select="ns0:Valor"/>
                  </dcomcom:Valor>
               </dcomcom:ParametroActividad>
            </xsl:for-each>
         </tns:ParametrosActividad>
      </tns:CrearActividadBPMMsjSol>
   </xsl:template>
</xsl:stylesheet>
