<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:tns="http://sura.com.pa/GestionarActividadDocumento/" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction"
                xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source/>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../wsdl/GestionarActividadDocumento.wsdl"/>
            <oracle-xsl-mapper:rootElement name="GestionarActividadDocumentoResp" namespace="http://sura.com.pa/GestionarActividadDocumento/"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [TUE OCT 26 21:59:21 COT 2021].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="codigoOperacion"/>
   <xsl:param name="fechaProcesamiento"/>
   <xsl:param name="fechaTransaccion"/>
   <xsl:param name="idTransaccionOsb"/>
   <xsl:param name="sistemaOrigen"/>
   <xsl:param name="sistemaDestino"/>
   <xsl:param name="detalleMensaje"/>
   <xsl:param name="codigoMensaje"/>
   <xsl:param name="idActividad"/>
   <xsl:template match="/">
      <tns:GestionarActividadDocumentoResp>
         <tns:CABECERA>
            <tns:CODIGO_OPERACION>
               <xsl:value-of select="$codigoOperacion"/>
            </tns:CODIGO_OPERACION>
            <tns:FECHA_PROCESAMIENTO>
               <xsl:value-of select="$fechaProcesamiento"/>
            </tns:FECHA_PROCESAMIENTO>
            <tns:FECHA_TRANSACCION>
               <xsl:value-of select="$fechaTransaccion"/>
            </tns:FECHA_TRANSACCION>
            <tns:ID_TRANSACCION_OSB>
               <xsl:value-of select="$idTransaccionOsb"/>
            </tns:ID_TRANSACCION_OSB>
            <tns:SISTEMA_DESTINO>
               <xsl:value-of select="$sistemaDestino"/>
            </tns:SISTEMA_DESTINO>
            <tns:SISTEMA_ORIGEN>
               <xsl:value-of select="$sistemaOrigen"/>
            </tns:SISTEMA_ORIGEN>
         </tns:CABECERA>
         <tns:STATUS>
            <tns:DETALLE>
               <xsl:value-of select="$detalleMensaje"/>
            </tns:DETALLE>
            <tns:CODIGO>
               <xsl:value-of select="$codigoMensaje"/>
            </tns:CODIGO>
         </tns:STATUS>
         <tns:IdActividad>
               <xsl:value-of select="$idActividad"/>
         </tns:IdActividad>
      </tns:GestionarActividadDocumentoResp>
   </xsl:template>
</xsl:stylesheet>
