<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:ns0="http://www.sura.com/GestionarCliente" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/sp/GestionarCliente" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction"
                xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../../../ComponentesComunes/XSD_Externos/GestionarCliente.xsd"/>
            <oracle-xsl-mapper:rootElement name="OBJETO_CLIENTE" namespace="http://www.sura.com/GestionarCliente"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../DBadapter/GestionarCliente_sp.xsd"/>
            <oracle-xsl-mapper:rootElement name="InputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/GestionarCliente"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [TUE JUL 28 11:16:32 COT 2020].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:InputParameters>
         <xsl:if test="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:NUMERO_IDENTIFICACION">
            <tns:P_ASEGURADO>
               <xsl:value-of select="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:NUMERO_IDENTIFICACION"/>
            </tns:P_ASEGURADO>
         </xsl:if>
         <xsl:if test="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:NOMBRE">
            <tns:P_NOMBRE>
               <xsl:value-of select="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:NOMBRE"/>
            </tns:P_NOMBRE>
         </xsl:if>
         <xsl:if test="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:SEGUNDO_NOMBRE">
            <tns:P_SEGUNDO_NOMBRE>
               <xsl:value-of select="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:SEGUNDO_NOMBRE"/>
            </tns:P_SEGUNDO_NOMBRE>
         </xsl:if>
         <xsl:if test="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:APELLIDO">
            <tns:P_APELLIDO>
               <xsl:value-of select="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:APELLIDO"/>
            </tns:P_APELLIDO>
         </xsl:if>
         <xsl:if test="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:SEGUNDO_APELLIDO">
            <tns:P_APELLIDO_MATERNO>
               <xsl:value-of select="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:SEGUNDO_APELLIDO"/>
            </tns:P_APELLIDO_MATERNO>
         </xsl:if>
         <xsl:if test="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:SEXO">
            <tns:P_SEXO>
               <xsl:value-of select="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:SEXO"/>
            </tns:P_SEXO>
         </xsl:if>
         <xsl:if test="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:ESTADO_CIVIL">
            <tns:P_ESTADO_CIVIL>
               <xsl:value-of select="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:ESTADO_CIVIL"/>
            </tns:P_ESTADO_CIVIL>
         </xsl:if>
         <xsl:if test="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:FECHA_NACIMIENTO">
            <tns:P_FECHA_DE_NACIMIENTO>
               <xsl:value-of select="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:FECHA_NACIMIENTO"/>
            </tns:P_FECHA_DE_NACIMIENTO>
         </xsl:if>
         <xsl:choose>
            <xsl:when test="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:DIRECCIONES/ns0:TIPO = &quot;r&quot;">
               <xsl:if test="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:DIRECCIONES/ns0:COD_PAIS">
                  <tns:P_COD_PAIS_RESIDENCIA>
                     <xsl:value-of select="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:DIRECCIONES/ns0:COD_PAIS"/>
                  </tns:P_COD_PAIS_RESIDENCIA>
               </xsl:if>
                <xsl:if test="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:DIRECCIONES/ns0:EMAIL">
                  <tns:P_EMAIL>
                     <xsl:value-of select="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:DIRECCIONES/ns0:EMAIL"/>
                  </tns:P_EMAIL>
               </xsl:if>
                <xsl:if test="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:DIRECCIONES/ns0:TELEFONO">
                  <tns:P_TELEFONO>
                     <xsl:value-of select="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:DIRECCIONES/ns0:TELEFONO"/>
                  </tns:P_TELEFONO>
               </xsl:if>
                <xsl:if test="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:CELULAR">
            <tns:P_CELULAR>
               <xsl:value-of select="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:CELULAR"/>
            </tns:P_CELULAR>
         </xsl:if>
               <xsl:if test="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:DIRECCIONES/ns0:COD_PROVINCIA">
                  <tns:P_COD_PROV_RESIDENCIA>
                     <xsl:value-of select="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:DIRECCIONES/ns0:COD_PROVINCIA"/>
                  </tns:P_COD_PROV_RESIDENCIA>
               </xsl:if>
               <xsl:if test="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:DIRECCIONES/ns0:COD_DISTRITO">
                  <tns:P_COD_DIST_RESIDENCIA>
                     <xsl:value-of select="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:DIRECCIONES/ns0:COD_DISTRITO"/>
                  </tns:P_COD_DIST_RESIDENCIA>
               </xsl:if>
               <xsl:if test="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:DIRECCIONES/ns0:COD_CORREGIMIENTO">
                  <tns:P_COD_CORR_RESIDENCIA>
                     <xsl:value-of select="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:DIRECCIONES/ns0:COD_CORREGIMIENTO"/>
                  </tns:P_COD_CORR_RESIDENCIA>
               </xsl:if>
               <xsl:if test="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:DIRECCIONES/ns0:COD_BARRIO">
                  <tns:P_BARRIO_RESIDENCIA>
                     <xsl:value-of select="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:DIRECCIONES/ns0:COD_BARRIO"/>
                  </tns:P_BARRIO_RESIDENCIA>
               </xsl:if>
               <xsl:if test="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:DIRECCIONES/ns0:CALLE">
                  <tns:P_CALLE>
                     <xsl:value-of select="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:DIRECCIONES/ns0:CALLE"/>
                  </tns:P_CALLE>
               </xsl:if>
               <xsl:if test="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:DIRECCIONES/ns0:URBANIZACION">
                  <tns:P_URBANIZACION>
                     <xsl:value-of select="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:DIRECCIONES/ns0:URBANIZACION"/>
                  </tns:P_URBANIZACION>
               </xsl:if>
               <xsl:if test="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:DIRECCIONES/ns0:CASA">
                  <tns:P_CASA>
                     <xsl:value-of select="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:DIRECCIONES/ns0:CASA"/>
                  </tns:P_CASA>
               </xsl:if>
               <xsl:if test="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:DIRECCIONES/ns0:DIRECCION">
                  <tns:P_DIRECCION>
                     <xsl:value-of select="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:DIRECCIONES/ns0:DIRECCION"/>
                  </tns:P_DIRECCION>
               </xsl:if>
            </xsl:when>
         </xsl:choose>
         <xsl:choose>
            <xsl:when test="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:DIRECCIONES/ns0:TIPO = &quot;t&quot;">
               <xsl:if test="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:DIRECCIONES/ns0:COD_PAIS">
                  <tns:P_COD_PAIS_TRABAJO>
                     <xsl:value-of select="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:DIRECCIONES/ns0:COD_PAIS"/>
                  </tns:P_COD_PAIS_TRABAJO>
               </xsl:if>
               <xsl:if test="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:DIRECCIONES/ns0:COD_PROVINCIA">
                  <tns:P_COD_PROV_TRABAJO>
                     <xsl:value-of select="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:DIRECCIONES/ns0:COD_PROVINCIA"/>
                  </tns:P_COD_PROV_TRABAJO>
               </xsl:if>
               <xsl:if test="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:DIRECCIONES/ns0:COD_DISTRITO">
                  <tns:P_COD_DIST_TRABAJO>
                     <xsl:value-of select="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:DIRECCIONES/ns0:COD_DISTRITO"/>
                  </tns:P_COD_DIST_TRABAJO>
               </xsl:if>
               <xsl:if test="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:DIRECCIONES/ns0:COD_CORREGIMIENTO">
                  <tns:P_COD_CORR_TRABAJO>
                     <xsl:value-of select="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:DIRECCIONES/ns0:COD_CORREGIMIENTO"/>
                  </tns:P_COD_CORR_TRABAJO>
               </xsl:if>
               <xsl:if test="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:DIRECCIONES/ns0:COD_BARRIO">
                  <tns:P_BARRIO_TRABAJO>
                     <xsl:value-of select="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:DIRECCIONES/ns0:COD_BARRIO"/>
                  </tns:P_BARRIO_TRABAJO>
               </xsl:if>
               <xsl:if test="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:DIRECCIONES/ns0:CALLE">
                  <tns:P_CALLE_TRABAJO>
                     <xsl:value-of select="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:DIRECCIONES/ns0:CALLE"/>
                  </tns:P_CALLE_TRABAJO>
               </xsl:if>
               <xsl:if test="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:DIRECCIONES/ns0:URBANIZACION">
                  <tns:P_URBANIZACION_TRABAJO>
                     <xsl:value-of select="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:DIRECCIONES/ns0:URBANIZACION"/>
                  </tns:P_URBANIZACION_TRABAJO>
               </xsl:if>
               <xsl:if test="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:DIRECCIONES/ns0:CASA">
                  <tns:P_CASA_TRABAJO>
                     <xsl:value-of select="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:DIRECCIONES/ns0:CASA"/>
                  </tns:P_CASA_TRABAJO>
               </xsl:if>
               <xsl:if test="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:DIRECCIONES/ns0:DIRECCION">
                  <tns:P_DIRECCION_TRABAJO>
                     <xsl:value-of select="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:DIRECCIONES/ns0:DIRECCION"/>
                  </tns:P_DIRECCION_TRABAJO>
               </xsl:if>
               <xsl:if test="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:DIRECCIONES/ns0:TELEFONO">
                  <tns:P_TELEFONO_TRABAJO>
                     <xsl:value-of select="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:DIRECCIONES/ns0:TELEFONO"/>
                  </tns:P_TELEFONO_TRABAJO>
               </xsl:if>
               <xsl:if test="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:DIRECCIONES/ns0:EXTENSION">
                  <tns:P_EXTENSION_2>
                     <xsl:value-of select="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:DIRECCIONES/ns0:EXTENSION"/>
                  </tns:P_EXTENSION_2>
               </xsl:if>
            </xsl:when>
         </xsl:choose>
        
         <xsl:if test="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:INFO_ACTIVIDAD_ECONOMICA/ns0:ACTIVIDAD_ECONOMICA">
            <tns:P_ACTIVIDAD_ECONOMICA>
               <xsl:value-of select="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:INFO_ACTIVIDAD_ECONOMICA/ns0:ACTIVIDAD_ECONOMICA"/>
            </tns:P_ACTIVIDAD_ECONOMICA>
         </xsl:if>
         <xsl:if test="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:INFO_ACTIVIDAD_ECONOMICA/ns0:ACTIVIDAD">
            <tns:P_ACTIVIDAD>
               <xsl:value-of select="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:INFO_ACTIVIDAD_ECONOMICA/ns0:ACTIVIDAD"/>
            </tns:P_ACTIVIDAD>
         </xsl:if>
         <xsl:if test="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:INFO_ACTIVIDAD_ECONOMICA/ns0:CARGO_PUBLICO">
            <tns:P_CARGO_PUBLICO>
               <xsl:value-of select="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:INFO_ACTIVIDAD_ECONOMICA/ns0:CARGO_PUBLICO"/>
            </tns:P_CARGO_PUBLICO>
         </xsl:if>
         <xsl:if test="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:INFO_ACTIVIDAD_ECONOMICA/ns0:CARGO_OCUPADO">
            <tns:P_CARGO_OCUPADO>
               <xsl:value-of select="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:INFO_ACTIVIDAD_ECONOMICA/ns0:CARGO_OCUPADO"/>
            </tns:P_CARGO_OCUPADO>
         </xsl:if>
         <xsl:if test="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:INFO_ACTIVIDAD_ECONOMICA/ns0:FECHA_INICIO_PEP">
            <tns:P_FECHA_INICIO_PEP>
               <xsl:value-of select="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:INFO_ACTIVIDAD_ECONOMICA/ns0:FECHA_INICIO_PEP"/>
            </tns:P_FECHA_INICIO_PEP>
         </xsl:if>
         <xsl:if test="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:INFO_ACTIVIDAD_ECONOMICA/ns0:PEP_ACTUAL">
            <tns:P_PEP_ACTUAL>
               <xsl:value-of select="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:INFO_ACTIVIDAD_ECONOMICA/ns0:PEP_ACTUAL"/>
            </tns:P_PEP_ACTUAL>
         </xsl:if>
         <xsl:if test="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:INFO_ACTIVIDAD_ECONOMICA/ns0:FECHA_FIN_PEP">
            <tns:P_FECHA_FINAL_PEP>
               <xsl:value-of select="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:INFO_ACTIVIDAD_ECONOMICA/ns0:FECHA_FIN_PEP"/>
            </tns:P_FECHA_FINAL_PEP>
         </xsl:if>
         <xsl:if test="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:INFO_ACTIVIDAD_ECONOMICA/ns0:CODIGO_INGRESO_ANUAL">
            <tns:P_COD_INGRESO_ANUAL>
               <xsl:value-of select="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:INFO_ACTIVIDAD_ECONOMICA/ns0:CODIGO_INGRESO_ANUAL"/>
            </tns:P_COD_INGRESO_ANUAL>
         </xsl:if>
         <xsl:if test="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:INFO_ACTIVIDAD_ECONOMICA/ns0:COD_OTRO_INGRESO">
            <tns:P_COD_INGRESO_OTRO>
               <xsl:value-of select="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:INFO_ACTIVIDAD_ECONOMICA/ns0:COD_OTRO_INGRESO"/>
            </tns:P_COD_INGRESO_OTRO>
         </xsl:if>
         <xsl:if test="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:INFO_ACTIVIDAD_ECONOMICA/ns0:COD_PAIS_RESIDENCIA_FISCAL">
            <tns:P_COD_PAIS_RESIDENCIA_FISCAL>
               <xsl:value-of select="/ns0:OBJETO_CLIENTE/ns0:PERSONA_ASEGURADA/ns0:INFO_ACTIVIDAD_ECONOMICA/ns0:COD_PAIS_RESIDENCIA_FISCAL"/>
            </tns:P_COD_PAIS_RESIDENCIA_FISCAL>
         </xsl:if>
         <xsl:if test="/ns0:OBJETO_CLIENTE/ns0:ACCION">
            <tns:P_ACCION>
               <xsl:value-of select="/ns0:OBJETO_CLIENTE/ns0:ACCION"/>
            </tns:P_ACCION>
         </xsl:if>
      </tns:InputParameters>
   </xsl:template>
</xsl:stylesheet>
