<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:tns="http://tempuri.org/" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:ns0="http://xmlns.sura.com/MensajeIntegracion/DominioProceso/BPMMI/V1" xmlns:dpropro="http://xmlns.sura.com/ObjetoIntegracion/DominioProceso/Proceso/V1" xmlns:dcomcom="http://xmlns.sura.com/ObjetoEmpresarial/DominioComun/Comun/V1" xmlns:ns1="http://schemas.datacontract.org/2004/07/OBService">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../../../ComponentesComunes/WSDL/xsd/DominioProceso/BPM/V1/ProcesoMIV1.xsd"/>
            <oracle-xsl-mapper:rootElement name="ActualizarActividadBPMMsjSol" namespace="http://xmlns.sura.com/MensajeIntegracion/DominioProceso/BPMMI/V1"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../wsdl/OBService.xsd"/>
            <oracle-xsl-mapper:rootElement name="OBDocEdit" namespace="http://tempuri.org/"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [TUE MAR 31 01:25:46 COT 2020].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:OBDocEdit>
         <tns:sOBDocHandle>
            <xsl:value-of select="/ns0:ActualizarActividadBPMMsjSol/ns0:IdActividad"/>
         </tns:sOBDocHandle>
         <tns:oKWord>
            <xsl:if test="/ns0:ActualizarActividadBPMMsjSol/ns0:IdUsuario">
               <ns1:OBKeyword>
                  <ns1:kwID>
                     <xsl:value-of select="&quot;121&quot;"/>
                  </ns1:kwID>
                  <ns1:kwName>
                     <xsl:value-of select="local-name(/ns0:ActualizarActividadBPMMsjSol/ns0:IdUsuario)"/>
                  </ns1:kwName>
                  <ns1:kwValue>
                     <xsl:value-of select="/ns0:ActualizarActividadBPMMsjSol/ns0:IdUsuario"/>
                  </ns1:kwValue>
               </ns1:OBKeyword>
            </xsl:if>
            <xsl:if test="/ns0:ActualizarActividadBPMMsjSol/ns0:CodigoEstado">
               <ns1:OBKeyword>
                  <ns1:kwID>
                     <xsl:value-of select="&quot;122&quot;"/>
                  </ns1:kwID>
                  <ns1:kwName>
                     <xsl:value-of select="local-name(/ns0:ActualizarActividadBPMMsjSol/ns0:CodigoEstado)"/>
                     </ns1:kwName>
                     <xsl:choose>
                     <xsl:when test="/ns0:ActualizarActividadBPMMsjSol/ns0:CodigoEstado = &quot;01&quot;">
                        <ns1:kwValue>Abierto</ns1:kwValue>
                     </xsl:when>
                     <xsl:when test="/ns0:ActualizarActividadBPMMsjSol/ns0:CodigoEstado = &quot;02&quot;">
                        <ns1:kwValue>Pendiente</ns1:kwValue>
                     </xsl:when>
                     <xsl:when test="/ns0:ActualizarActividadBPMMsjSol/ns0:CodigoEstado = &quot;03&quot;">
                        <ns1:kwValue>En Ejecucion</ns1:kwValue>
                     </xsl:when>
                     <xsl:when test="/ns0:ActualizarActividadBPMMsjSol/ns0:CodigoEstado = &quot;04&quot;">
                        <ns1:kwValue>En Aprobacion</ns1:kwValue>
                     </xsl:when>
                     <xsl:when test="/ns0:ActualizarActividadBPMMsjSol/ns0:CodigoEstado = &quot;05&quot;">
                        <ns1:kwValue>Cerrado</ns1:kwValue>
                     </xsl:when>
                     <xsl:when test="/ns0:ActualizarActividadBPMMsjSol/ns0:CodigoEstado = &quot;06&quot;">
                        <ns1:kwValue>Cancelado</ns1:kwValue>
                     </xsl:when>
                  </xsl:choose>
                  
               </ns1:OBKeyword>
            </xsl:if>
            <xsl:if test="/ns0:ActualizarActividadBPMMsjSol/ns0:CodigoSubEstado">
               <ns1:OBKeyword>
                  <ns1:kwID>
                     <xsl:value-of select="&quot;123&quot;"/>
                  </ns1:kwID>
                  <ns1:kwName>
                     <xsl:value-of select="local-name(/ns0:ActualizarActividadBPMMsjSol/ns0:CodigoSubEstado)"/>
                   </ns1:kwName>  
                      <xsl:choose>
                     <xsl:when test="/ns0:ActualizarActividadBPMMsjSol/ns0:CodigoSubEstado = &quot;01&quot;">
                        <ns1:kwValue>En Cumplimiento</ns1:kwValue>
                     </xsl:when>
                      <xsl:when test="/ns0:ActualizarActividadBPMMsjSol/ns0:CodigoSubEstado = &quot;02&quot;">
                        <ns1:kwValue>En Evaluacion Tecnica</ns1:kwValue>
                     </xsl:when>
                      <xsl:when test="/ns0:ActualizarActividadBPMMsjSol/ns0:CodigoSubEstado = &quot;03&quot;">
                        <ns1:kwValue>En Gestion</ns1:kwValue>
                     </xsl:when>
                      <xsl:when test="/ns0:ActualizarActividadBPMMsjSol/ns0:CodigoSubEstado = &quot;04&quot;">
                        <ns1:kwValue>En Tesoreria/ Finanazas</ns1:kwValue>
                     </xsl:when>
                      <xsl:when test="/ns0:ActualizarActividadBPMMsjSol/ns0:CodigoSubEstado = &quot;05&quot;">
                        <ns1:kwValue>En Devolucion</ns1:kwValue>
                     </xsl:when>
                  </xsl:choose>
               </ns1:OBKeyword>
            </xsl:if>
         </tns:oKWord>
      </tns:OBDocEdit>
   </xsl:template>
</xsl:stylesheet>