<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="expoConsultarPolizaSOAP"
     targetNamespace="http://sura.com.pa/expoConsultarPolizaSOAP/"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:ccm="http://sura.com.pa/expoConsultarPolizaSOAP/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="Exp_ConsultarPolizaV2">
        <plnk:role name="expoConsultarPolizaSOAP" portType="ccm:expoConsultarPolizaSOAP"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://sura.com.pa/expoConsultarPolizaSOAP/" location="consultarPoliza.wsdl"/>
</wsdl:definitions>
