-- Declare package containing conversion functions between SQL and PL/SQL types
CREATE OR REPLACE PACKAGE BPEL_CREARPROVEEDORINSIS AS
   FUNCTION prov_dm$insert_provider (PI_MAN_ID NUMBER,
	PO_PROVIDER_ID OUT NUMBER,
	PIO_ERR IN OUT SRVERR
	) RETURN INTEGER;
END BPEL_CREARPROVEEDORINSIS;
/
show errors
CREATE OR REPLACE PACKAGE BODY BPEL_CREARPROVEEDORINSIS IS

   FUNCTION prov_dm$insert_provider (PI_MAN_ID NUMBER,
	PO_PROVIDER_ID OUT NUMBER,
	PIO_ERR IN OUT SRVERR
	) RETURN INTEGER IS
 RETURN_ INTEGER;
   BEGIN
      RETURN_ := SYS.SQLJUTL.BOOL2INT(INSIS_NTW_V10.PROV_DM.INSERT_PROVIDER(PI_MAN_ID,
	PO_PROVIDER_ID,
	PIO_ERR
	));
      return RETURN_;
   END prov_dm$insert_provider;

END BPEL_CREARPROVEEDORINSIS;
/
show errors
exit
