<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/sp/dbInsis" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:ns0="http://xmlns.sura.com/MensajeIntegracion/DominioProceso/BPMMI/V1" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction"
                xmlns:dpropro="http://xmlns.sura.com/ObjetoIntegracion/DominioProceso/Proceso/V1"
                xmlns:dcomcom="http://xmlns.sura.com/ObjetoEmpresarial/DominioComun/Comun/V1"
                xmlns:ns1="http://www.sura.com/ObjetoEmpresarial/DominioProceso/Proceso/V1">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../../../ComponentesComunes/WSDL/xsd/DominioProceso/BPM/V1/ProcesoMIV1.xsd"/>
            <oracle-xsl-mapper:rootElement name="ObtenerReferenciaBPMMsjSol" namespace="http://xmlns.sura.com/MensajeIntegracion/DominioProceso/BPMMI/V1"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../database/dbInsis_sp.xsd"/>
            <oracle-xsl-mapper:rootElement name="InputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/dbInsis"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [WED APR 01 14:15:26 COT 2020].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:InputParameters>
         <tns:PI_POLICYID>
            <xsl:value-of select="/ns0:ObtenerReferenciaBPMMsjSol/ns0:NumeroPoliza"/>
         </tns:PI_POLICYID>
         <tns:PI_EGN>
            <xsl:value-of select="/ns0:ObtenerReferenciaBPMMsjSol/ns0:IdentificacionCliente"/>
         </tns:PI_EGN>
         <tns:PI_TYPEREF>
            <xsl:value-of select="/ns0:ObtenerReferenciaBPMMsjSol/ns0:TipoReferencia"/>
         </tns:PI_TYPEREF>
         <xsl:if test="/ns0:ObtenerReferenciaBPMMsjSol/ns0:IdProceso">
            <tns:PI_IDPROCESS>
               <xsl:value-of select="/ns0:ObtenerReferenciaBPMMsjSol/ns0:IdProceso"/>
            </tns:PI_IDPROCESS>
         </xsl:if>
         <tns:PI_USERID>
            <xsl:value-of select="/ns0:ObtenerReferenciaBPMMsjSol/ns0:IdUsuario"/>
         </tns:PI_USERID>
         <xsl:if test="/ns0:ObtenerReferenciaBPMMsjSol/ns0:IdPlantillaActividad">
            <tns:PI_NUMREFER>
               <xsl:value-of select="/ns0:ObtenerReferenciaBPMMsjSol/ns0:IdPlantillaActividad"/>
            </tns:PI_NUMREFER>
         </xsl:if>
      </tns:InputParameters>
   </xsl:template>
</xsl:stylesheet>
