<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:ns0="http://www.sura.com.pa/GestionarTransaccionBD" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/sp/sp_busdata_polkm0" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction"
                xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../nxsd/RqGestionarTransaccionBD.xsd"/>
            <oracle-xsl-mapper:rootElement name="OBJETO_TRANSACCION_BD" namespace="http://www.sura.com.pa/GestionarTransaccionBD"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../Database/sp_busdata_polkm0_sp.xsd"/>
            <oracle-xsl-mapper:rootElement name="InputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/sp_busdata_polkm0"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [WED DEC 23 10:49:45 COT 2020].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="id_km"/>
   <xsl:param name="id_pro"/>
   <xsl:param name="opcion"/>
   <xsl:template match="/">
      <tns:InputParameters>
         <xsl:if test="/ns0:OBJETO_TRANSACCION_BD/ns0:NUMERO_DE_POLIZA != &quot;null&quot;">
            <tns:i_Pk_poliza>
               <xsl:value-of select="/ns0:OBJETO_TRANSACCION_BD/ns0:NUMERO_DE_POLIZA"/>
            </tns:i_Pk_poliza>
         </xsl:if>
         <xsl:if test="/ns0:OBJETO_TRANSACCION_BD/ns0:CHASIS != &quot;null&quot;">
            <tns:i_pk_Vin>
               <xsl:value-of select="/ns0:OBJETO_TRANSACCION_BD/ns0:CHASIS"/>
            </tns:i_pk_Vin>
         </xsl:if>
         <xsl:if test="/ns0:OBJETO_TRANSACCION_BD/ns0:ID != &quot;null&quot;">
            <tns:i_pk_ID_Voucher>
               <xsl:value-of select="/ns0:OBJETO_TRANSACCION_BD/ns0:ID"/>
            </tns:i_pk_ID_Voucher>
         </xsl:if>
         <xsl:if test="/ns0:OBJETO_TRANSACCION_BD/ns0:TIPO_DE_COBERTURA != &quot;null&quot;">
            <xsl:choose>
               <xsl:when test="/ns0:OBJETO_TRANSACCION_BD/ns0:TIPO_DE_COBERTURA = &quot;KM&quot;">
                  <tns:i_pk_ContractType>
                     <xsl:value-of select="$id_km"/>
                  </tns:i_pk_ContractType>
               </xsl:when>
               <xsl:when test="/ns0:OBJETO_TRANSACCION_BD/ns0:TIPO_DE_COBERTURA != &quot;KM&quot;">
                  <tns:i_pk_ContractType>
                     <xsl:value-of select="$id_pro"/>
                  </tns:i_pk_ContractType>
               </xsl:when>
            </xsl:choose>
         </xsl:if>
         <xsl:if test="/ns0:OBJETO_TRANSACCION_BD/ns0:STATE != &quot;null&quot;">
            <tns:i_pk_Status>
               <xsl:value-of select="number(/ns0:OBJETO_TRANSACCION_BD/ns0:STATE)"/>
            </tns:i_pk_Status>
         </xsl:if>
         <xsl:if test="/ns0:OBJETO_TRANSACCION_BD/ns0:OPEN_DATE != &quot;null&quot;">
            <tns:i_pk_FechaRegistro>
               <xsl:value-of select="/ns0:OBJETO_TRANSACCION_BD/ns0:OPEN_DATE"/>
            </tns:i_pk_FechaRegistro>
         </xsl:if>
         <xsl:if test="/ns0:OBJETO_TRANSACCION_BD/ns0:VIGENCIA_INICIAL != &quot;null&quot;">
            <tns:i_pk_VigenciaInicial>
               <xsl:value-of select="substring-before (/ns0:OBJETO_TRANSACCION_BD/ns0:VIGENCIA_INICIAL, &quot;T&quot; )"/>
            </tns:i_pk_VigenciaInicial>
         </xsl:if>
         <xsl:if test="/ns0:OBJETO_TRANSACCION_BD/ns0:VIGENCIA_FINAL != &quot;null&quot;">
            <tns:i_pk_VigenciaFinal>
               <xsl:value-of select="substring-before (/ns0:OBJETO_TRANSACCION_BD/ns0:VIGENCIA_FINAL, &quot;T&quot; )"/>
            </tns:i_pk_VigenciaFinal>
         </xsl:if>
         <xsl:if test="/ns0:OBJETO_TRANSACCION_BD/ns0:IDENTIFICACION != &quot;null&quot;">
            <tns:i_pk_Cedula>
               <xsl:value-of select="/ns0:OBJETO_TRANSACCION_BD/ns0:IDENTIFICACION"/>
            </tns:i_pk_Cedula>
         </xsl:if>
         <xsl:if test="/ns0:OBJETO_TRANSACCION_BD/ns0:TIPO_PROCESO != &quot;null&quot;">
            <tns:i_opcion>
               <xsl:value-of select="$opcion"/>
            </tns:i_opcion>
         </xsl:if>
      </tns:InputParameters>
   </xsl:template>
</xsl:stylesheet>
