apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: UsersCrudReactJs
  annotations:
    github.com/project-slug: octaviobarre92/UsersCrudReactJs
spec:
  type: other
  lifecycle: unknown
  owner: guests
