<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CajaUnica/Dat_ConsultarReclamoPremium/Consultar_Reclamo" name="Consultar_Reclamo-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="Consultar_Reclamo.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/CajaUnica/Dat_ConsultarReclamoPremium/Consultar_Reclamo"/>
    <wsdl:binding name="Consultar_Reclamo_ptt-binding" type="con:Consultar_Reclamo_ptt" xmlns:con="http://xmlns.oracle.com/pcbpel/adapter/db/CajaUnica/Dat_ConsultarReclamoPremium/Consultar_Reclamo">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="Consultar_Reclamo">
            <soap:operation soapAction="Consultar_Reclamo"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>