<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/sp/sp_get_polizas_corredores" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:tns="http://www.sura.com.pa/RsObtenerPolizasCorredores" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction"
                xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../Database/sp_get_polizas_corredores_sp.xsd"/>
            <oracle-xsl-mapper:rootElement name="OutputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/sp_get_polizas_corredores"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../nxsd/RsObtenerPolizasCorredores.xsd"/>
            <oracle-xsl-mapper:rootElement name="INFO_POLIZAS" namespace="http://www.sura.com.pa/RsObtenerPolizasCorredores"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [MON DEC 28 16:43:37 COT 2020].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="codigoOperacion"/>
   <xsl:param name="fechaProcesamiento"/>
   <xsl:param name="fechaTransaccion"/>
   <xsl:param name="idTransaccion"/>
   <xsl:param name="sistemaDestino"/>
   <xsl:param name="sistemaOrigen"/>
   <xsl:param name="componente"/>
   <xsl:param name="origen"/>
   <xsl:template match="/">
     <tns:INFO_POLIZAS>
         <tns:STATUS>
            <xsl:if test="/ns0:OutputParameters/ns0:descMSG">
               <tns:DETALLE>
                  <xsl:value-of select="/ns0:OutputParameters/ns0:descMSG"/>
               </tns:DETALLE>
            </xsl:if>
            <xsl:if test="/ns0:OutputParameters/ns0:statusMSG">
               <tns:CODIGO>200</tns:CODIGO>
            </xsl:if>
            <xsl:if test="$origen">
               <tns:ORIGEN>
                  <xsl:value-of select="$origen"/>
               </tns:ORIGEN>
            </xsl:if>
            <xsl:if test="$componente">
               <tns:COMPONENTE>
                  <xsl:value-of select="$componente"/>
               </tns:COMPONENTE>
            </xsl:if>
         </tns:STATUS>
         <tns:CABECERA>
            <xsl:if test="$fechaTransaccion">
               <tns:FECHA_TRANSACCION>
                  <xsl:value-of select="$fechaTransaccion"/>
               </tns:FECHA_TRANSACCION>
            </xsl:if>
            <xsl:if test="$idTransaccion">
               <tns:ID_TRANSACCION_OSB>
                  <xsl:value-of select="$idTransaccion"/>
               </tns:ID_TRANSACCION_OSB>
            </xsl:if>
            <xsl:if test="$fechaProcesamiento">
               <tns:FECHA_PROCESAMIENTO>
                  <xsl:value-of select="$fechaProcesamiento"/>
               </tns:FECHA_PROCESAMIENTO>
            </xsl:if>
            <xsl:if test="$sistemaDestino">
               <tns:SISTEMA_DESTINO>
                  <xsl:value-of select="$sistemaDestino"/>
               </tns:SISTEMA_DESTINO>
            </xsl:if>
            <xsl:if test="$sistemaOrigen">
               <tns:SISTEMA_ORIGEN>
                  <xsl:value-of select="$sistemaOrigen"/>
               </tns:SISTEMA_ORIGEN>
            </xsl:if>
            <xsl:if test="$codigoOperacion">
               <tns:CODIGO_OPERACION>
                  <xsl:value-of select="$codigoOperacion"/>
               </tns:CODIGO_OPERACION>
            </xsl:if>
            <tns:PAGINACION>
               <xsl:if test="/ns0:OutputParameters/ns0:totalPages">
                  <tns:CANTIDAD_DE_PAGINAS>
                     <xsl:value-of select="/ns0:OutputParameters/ns0:totalPages"/>
                  </tns:CANTIDAD_DE_PAGINAS>
               </xsl:if>
            </tns:PAGINACION>
         </tns:CABECERA>
         <xsl:for-each select="/ns0:OutputParameters/ns0:RowSet/ns0:Row">
            <tns:INFO_POLIZAS>
               <xsl:if test="ns0:Column[@name='Cod_corredor']">
                  <tns:COD_CORREDOR>
                     <xsl:value-of select="ns0:Column[@name='Cod_corredor']"/>
                  </tns:COD_CORREDOR>
               </xsl:if>
               <xsl:if test="ns0:Column[@name='Nombre_corredor']">
                  <tns:NOMBRE_CORREDOR>
                     <xsl:value-of select="ns0:Column[@name='Nombre_corredor']"/>
                  </tns:NOMBRE_CORREDOR>
               </xsl:if>
               <tns:CONTRATANTE>
                  <xsl:if test="ns0:Column[@name='Apellido_cont']">
                     <tns:APELLIDO>
                        <xsl:value-of select="ns0:Column[@name='Apellido_cont']"/>
                     </tns:APELLIDO>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Id_cont']">
                     <tns:ID_CONTRATANTE>
                        <xsl:value-of select="ns0:Column[@name='Id_cont']"/>
                     </tns:ID_CONTRATANTE>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Nombre_cont']">
                     <tns:NOMBRE>
                        <xsl:value-of select="ns0:Column[@name='Nombre_cont']"/>
                     </tns:NOMBRE>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Identificacion_cont']">
                     <tns:NUMERO_IDENTIFICACION>
                        <xsl:value-of select="ns0:Column[@name='Identificacion_cont']"/>
                     </tns:NUMERO_IDENTIFICACION>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Razon_social_cont']">
                     <tns:RAZON_SOCIAL>
                        <xsl:value-of select="ns0:Column[@name='Razon_social_cont']"/>
                     </tns:RAZON_SOCIAL>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Id_tipo_persona_cont']">
                     <tns:TIPO_PERSONA>
                        <xsl:value-of select="ns0:Column[@name='Id_tipo_persona_cont']"/>
                     </tns:TIPO_PERSONA>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Email_cont']">
                     <tns:EMAIL>
                        <xsl:value-of select="ns0:Column[@name='Email_cont']"/>
                     </tns:EMAIL>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Telefono_cont']">
                     <tns:TELEFONO>
                        <xsl:value-of select="ns0:Column[@name='Telefono_cont']"/>
                     </tns:TELEFONO>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Telefono_ofic_cont']">
                     <tns:TELEFONO_OFICINA>
                        <xsl:value-of select="ns0:Column[@name='Telefono_ofic_cont']"/>
                     </tns:TELEFONO_OFICINA>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Celular_cont']">
                     <tns:CELULAR>
                        <xsl:value-of select="ns0:Column[@name='Celular_cont']"/>
                     </tns:CELULAR>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Direccion_cont']">
                     <tns:DIRECCION>
                        <xsl:value-of select="ns0:Column[@name='Direccion_cont']"/>
                     </tns:DIRECCION>
                  </xsl:if>
               </tns:CONTRATANTE>
               <tns:OBJETO_POLIZA>
                  <xsl:if test="ns0:Column[@name='Cod_ramo']">
                     <tns:COD_RAMO>
                        <xsl:value-of select="ns0:Column[@name='Cod_ramo']"/>
                     </tns:COD_RAMO>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Ramo']">
                     <tns:DESC_RAMO>
                        <xsl:value-of select="ns0:Column[@name='Ramo']"/>
                     </tns:DESC_RAMO>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Nro_poliza']">
                     <tns:NUMERO_POLIZA>
                        <xsl:value-of select="ns0:Column[@name='Nro_poliza']"/>
                     </tns:NUMERO_POLIZA>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Poliza_inicial']">
                     <tns:NUMERO_POLIZA_INICIAL>
                        <xsl:value-of select="ns0:Column[@name='Poliza_inicial']"/>
                     </tns:NUMERO_POLIZA_INICIAL>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Poliza_Secuencia']">
                     <tns:SECUENCIAL_POLIZA>
                        <xsl:value-of select="ns0:Column[@name='Poliza_Secuencia']"/>
                     </tns:SECUENCIAL_POLIZA>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Fecha_desde']">
                     <tns:VIGENCIA_DESDE>
                        <xsl:value-of select="ns0:Column[@name='Fecha_desde']"/>
                     </tns:VIGENCIA_DESDE>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Fecha_Hasta']">
                     <tns:VIGENCIA_HASTA>
                        <xsl:value-of select="ns0:Column[@name='Fecha_Hasta']"/>
                     </tns:VIGENCIA_HASTA>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Id_poliza']">
                     <tns:ID_POLIZA>
                        <xsl:value-of select="ns0:Column[@name='Id_poliza']"/>
                     </tns:ID_POLIZA>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Id_tipo_poliza']">
                     <tns:ID_TIPO_POLIZA>
                        <xsl:value-of select="ns0:Column[@name='Id_tipo_poliza']"/>
                     </tns:ID_TIPO_POLIZA>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Tipo_poliza']">
                     <tns:TIPO_POLIZA>
                        <xsl:value-of select="ns0:Column[@name='Tipo_poliza']"/>
                     </tns:TIPO_POLIZA>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Cantidad_letras']">
                     <tns:CANTIDAD_LETRAS>
                        <xsl:value-of select="ns0:Column[@name='Cantidad_letras']"/>
                     </tns:CANTIDAD_LETRAS>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Estatus']">
                     <tns:ESTATUS>
                        <xsl:value-of select="ns0:Column[@name='Estatus']"/>
                     </tns:ESTATUS>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Id_endoso']">
                     <tns:ID_ENDOSO>
                        <xsl:value-of select="ns0:Column[@name='Id_endoso']"/>
                     </tns:ID_ENDOSO>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Tipo_endoso']">
                     <tns:TIPO_ENDOSO>
                        <xsl:value-of select="ns0:Column[@name='Tipo_endoso']"/>
                     </tns:TIPO_ENDOSO>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Cod_tipo_endoso']">
                     <tns:CODIGO_TIPO_ENDOSO>
                        <xsl:value-of select="ns0:Column[@name='Cod_tipo_endoso']"/>
                     </tns:CODIGO_TIPO_ENDOSO>
                  </xsl:if>
               </tns:OBJETO_POLIZA>
               <tns:PERSONA_ASEGURADA>
                  <xsl:if test="ns0:Column[@name='Apellido_aseg']">
                     <tns:APELLIDO>
                        <xsl:value-of select="ns0:Column[@name='Apellido_aseg']"/>
                     </tns:APELLIDO>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Id_aseg']">
                     <tns:ID_ASEGURADO>
                        <xsl:value-of select="ns0:Column[@name='Id_aseg']"/>
                     </tns:ID_ASEGURADO>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Id_tipo_persona_aseg']">
                     <tns:ID_TIPO_PERSONA>
                        <xsl:value-of select="ns0:Column[@name='Id_tipo_persona_aseg']"/>
                     </tns:ID_TIPO_PERSONA>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Nombre_aseg']">
                     <tns:NOMBRE>
                        <xsl:value-of select="ns0:Column[@name='Nombre_aseg']"/>
                     </tns:NOMBRE>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Identificacion_aseg']">
                     <tns:NUMERO_IDENTIFICACION>
                        <xsl:value-of select="ns0:Column[@name='Identificacion_aseg']"/>
                     </tns:NUMERO_IDENTIFICACION>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Razon_social_aseg']">
                     <tns:RAZON_SOCIAL_ASEGURADO>
                        <xsl:value-of select="ns0:Column[@name='Razon_social_aseg']"/>
                     </tns:RAZON_SOCIAL_ASEGURADO>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Email_aseg']">
                     <tns:EMAIL>
                        <xsl:value-of select="ns0:Column[@name='Email_aseg']"/>
                     </tns:EMAIL>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Telefono_aseg']">
                     <tns:TELEFONO>
                        <xsl:value-of select="ns0:Column[@name='Telefono_aseg']"/>
                     </tns:TELEFONO>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Telefono_ofic_aseg']">
                     <tns:TELEFONO_OFICINA>
                        <xsl:value-of select="ns0:Column[@name='Telefono_ofic_aseg']"/>
                     </tns:TELEFONO_OFICINA>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Celular_aseg']">
                     <tns:CELULAR>
                        <xsl:value-of select="ns0:Column[@name='Celular_aseg']"/>
                     </tns:CELULAR>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Direccion_aseg']">
                     <tns:DIRECCION>
                        <xsl:value-of select="ns0:Column[@name='Direccion_aseg']"/>
                     </tns:DIRECCION>
                  </xsl:if>
               </tns:PERSONA_ASEGURADA>
               <tns:DETALLE_POLIZA>
                  <xsl:if test="ns0:Column[@name='Fecha_facturacion']">
                     <tns:FECHA_FACTURACION>
                        <xsl:value-of select="ns0:Column[@name='Fecha_facturacion']"/>
                     </tns:FECHA_FACTURACION>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Cod_forma_pago']">
                     <tns:ID_FORMA_PAGO>
                        <xsl:value-of select="ns0:Column[@name='Cod_forma_pago']"/>
                     </tns:ID_FORMA_PAGO>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Forma_pago']">
                     <tns:FORMA_PAGO>
                        <xsl:value-of select="ns0:Column[@name='Forma_pago']"/>
                     </tns:FORMA_PAGO>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Cod_frecuencia_pago']">
                     <tns:ID_FRECUENCIA_PAGO>
                        <xsl:value-of select="ns0:Column[@name='Cod_frecuencia_pago']"/>
                     </tns:ID_FRECUENCIA_PAGO>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Frecuencia_pago']">
                     <tns:FRECUENCIA_PAGO>
                        <xsl:value-of select="ns0:Column[@name='Frecuencia_pago']"/>
                     </tns:FRECUENCIA_PAGO>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Porc_comision']">
                     <tns:PORCENTAJE_COMISION>
                        <xsl:value-of select="ns0:Column[@name='Porc_comision']"/>
                     </tns:PORCENTAJE_COMISION>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Prima_bruta']">
                     <tns:PRIMA_BRUTA>
                        <xsl:value-of select="ns0:Column[@name='Prima_bruta']"/>
                     </tns:PRIMA_BRUTA>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Porc_impuesto']">
                     <tns:PORCENTAJE_IMPUESTO>
                        <xsl:value-of select="ns0:Column[@name='Porc_impuesto']"/>
                     </tns:PORCENTAJE_IMPUESTO>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Impuesto']">
                     <tns:IMPUESTO>
                        <xsl:value-of select="ns0:Column[@name='Impuesto']"/>
                     </tns:IMPUESTO>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Prima_neta']">
                     <tns:PRIMA_NETA>
                        <xsl:value-of select="ns0:Column[@name='Prima_neta']"/>
                     </tns:PRIMA_NETA>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Nro_Factura']">
                     <tns:NUMERO_FACTURA>
                        <xsl:value-of select="ns0:Column[@name='Nro_Factura']"/>
                     </tns:NUMERO_FACTURA>
                  </xsl:if>
               </tns:DETALLE_POLIZA>
            </tns:INFO_POLIZAS>
         </xsl:for-each>
      </tns:INFO_POLIZAS>
   </xsl:template>
</xsl:stylesheet>
