<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/sp/LegalizarRecibosDS" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source/>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../Database/LegalizarRecibosDS_sp.xsd"/>
            <oracle-xsl-mapper:rootElement name="InputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/LegalizarRecibosDS"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [THU AUG 26 17:39:58 COT 2021].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="NumeroPoliza"/>
   <xsl:param name="NumeroReferencia"/>
   <xsl:param name="Monto"/>
   <xsl:param name="Cedula"/>
   <xsl:param name="TipoCedula"/>
   <xsl:param name="Sucursal"/>
   <xsl:param name="FechaOperacion"/>
   <xsl:param name="Usuario"/>
   <xsl:param name="FormaPago"/>
   <xsl:param name="MarcaPoliza"/>
   <xsl:template match="/">
      <tns:InputParameters>
         <tns:PVA_NPOLIZA>
            <xsl:value-of select="$NumeroPoliza"/>
         </tns:PVA_NPOLIZA>
         <tns:PNU_MONTO>
            <xsl:value-of select="$Monto"/>
         </tns:PNU_MONTO>
         <tns:PNU_SECUENCIA>
            <xsl:value-of select="$NumeroReferencia"/>
         </tns:PNU_SECUENCIA>
         <tns:PVA_CEDULA>
            <xsl:value-of select="$Cedula"/>
         </tns:PVA_CEDULA>
         <tns:PVA_CDTIPOCED>
            <xsl:value-of select="$TipoCedula"/>
         </tns:PVA_CDTIPOCED>
         <tns:PVA_OFICINA>
            <xsl:value-of select="$Sucursal"/>
         </tns:PVA_OFICINA>
         <tns:PDA_FEOPERACION>
            <xsl:value-of select="$FechaOperacion"/>
         </tns:PDA_FEOPERACION>
         <tns:PVA_USER>
            <xsl:value-of select="$Usuario"/>
         </tns:PVA_USER>
         <tns:PVA_FORMA_PAGO>
            <xsl:value-of select="$FormaPago"/>
         </tns:PVA_FORMA_PAGO>
         <tns:PNU_MARCAPOLI>
            <xsl:value-of select="$MarcaPoliza"/>
         </tns:PNU_MARCAPOLI>
      </tns:InputParameters>
   </xsl:template>
</xsl:stylesheet>
