<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="CrearActividadGAD"
     targetNamespace="http://sura.com.pa/CrearActividadGAD/"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:WL5G3N1="http://sura.com.pa/CrearActividadGAD/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="ExpCrearActividadGAD">
        <plnk:role name="CrearActividadGAD" portType="WL5G3N1:CrearActividadGAD"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://sura.com.pa/CrearActividadGAD/" location="Exp_CrearActividadGADPS.wsdl"/>
</wsdl:definitions>
