<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:tns="http://xmlns.sura.com/MensajeIntegracion/DominioPago/PagoMI/V1" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:ns0="http://sura.com.pa/afiliarInfoBnk/" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:dcomcom="http://xmlns.sura.com/ObjetoEmpresarial/DominioComun/Comun/V1"
                xmlns:dpagpag="http://xmlns.sura.com/ObjetoIntegracion/DominioPago/Pago/V1">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../../ComponentesComunes/WSDL_Externos/afiliarInfoBnk.wsdl"/>
            <oracle-xsl-mapper:rootElement name="vincularInfoBnk" namespace="http://sura.com.pa/afiliarInfoBnk/"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../../ComponentesComunes/WSDL/xsd/DominioPago/Pago/V1/PagoMIV1.xsd"/>
            <oracle-xsl-mapper:rootElement name="VincularClienteInfoBancariaMsjSol" namespace="http://xmlns.sura.com/MensajeIntegracion/DominioPago/PagoMI/V1"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [THU JUN 11 00:39:43 COT 2020].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="codigoOperacion"/>
   <xsl:param name="fechaProcesamiento"/>
   <xsl:param name="idTransaccionOsb"/>
   <xsl:template match="/">
      <tns:VincularClienteInfoBancariaMsjSol>
         <tns:CabeceraSol>
            <dcomcom:CodigoOperacion>
               <xsl:value-of select="$codigoOperacion"/>
            </dcomcom:CodigoOperacion>
            <dcomcom:FechaProcesamiento>
               <xsl:value-of select="$fechaProcesamiento"/>
            </dcomcom:FechaProcesamiento>
            <dcomcom:FechaTransaccion>
               <xsl:value-of select="$fechaProcesamiento"/>
            </dcomcom:FechaTransaccion>
            <dcomcom:IdTransaccionOsb>
               <xsl:value-of select="$idTransaccionOsb"/>
            </dcomcom:IdTransaccionOsb>
            <dcomcom:SistemaDestino>PP</dcomcom:SistemaDestino>
            <dcomcom:SistemaOrigen>Pasarela</dcomcom:SistemaOrigen>
         </tns:CabeceraSol>
         <tns:Beneficiario>
            <xsl:if test="/ns0:vincularInfoBnk/emailCliente">
               <dcomcom:Email>
                  <xsl:value-of select="/ns0:vincularInfoBnk/emailCliente"/>
               </dcomcom:Email>
            </xsl:if>
            <dcomcom:Nombre>
               <xsl:value-of select="/ns0:vincularInfoBnk/nomCliente"/>
            </dcomcom:Nombre>
            <dcomcom:Alias>
               <xsl:value-of select="/ns0:vincularInfoBnk/idUsuario"/>
            </dcomcom:Alias>
            <dcomcom:NumeroIdentificacion>
               <xsl:value-of select="/ns0:vincularInfoBnk/idCliente"/>
            </dcomcom:NumeroIdentificacion>
         </tns:Beneficiario>
         <tns:Pago>
            <dpagpag:TipoPago>
               <xsl:value-of select="/ns0:vincularInfoBnk/medioPago"/>
            </dpagpag:TipoPago>
            <xsl:if test="/ns0:vincularInfoBnk/feCobro">
               <dpagpag:FechaCobro>
                  <xsl:value-of select="/ns0:vincularInfoBnk/feCobro"/>
               </dpagpag:FechaCobro>
            </xsl:if>
            <xsl:if test="/ns0:vincularInfoBnk/cantCuota">
               <dpagpag:CantidadCuotas>
                  <xsl:value-of select="/ns0:vincularInfoBnk/cantCuota"/>
               </dpagpag:CantidadCuotas>
            </xsl:if>
            <xsl:if test="/ns0:vincularInfoBnk/primaTotal">
               <dpagpag:MontoPrimaTotal>
                  <xsl:value-of select="/ns0:vincularInfoBnk/primaTotal"/>
               </dpagpag:MontoPrimaTotal>
            </xsl:if>
            <dpagpag:InfoPolizaPago>
               <xsl:if test="/ns0:vincularInfoBnk/numPoliza">
                  <dpagpag:NumeroPoliza>
                     <xsl:value-of select="/ns0:vincularInfoBnk/numPoliza"/>
                  </dpagpag:NumeroPoliza>
               </xsl:if>
               <xsl:if test="/ns0:vincularInfoBnk/codeProducto">
                  <dpagpag:CodigoProducto>
                     <xsl:value-of select="/ns0:vincularInfoBnk/codeProducto"/>
                  </dpagpag:CodigoProducto>
               </xsl:if>
               <xsl:if test="/ns0:vincularInfoBnk/vigIni">
                  <dpagpag:FechaVigenciaInicio>
                     <xsl:value-of select="/ns0:vincularInfoBnk/vigIni"/>
                  </dpagpag:FechaVigenciaInicio>
               </xsl:if>
               <xsl:if test="/ns0:vincularInfoBnk/vigFin">
                  <dpagpag:FechaVigenciaFin>
                     <xsl:value-of select="/ns0:vincularInfoBnk/vigFin"/>
                  </dpagpag:FechaVigenciaFin>
               </xsl:if>
            </dpagpag:InfoPolizaPago>
         </tns:Pago>
      </tns:VincularClienteInfoBancariaMsjSol>
   </xsl:template>
</xsl:stylesheet>
