<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:tns="http://www.sura.com/BssEmisionAPTODOS" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:ns0="http://www.sura.com/EmisionAPTODOS" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction"
                xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../nxsd/EmisionAPTODOS.xsd"/>
            <oracle-xsl-mapper:rootElement name="EmisionAPTODOS" namespace="http://www.sura.com/EmisionAPTODOS"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../../../ComponentesComunes/XSD_Externos/BssEmisionAPTODOS.xsd"/>
            <oracle-xsl-mapper:rootElement name="EmisionAPTODOS" namespace="http://www.sura.com/BssEmisionAPTODOS"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [MON NOV 08 11:03:24 COT 2021].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="idTransaccionOSB"/>
   <xsl:param name="idPlan"/>
   <xsl:template match="/">
      <tns:EmisionAPTODOS>
         <tns:CABECERA>
            <tns:FECHA_TRANSACCION>
               <xsl:value-of select="xp20:current-date ( )"/>
            </tns:FECHA_TRANSACCION>
            <tns:FECHA_PROCESAMIENTO>
               <xsl:value-of select="xp20:current-date ( )"/>
            </tns:FECHA_PROCESAMIENTO>
            <tns:SISTEMA_DESTINO>Premium</tns:SISTEMA_DESTINO>
            <tns:SISTEMA_ORIGEN>NubeSeguros</tns:SISTEMA_ORIGEN>
            <tns:CODIGO_OPERACION>44</tns:CODIGO_OPERACION>
            <tns:ID_TRANSACCION_OSB>
               <xsl:value-of select="$idTransaccionOSB"/>
            </tns:ID_TRANSACCION_OSB>
         </tns:CABECERA>
         <tns:CORE>P</tns:CORE>
         <tns:POLIZA>
         <xsl:if test="$idPlan">
            <tns:PLAN>
               <xsl:value-of select="$idPlan"/>
            </tns:PLAN>
          </xsl:if>
          <xsl:if test="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:id_negocio_core_legacy">
            <tns:NUMERO_POLIZA>
               <xsl:value-of select="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:id_negocio_core_legacy"/>
            </tns:NUMERO_POLIZA>
          </xsl:if>
          <xsl:if test="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:fecha_inicio_vigencia">
            <tns:VIGENCIA_DESDE>
               <xsl:value-of select="xp20:format-dateTime (/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:fecha_inicio_vigencia, &quot;[D01]-[M01]-[Y0001]&quot; )"/>
            </tns:VIGENCIA_DESDE>
          </xsl:if>
          <xsl:if test="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:fecha_inicio_vigencia">
            <tns:VIGENCIA_HASTA>
               <xsl:value-of select="xp20:format-dateTime (xp20:add-dayTimeDuration-to-dateTime (/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:fecha_inicio_vigencia, concat (&quot;P&quot;, /ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:riesgos/ns0:persona/ns0:plan/ns0:plan_accidente_personal_para_todos/ns0:temporalidad, &quot;Y&quot; ) ), &quot;[D01]-[M01]-[Y0001]&quot; )"/>              
            </tns:VIGENCIA_HASTA>
          </xsl:if>
          <xsl:if test="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:riesgos/ns0:persona/ns0:plan/ns0:plan_accidente_personal_para_todos/ns0:valor_asegurado">
            <tns:SUMA_ASEGURADA>
               <xsl:value-of select="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:riesgos/ns0:persona/ns0:plan/ns0:plan_accidente_personal_para_todos/ns0:valor_asegurado"/>
            </tns:SUMA_ASEGURADA>
          </xsl:if>
          <xsl:if test="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:riesgos/ns0:persona/ns0:plan/ns0:plan_accidente_personal_para_todos/ns0:temporalidad">
            <tns:DURACION>
               <xsl:value-of select="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:riesgos/ns0:persona/ns0:plan/ns0:plan_accidente_personal_para_todos/ns0:temporalidad"/>
            </tns:DURACION>
          </xsl:if>
          <xsl:if test="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:usuario_application_premium">
            <tns:USUARIO>
               <xsl:value-of select="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:usuario_application_premium"/>
            </tns:USUARIO>
          </xsl:if>
         </tns:POLIZA>
         <tns:CONTRATANTE>
            <xsl:if test="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:tomador/ns0:tomador_negocio_producto_accidente_personal_para_todos/ns0:numero_documento">
               <tns:NUMERO_IDENTIFICACION>
                  <xsl:value-of select="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:tomador/ns0:tomador_negocio_producto_accidente_personal_para_todos/ns0:numero_documento"/>
               </tns:NUMERO_IDENTIFICACION>
            </xsl:if>
            <xsl:if test="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:tomador/ns0:tomador_negocio_producto_accidente_personal_para_todos/ns0:primer_nombre">
               <tns:NOMBRE>
                  <xsl:value-of select="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:tomador/ns0:tomador_negocio_producto_accidente_personal_para_todos/ns0:primer_nombre"/>
               </tns:NOMBRE>
            </xsl:if>
            <xsl:if test="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:tomador/ns0:tomador_negocio_producto_accidente_personal_para_todos/ns0:segundo_nombre">
               <tns:SEGUNDO_NOMBRE>
                  <xsl:value-of select="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:tomador/ns0:tomador_negocio_producto_accidente_personal_para_todos/ns0:segundo_nombre"/>
               </tns:SEGUNDO_NOMBRE>
            </xsl:if>
            <xsl:if test="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:tomador/ns0:tomador_negocio_producto_accidente_personal_para_todos/ns0:primer_apellido">
               <tns:APELLIDO>
                  <xsl:value-of select="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:tomador/ns0:tomador_negocio_producto_accidente_personal_para_todos/ns0:primer_apellido"/>
               </tns:APELLIDO>
            </xsl:if>
            <xsl:if test="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:tomador/ns0:tomador_negocio_producto_accidente_personal_para_todos/ns0:segundo_apellido">
               <tns:SEGUNDO_APELLIDO>
                  <xsl:value-of select="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:tomador/ns0:tomador_negocio_producto_accidente_personal_para_todos/ns0:segundo_apellido"/>
               </tns:SEGUNDO_APELLIDO>
            </xsl:if>
            <xsl:if test="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:tomador/ns0:tomador_negocio_producto_accidente_personal_para_todos/ns0:celular">
               <tns:TELEFONO>
                  <xsl:value-of select="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:tomador/ns0:tomador_negocio_producto_accidente_personal_para_todos/ns0:celular"/>
               </tns:TELEFONO>
            </xsl:if>
            <xsl:if test="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:tomador/ns0:tomador_negocio_producto_accidente_personal_para_todos/ns0:sexo">
               <tns:SEXO>
                  <xsl:value-of select="substring (/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:tomador/ns0:tomador_negocio_producto_accidente_personal_para_todos/ns0:sexo, 1, 1 )"/>
               </tns:SEXO>
            </xsl:if>
            <xsl:if test="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:tomador/ns0:tomador_negocio_producto_accidente_personal_para_todos/ns0:estado_civil">
               <tns:ESTADO_CIVIL>
                  <xsl:value-of select="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:tomador/ns0:tomador_negocio_producto_accidente_personal_para_todos/ns0:estado_civil"/>
               </tns:ESTADO_CIVIL>
            </xsl:if>
            <xsl:if test="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:tomador/ns0:tomador_negocio_producto_accidente_personal_para_todos/ns0:fecha_nacimiento">
               <tns:FECHA_NACIMIENTO>
                  <xsl:value-of select='xp20:format-dateTime (/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:tomador/ns0:tomador_negocio_producto_accidente_personal_para_todos/ns0:fecha_nacimiento, "[D01]-[M01]-[Y0001]" )'/>
               </tns:FECHA_NACIMIENTO>
            </xsl:if>
            <xsl:if test="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:tomador/ns0:tomador_negocio_producto_accidente_personal_para_todos/ns0:nacionalidad">
               <tns:NACIONALIDAD>
                  <xsl:value-of select="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:tomador/ns0:tomador_negocio_producto_accidente_personal_para_todos/ns0:nacionalidad"/>
               </tns:NACIONALIDAD>
            </xsl:if>
         </tns:CONTRATANTE>
         <tns:OBJETO_ASEGURADO>
            <tns:PERSONA_ASEGURADA>
               <tns:BENEFICIARIO>
                  <xsl:if test="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:riesgos/ns0:persona/ns0:beneficiarios/ns0:beneficiarios_riesgos_negocio_producto_accidente_personal_para_todos/ns0:primer_nombre">
                     <tns:NOMBRE>
                        <xsl:value-of select='concat (/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:riesgos/ns0:persona/ns0:beneficiarios/ns0:beneficiarios_riesgos_negocio_producto_accidente_personal_para_todos/ns0:primer_nombre," ",/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:riesgos/ns0:persona/ns0:beneficiarios/ns0:beneficiarios_riesgos_negocio_producto_accidente_personal_para_todos/ns0:segundo_nombre)'/>
                     </tns:NOMBRE>
                  </xsl:if>
                  <xsl:if test="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:riesgos/ns0:persona/ns0:beneficiarios/ns0:beneficiarios_riesgos_negocio_producto_accidente_personal_para_todos/ns0:primer_apellido">
                     <tns:APELLIDO>
                        <xsl:value-of select='concat (/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:riesgos/ns0:persona/ns0:beneficiarios/ns0:beneficiarios_riesgos_negocio_producto_accidente_personal_para_todos/ns0:primer_apellido," ",/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:riesgos/ns0:persona/ns0:beneficiarios/ns0:beneficiarios_riesgos_negocio_producto_accidente_personal_para_todos/ns0:segundo_apellido)'/>
                     </tns:APELLIDO>
                  </xsl:if>
                  <xsl:if test="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:riesgos/ns0:persona/ns0:beneficiarios/ns0:beneficiarios_riesgos_negocio_producto_accidente_personal_para_todos/ns0:numero_documento">
                     <tns:NUMERO_IDENTIFICACION>
                        <xsl:value-of select="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:riesgos/ns0:persona/ns0:beneficiarios/ns0:beneficiarios_riesgos_negocio_producto_accidente_personal_para_todos/ns0:numero_documento"/>
                     </tns:NUMERO_IDENTIFICACION>
                  </xsl:if>
                  <xsl:if test="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:riesgos/ns0:persona/ns0:beneficiarios/ns0:beneficiarios_riesgos_negocio_producto_accidente_personal_para_todos/ns0:parentesco_beneficiario">
                     <tns:PARENTESCO>
                        <xsl:value-of select="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:riesgos/ns0:persona/ns0:beneficiarios/ns0:beneficiarios_riesgos_negocio_producto_accidente_personal_para_todos/ns0:parentesco_beneficiario"/>
                     </tns:PARENTESCO>
                  </xsl:if>
                  <xsl:if test="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:riesgos/ns0:persona/ns0:beneficiarios/ns0:beneficiarios_riesgos_negocio_producto_accidente_personal_para_todos/ns0:administrador_fiduciario">
                     <tns:ADMINISTRADOR_FIDUCIARIO>
                        <xsl:value-of select="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:riesgos/ns0:persona/ns0:beneficiarios/ns0:beneficiarios_riesgos_negocio_producto_accidente_personal_para_todos/ns0:administrador_fiduciario"/>
                     </tns:ADMINISTRADOR_FIDUCIARIO>
                  </xsl:if>
                  <xsl:if test="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:riesgos/ns0:persona/ns0:beneficiarios/ns0:beneficiarios_riesgos_negocio_producto_accidente_personal_para_todos/ns0:tipo_beneficiario">
                     <tns:JERARQUIA>
                        <xsl:value-of select="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:riesgos/ns0:persona/ns0:beneficiarios/ns0:beneficiarios_riesgos_negocio_producto_accidente_personal_para_todos/ns0:tipo_beneficiario"/>
                     </tns:JERARQUIA>
                  </xsl:if>
                  <xsl:if test="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:riesgos/ns0:persona/ns0:beneficiarios/ns0:beneficiarios_riesgos_negocio_producto_accidente_personal_para_todos/ns0:porcentaje_beneficiario">
                     <tns:PORCENTAJE_BENEFICIARIO>
                        <xsl:value-of select="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:riesgos/ns0:persona/ns0:beneficiarios/ns0:beneficiarios_riesgos_negocio_producto_accidente_personal_para_todos/ns0:porcentaje_beneficiario"/>
                     </tns:PORCENTAJE_BENEFICIARIO>
                  </xsl:if>
               </tns:BENEFICIARIO>
               <xsl:if test="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:riesgos/ns0:persona/ns0:asegurado/ns0:asegurado_riesgos_negocio_producto_accidente_personal_para_todos/ns0:numero_documento">
                  <tns:NUMERO_IDENTIFICACION>
                     <xsl:value-of select="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:riesgos/ns0:persona/ns0:asegurado/ns0:asegurado_riesgos_negocio_producto_accidente_personal_para_todos/ns0:numero_documento"/>
                  </tns:NUMERO_IDENTIFICACION>
               </xsl:if>
               <xsl:if test="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:riesgos/ns0:persona/ns0:asegurado/ns0:asegurado_riesgos_negocio_producto_accidente_personal_para_todos/ns0:primer_nombre">
                  <tns:NOMBRE>
                     <xsl:value-of select="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:riesgos/ns0:persona/ns0:asegurado/ns0:asegurado_riesgos_negocio_producto_accidente_personal_para_todos/ns0:primer_nombre"/>
                  </tns:NOMBRE>
               </xsl:if>
               <xsl:if test="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:riesgos/ns0:persona/ns0:asegurado/ns0:asegurado_riesgos_negocio_producto_accidente_personal_para_todos/ns0:segundo_nombre">
                  <tns:SEGUNDO_NOMBRE>
                     <xsl:value-of select="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:riesgos/ns0:persona/ns0:asegurado/ns0:asegurado_riesgos_negocio_producto_accidente_personal_para_todos/ns0:segundo_nombre"/>
                  </tns:SEGUNDO_NOMBRE>
               </xsl:if>
               <xsl:if test="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:riesgos/ns0:persona/ns0:asegurado/ns0:asegurado_riesgos_negocio_producto_accidente_personal_para_todos/ns0:primer_apellido">
                  <tns:APELLIDO>
                     <xsl:value-of select="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:riesgos/ns0:persona/ns0:asegurado/ns0:asegurado_riesgos_negocio_producto_accidente_personal_para_todos/ns0:primer_apellido"/>
                  </tns:APELLIDO>
               </xsl:if>
               <xsl:if test="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:riesgos/ns0:persona/ns0:asegurado/ns0:asegurado_riesgos_negocio_producto_accidente_personal_para_todos/ns0:segundo_apellido">
                  <tns:SEGUNDO_APELLIDO>
                     <xsl:value-of select="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:riesgos/ns0:persona/ns0:asegurado/ns0:asegurado_riesgos_negocio_producto_accidente_personal_para_todos/ns0:segundo_apellido"/>
                  </tns:SEGUNDO_APELLIDO>
               </xsl:if>
               <xsl:if test="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:riesgos/ns0:persona/ns0:asegurado/ns0:asegurado_riesgos_negocio_producto_accidente_personal_para_todos/ns0:celular">
                  <tns:CELULAR>
                     <xsl:value-of select="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:riesgos/ns0:persona/ns0:asegurado/ns0:asegurado_riesgos_negocio_producto_accidente_personal_para_todos/ns0:celular"/>
                  </tns:CELULAR>
               </xsl:if>
               <xsl:if test="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:riesgos/ns0:persona/ns0:asegurado/ns0:asegurado_riesgos_negocio_producto_accidente_personal_para_todos/ns0:sexo">
                  <tns:SEXO>
                     <xsl:value-of select="substring (/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:riesgos/ns0:persona/ns0:asegurado/ns0:asegurado_riesgos_negocio_producto_accidente_personal_para_todos/ns0:sexo, 1, 1 )"/>
                  </tns:SEXO>
               </xsl:if>
               <xsl:if test="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:riesgos/ns0:persona/ns0:asegurado/ns0:asegurado_riesgos_negocio_producto_accidente_personal_para_todos/ns0:estado_civil">
                  <tns:ESTADO_CIVIL>
                     <xsl:value-of select="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:riesgos/ns0:persona/ns0:asegurado/ns0:asegurado_riesgos_negocio_producto_accidente_personal_para_todos/ns0:estado_civil"/>
                  </tns:ESTADO_CIVIL>
               </xsl:if>
               <xsl:if test="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:riesgos/ns0:persona/ns0:asegurado/ns0:asegurado_riesgos_negocio_producto_accidente_personal_para_todos/ns0:fecha_nacimiento">
                  <tns:FECHA_NACIMIENTO>
                     <xsl:value-of select='xp20:format-dateTime (/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:riesgos/ns0:persona/ns0:asegurado/ns0:asegurado_riesgos_negocio_producto_accidente_personal_para_todos/ns0:fecha_nacimiento, "[D01]-[M01]-[Y0001]" )'/>
                  </tns:FECHA_NACIMIENTO>
               </xsl:if>
               <xsl:if test="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:riesgos/ns0:persona/ns0:asegurado/ns0:asegurado_riesgos_negocio_producto_accidente_personal_para_todos/ns0:nacionalidad">
                  <tns:NACIONALIDAD>
                     <xsl:value-of select="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:riesgos/ns0:persona/ns0:asegurado/ns0:asegurado_riesgos_negocio_producto_accidente_personal_para_todos/ns0:nacionalidad"/>
                  </tns:NACIONALIDAD>
               </xsl:if>
               <tns:DIRECCIONES>
                  <tns:TIPO>R</tns:TIPO>
                  <xsl:if test="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:riesgos/ns0:persona/ns0:asegurado/ns0:asegurado_riesgos_negocio_producto_accidente_personal_para_todos/ns0:nacionalidad">
                     <tns:COD_PAIS>PAN</tns:COD_PAIS>
                  </xsl:if>
                  <xsl:if test="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:riesgos/ns0:persona/ns0:asegurado/ns0:asegurado_riesgos_negocio_producto_accidente_personal_para_todos/ns0:provincia">
                     <tns:COD_PROVINCIA>
                        <xsl:value-of select="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:riesgos/ns0:persona/ns0:asegurado/ns0:asegurado_riesgos_negocio_producto_accidente_personal_para_todos/ns0:provincia"/>
                     </tns:COD_PROVINCIA>
                  </xsl:if>
                  <xsl:if test="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:riesgos/ns0:persona/ns0:asegurado/ns0:asegurado_riesgos_negocio_producto_accidente_personal_para_todos/ns0:distrito">
                     <tns:COD_DISTRITO>
                        <xsl:value-of select='substring-before (/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:riesgos/ns0:persona/ns0:asegurado/ns0:asegurado_riesgos_negocio_producto_accidente_personal_para_todos/ns0:distrito, "-" )'/>
                     </tns:COD_DISTRITO>
                  </xsl:if>
                  <xsl:if test="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:riesgos/ns0:persona/ns0:asegurado/ns0:asegurado_riesgos_negocio_producto_accidente_personal_para_todos/ns0:corregimiento">
                     <tns:COD_CORREGIMIENTO>
                        <xsl:value-of select='substring-before (/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:riesgos/ns0:persona/ns0:asegurado/ns0:asegurado_riesgos_negocio_producto_accidente_personal_para_todos/ns0:corregimiento, "-" )'/>
                     </tns:COD_CORREGIMIENTO>
                  </xsl:if>
                  <xsl:if test="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:riesgos/ns0:persona/ns0:asegurado/ns0:asegurado_riesgos_negocio_producto_accidente_personal_para_todos/ns0:barrio">
                     <tns:COD_BARRIO>
                        <xsl:value-of select="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:riesgos/ns0:persona/ns0:asegurado/ns0:asegurado_riesgos_negocio_producto_accidente_personal_para_todos/ns0:barrio"/>
                     </tns:COD_BARRIO>
                  </xsl:if>
                  <xsl:if test="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:riesgos/ns0:persona/ns0:asegurado/ns0:asegurado_riesgos_negocio_producto_accidente_personal_para_todos/ns0:calle">
                     <tns:CALLE>
                        <xsl:value-of select="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:riesgos/ns0:persona/ns0:asegurado/ns0:asegurado_riesgos_negocio_producto_accidente_personal_para_todos/ns0:calle"/>
                     </tns:CALLE>
                  </xsl:if>
                  <xsl:if test="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:riesgos/ns0:persona/ns0:asegurado/ns0:asegurado_riesgos_negocio_producto_accidente_personal_para_todos/ns0:barrio">
                     <tns:URBANIZACION>
                        <xsl:value-of select="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:riesgos/ns0:persona/ns0:asegurado/ns0:asegurado_riesgos_negocio_producto_accidente_personal_para_todos/ns0:barrio"/>
                     </tns:URBANIZACION>
                  </xsl:if>
                  <xsl:if test="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:riesgos/ns0:persona/ns0:asegurado/ns0:asegurado_riesgos_negocio_producto_accidente_personal_para_todos/ns0:casa_edificio_apto">
                     <tns:CASA>
                        <xsl:value-of select="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:riesgos/ns0:persona/ns0:asegurado/ns0:asegurado_riesgos_negocio_producto_accidente_personal_para_todos/ns0:casa_edificio_apto"/>
                     </tns:CASA>
                  </xsl:if>
                  <xsl:if test="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:riesgos/ns0:persona/ns0:asegurado/ns0:asegurado_riesgos_negocio_producto_accidente_personal_para_todos/ns0:casa_edificio_apto">
                     <tns:DIRECCION>
                        <xsl:value-of select='concat (/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:riesgos/ns0:persona/ns0:asegurado/ns0:asegurado_riesgos_negocio_producto_accidente_personal_para_todos/ns0:barrio," ", /ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:riesgos/ns0:persona/ns0:asegurado/ns0:asegurado_riesgos_negocio_producto_accidente_personal_para_todos/ns0:calle, " ", /ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:riesgos/ns0:persona/ns0:asegurado/ns0:asegurado_riesgos_negocio_producto_accidente_personal_para_todos/ns0:casa_edificio_apto)'/>
                     </tns:DIRECCION>
                  </xsl:if>
                  <xsl:if test="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:riesgos/ns0:persona/ns0:asegurado/ns0:asegurado_riesgos_negocio_producto_accidente_personal_para_todos/ns0:telefono">
                     <tns:TELEFONO>
                        <xsl:value-of select="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:riesgos/ns0:persona/ns0:asegurado/ns0:asegurado_riesgos_negocio_producto_accidente_personal_para_todos/ns0:telefono"/>
                     </tns:TELEFONO>
                  </xsl:if>
                  <xsl:if test="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:riesgos/ns0:persona/ns0:asegurado/ns0:asegurado_riesgos_negocio_producto_accidente_personal_para_todos/ns0:email">
                     <tns:EMAIL>
                        <xsl:value-of select="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:riesgos/ns0:persona/ns0:asegurado/ns0:asegurado_riesgos_negocio_producto_accidente_personal_para_todos/ns0:email"/>
                     </tns:EMAIL>
                  </xsl:if>
               </tns:DIRECCIONES>
            </tns:PERSONA_ASEGURADA>
         </tns:OBJETO_ASEGURADO>
         <tns:INFO_ACTIVIDAD_ECONOMICA>
            <tns:ACTIVIDAD_ECONOMICA/>
            <xsl:if test="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:riesgos/ns0:persona/ns0:asegurado/ns0:asegurado_riesgos_negocio_producto_accidente_personal_para_todos/ns0:ocupacion">
               <tns:ACTIVIDAD>
                  <xsl:value-of select="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:riesgos/ns0:persona/ns0:asegurado/ns0:asegurado_riesgos_negocio_producto_accidente_personal_para_todos/ns0:ocupacion"/>
               </tns:ACTIVIDAD>
            </xsl:if>
            <xsl:if test="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:riesgos/ns0:persona/ns0:asegurado/ns0:asegurado_riesgos_negocio_producto_accidente_personal_para_todos/ns0:es_pep">
               <tns:CARGO_PUBLICO>
                  <xsl:value-of select="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:riesgos/ns0:persona/ns0:asegurado/ns0:asegurado_riesgos_negocio_producto_accidente_personal_para_todos/ns0:es_pep"/>
               </tns:CARGO_PUBLICO>
            </xsl:if>
            <xsl:if test="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:riesgos/ns0:persona/ns0:asegurado/ns0:asegurado_riesgos_negocio_producto_accidente_personal_para_todos/ns0:cargo_pep">
               <tns:CARGO_OCUPADO>
                  <xsl:value-of select="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:riesgos/ns0:persona/ns0:asegurado/ns0:asegurado_riesgos_negocio_producto_accidente_personal_para_todos/ns0:cargo_pep"/>
               </tns:CARGO_OCUPADO>
            </xsl:if>
            <tns:PEP_ACTUAL/>
            <xsl:if test="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:riesgos/ns0:persona/ns0:asegurado/ns0:asegurado_riesgos_negocio_producto_accidente_personal_para_todos/ns0:ingresos_anuales_principal">
               <tns:CODIGO_INGRESO_ANUAL>
                  <xsl:value-of select="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:riesgos/ns0:persona/ns0:asegurado/ns0:asegurado_riesgos_negocio_producto_accidente_personal_para_todos/ns0:ingresos_anuales_principal"/>
               </tns:CODIGO_INGRESO_ANUAL>
            </xsl:if>
            <xsl:if test="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:riesgos/ns0:persona/ns0:asegurado/ns0:asegurado_riesgos_negocio_producto_accidente_personal_para_todos/ns0:ingresos_anuales_otros">
               <tns:COD_OTRO_INGRESO>
                  <xsl:value-of select="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:riesgos/ns0:persona/ns0:asegurado/ns0:asegurado_riesgos_negocio_producto_accidente_personal_para_todos/ns0:ingresos_anuales_otros"/>
               </tns:COD_OTRO_INGRESO>
            </xsl:if>
         </tns:INFO_ACTIVIDAD_ECONOMICA>
         <tns:ESTRUCTURA_COMERCIAL>
            <xsl:if test="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:estructura_venta/ns0:estructura_venta/ns0:no_peoplesoft">
               <tns:REFERENCIA>
                  <xsl:value-of select="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:estructura_venta/ns0:estructura_venta/ns0:no_peoplesoft"/>
               </tns:REFERENCIA>
            </xsl:if>
            <xsl:if test="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:estructura_venta/ns0:estructura_venta/ns0:no_peoplesoft">
               <tns:CODIGO_FUNCIONARIO>
                  <xsl:value-of select="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:estructura_venta/ns0:estructura_venta/ns0:no_peoplesoft"/>
               </tns:CODIGO_FUNCIONARIO>
            </xsl:if>
            <xsl:if test="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:estructura_venta/ns0:estructura_venta/ns0:sucursal_banco">
               <tns:SUCURSAL>
                  <xsl:value-of select="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:estructura_venta/ns0:estructura_venta/ns0:sucursal_banco"/>
               </tns:SUCURSAL>
            </xsl:if>
         </tns:ESTRUCTURA_COMERCIAL>
         <tns:INFORMACION_BANCO>
            <xsl:choose>
              <xsl:when test="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:tomador/ns0:tomador_negocio_producto_accidente_personal_para_todos/ns0:informacion_banco/ns0:informacion_banco/ns0:tag_tc and /ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:tomador/ns0:tomador_negocio_producto_accidente_personal_para_todos/ns0:informacion_banco/ns0:informacion_banco/ns0:iv_tc">
                <tns:CUENTA>
                  <xsl:value-of select="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:tomador/ns0:tomador_negocio_producto_accidente_personal_para_todos/ns0:informacion_banco/ns0:informacion_banco/ns0:numero_cuenta"/>
               </tns:CUENTA>
              </xsl:when>
              <xsl:otherwise>
                <tns:CUENTA>
                  <xsl:value-of select="concat(/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:tomador/ns0:tomador_negocio_producto_accidente_personal_para_todos/ns0:informacion_banco/ns0:informacion_banco/ns0:numero_cuenta,&quot;|&quot;,/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:tomador/ns0:tomador_negocio_producto_accidente_personal_para_todos/ns0:informacion_banco/ns0:informacion_banco/ns0:tag_tc,&quot;|&quot;,/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:tomador/ns0:tomador_negocio_producto_accidente_personal_para_todos/ns0:informacion_banco/ns0:informacion_banco/ns0:iv_tc)"/>
               </tns:CUENTA>
              </xsl:otherwise>
            </xsl:choose>
            <tns:APLICAR_PAGO>
               <xsl:value-of select="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:tomador/ns0:tomador_negocio_producto_accidente_personal_para_todos/ns0:informacion_banco/ns0:informacion_banco/ns0:cobro_exitoso"/>
            </tns:APLICAR_PAGO>
            <tns:AUTOAFILIAR>TRUE</tns:AUTOAFILIAR>
            <tns:REFERENCIA_COBRO>
               <xsl:value-of select="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:tomador/ns0:tomador_negocio_producto_accidente_personal_para_todos/ns0:informacion_banco/ns0:informacion_banco/ns0:referencia_de_pago"/>
            </tns:REFERENCIA_COBRO>
            <tns:COBRO>
               <xsl:value-of select="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:riesgos/ns0:persona/ns0:prima_comercial_resultado_calculo"/>
            </tns:COBRO>
            <tns:BANCO>
               <xsl:value-of select="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:tomador/ns0:tomador_negocio_producto_accidente_personal_para_todos/ns0:informacion_banco/ns0:informacion_banco/ns0:banco"/>
            </tns:BANCO>
            <xsl:choose>
              <xsl:when test="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:tomador/ns0:tomador_negocio_producto_accidente_personal_para_todos/ns0:informacion_banco/ns0:informacion_banco/ns0:tag_fecha_expiracion_tc and /ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:tomador/ns0:tomador_negocio_producto_accidente_personal_para_todos/ns0:informacion_banco/ns0:informacion_banco/ns0:iv_fecha_expiracion_tc">
                <tns:FECHA_VEN_TDC>
                   <xsl:value-of select="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:tomador/ns0:tomador_negocio_producto_accidente_personal_para_todos/ns0:informacion_banco/ns0:informacion_banco/ns0:fecha_expiracion_tc"/>
                </tns:FECHA_VEN_TDC>
              </xsl:when>
            </xsl:choose>
            <xsl:choose>
              <xsl:when test="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:tomador/ns0:tomador_negocio_producto_accidente_personal_para_todos/ns0:informacion_banco/ns0:informacion_banco/ns0:tag_fecha_expiracion_tc and /ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:tomador/ns0:tomador_negocio_producto_accidente_personal_para_todos/ns0:informacion_banco/ns0:informacion_banco/ns0:iv_fecha_expiracion_tc and /ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:tomador/ns0:tomador_negocio_producto_accidente_personal_para_todos/ns0:informacion_banco/ns0:informacion_banco/ns0:tag_tc and /ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:tomador/ns0:tomador_negocio_producto_accidente_personal_para_todos/ns0:informacion_banco/ns0:informacion_banco/ns0:iv_tc">
                <tns:TIPO_CUENTA>
                   <xsl:value-of select="/ns0:EmisionAPTODOS/ns0:negocio_producto_accidente_personal_para_todos/ns0:tomador/ns0:tomador_negocio_producto_accidente_personal_para_todos/ns0:informacion_banco/ns0:informacion_banco/ns0:tipo_cuenta"/>
                </tns:TIPO_CUENTA>
              </xsl:when>
            </xsl:choose>          
         </tns:INFORMACION_BANCO>
      </tns:EmisionAPTODOS>
   </xsl:template>
</xsl:stylesheet>
