-- Declare package containing conversion functions between SQL and PL/SQL types
CREATE OR REPLACE PACKAGE BPEL_CONSULTARUBICACIONCATALOG AS
   PROCEDURE pkg_nube_seguros$busca_ubicac (P_PADRE VARCHAR2,
	P_NIVEL NUMBER,
	P_HIJO OUT SYS_REFCURSOR,
	P_OK OUT INTEGER,
	P_MENSAJE OUT VARCHAR2
	);
END BPEL_CONSULTARUBICACIONCATALOG;
/
show errors
CREATE OR REPLACE PACKAGE BODY BPEL_CONSULTARUBICACIONCATALOG IS

   PROCEDURE pkg_nube_seguros$busca_ubicac (P_PADRE VARCHAR2,
	P_NIVEL NUMBER,
	P_HIJO OUT SYS_REFCURSOR,
	P_OK OUT INTEGER,
	P_MENSAJE OUT VARCHAR2
	) IS
 P_OK_ BOOLEAN;
   BEGIN
      SEGUROS.PKG_NUBE_SEGUROS.BUSCA_UBICACION(P_PADRE,
	P_NIVEL,
	P_HIJO,
	P_OK_,
	P_MENSAJE
	);
 P_OK := SYS.SQLJUTL.BOOL2INT(P_OK_);
   END pkg_nube_seguros$busca_ubicac;

END BPEL_CONSULTARUBICACIONCATALOG;
/
show errors
exit
