<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/NubeSerguros_II/Dat_ConsultarUbicacionCatalogo/ConsultarUbicacionCatalogo" name="ConsultarUbicacionCatalogo-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="ConsultarUbicacionCatalogo.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/NubeSerguros_II/Dat_ConsultarUbicacionCatalogo/ConsultarUbicacionCatalogo"/>
    <wsdl:binding name="ConsultarUbicacionCatalogo_ptt-binding" type="con:ConsultarUbicacionCatalogo_ptt" xmlns:con="http://xmlns.oracle.com/pcbpel/adapter/db/NubeSerguros_II/Dat_ConsultarUbicacionCatalogo/ConsultarUbicacionCatalogo">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="ConsultarUbicacionCatalogo">
            <soap:operation soapAction="ConsultarUbicacionCatalogo"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>