<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:ns0="http://sura.com.pa/matrizRiesgoCliente/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:tns="http://www.sura.com/MensajeIntegracion/DominioCliente/ClienteMEN/V1" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:dcomban="http://www.sura.com/ObjetoEmpresarial/DominioComun/ComunBanco/V1" xmlns:dcliubi="http://www.sura.com/ObjetoEmpresarial/DominioCliente/Ubicacion/V2" xmlns:dclicli="http://www.sura.com/ObjetoEmpresarial/DominioCliente/Cliente/V1" xmlns:ns1="http://www.sura.com/ObjetoEmpresarial/DominioCliente/Ubicacion/V1" xmlns:dutilcom="http://www.sura.com/ObjetoEmpresarial/DominioUtilitario/Comun/V1" xmlns:dcliper="http://www.sura.com/ObjetoEmpresarial/DominioCliente/Persona/V1" xmlns:dautaut="http://www.sura.com/ObjetoIntegracion/DominioAutenticacion/Autenticacion/V1" xmlns:dcomcom="http://xmlns.sura.com/ObjetoEmpresarial/DominioComun/Comun/V1" xmlns:ibmSchExtn="http://www.ibm.com/schema/extensions">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../matrizRiesgoCliente.wsdl"/>
            <oracle-xsl-mapper:rootElement name="validarRiesgoCliente" namespace="http://sura.com.pa/matrizRiesgoCliente/"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../../../ComponentesComunes/WSDL/xsd/DominioCliente/Cliente/V1/ClienteMENV1.xsd"/>
            <oracle-xsl-mapper:rootElement name="ValidarRiesgoClienteMsjSol" namespace="http://www.sura.com/MensajeIntegracion/DominioCliente/ClienteMEN/V1"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [SUN MAR 22 19:07:28 COT 2020].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="codigoOperacion"/>
   <xsl:param name="fechaProcesamiento"/>
   <xsl:param name="idTransaccion"/>
   <xsl:template match="/">
      <tns:ValidarRiesgoClienteMsjSol>
         <tns:CabeceraSol>
            <dcomcom:CodigoOperacion>
               <xsl:value-of select="$codigoOperacion"/>
            </dcomcom:CodigoOperacion>
            <dcomcom:FechaProcesamiento>
               <xsl:value-of select="$fechaProcesamiento"/>
            </dcomcom:FechaProcesamiento>
            <dcomcom:FechaTransaccion>
               <xsl:value-of select="$fechaProcesamiento"/>
            </dcomcom:FechaTransaccion>
            <dcomcom:IdTransaccionOsb>
               <xsl:value-of select="$idTransaccion"/>
            </dcomcom:IdTransaccionOsb>
            <dcomcom:SistemaDestino>INSIS</dcomcom:SistemaDestino>
            <dcomcom:SistemaOrigen>MatrizRiesgo</dcomcom:SistemaOrigen>
         </tns:CabeceraSol>
         <tns:IdPersona>
            <xsl:value-of select="/ns0:validarRiesgoCliente/idPersona"/>
         </tns:IdPersona>
         <tns:TipoIdentificacion>
            <xsl:value-of select="/ns0:validarRiesgoCliente/tipoID"/>
         </tns:TipoIdentificacion>
         <xsl:if test="/ns0:validarRiesgoCliente/codigoActividadEconomica">
            <tns:ActividadEconomica>
               <dcliper:Codigo>
                  <xsl:value-of select="/ns0:validarRiesgoCliente/codigoActividadEconomica"/>
               </dcliper:Codigo>
            </tns:ActividadEconomica>
         </xsl:if>
         <xsl:if test="/ns0:validarRiesgoCliente/codigoOcupacion">
            <tns:Ocupacion>
               <dcliper:Codigo>
                  <xsl:value-of select="/ns0:validarRiesgoCliente/codigoOcupacion"/>
               </dcliper:Codigo>
            </tns:Ocupacion>
         </xsl:if>
         <tns:Direccion>
            <xsl:if test="/ns0:validarRiesgoCliente/codigoPais">
               <dcliubi:Pais>
                  <dcliubi:Abreviatura>
                     <xsl:value-of select="/ns0:validarRiesgoCliente/codigoPais"/>
                  </dcliubi:Abreviatura>
               </dcliubi:Pais>
            </xsl:if>
            <xsl:if test="/ns0:validarRiesgoCliente/codigoProvincia">
               <dcliubi:Provincia>
                  <dcliubi:Codigo>
                     <xsl:value-of select="/ns0:validarRiesgoCliente/codigoProvincia"/>
                  </dcliubi:Codigo>
               </dcliubi:Provincia>
            </xsl:if>
         </tns:Direccion>
         <xsl:if test="/ns0:validarRiesgoCliente/expuestoPolitico">
            <tns:PoliticamenteExpuesto>
               <xsl:value-of select="/ns0:validarRiesgoCliente/expuestoPolitico"/>
            </tns:PoliticamenteExpuesto>
         </xsl:if>
         <xsl:if test="/ns0:validarRiesgoCliente/familiar_expuestoPolitico">
            <tns:FamiliarPEP>
               <xsl:value-of select="/ns0:validarRiesgoCliente/familiar_expuestoPolitico"/>
            </tns:FamiliarPEP>
         </xsl:if>
         <xsl:if test="/ns0:validarRiesgoCliente/codigoProducto">
            <tns:IdProducto>
               <xsl:value-of select="/ns0:validarRiesgoCliente/codigoProducto"/>
            </tns:IdProducto>
         </xsl:if>
         <xsl:if test="/ns0:validarRiesgoCliente/primaAnual">
            <tns:PrimaAnual>
               <xsl:value-of select="/ns0:validarRiesgoCliente/primaAnual"/>
            </tns:PrimaAnual>
         </xsl:if>
         <xsl:if test="/ns0:validarRiesgoCliente/formaPago">
            <tns:FormaPago>
               <xsl:value-of select="/ns0:validarRiesgoCliente/formaPago"/>
            </tns:FormaPago>
         </xsl:if>
         <xsl:if test="/ns0:validarRiesgoCliente/ingresosAnuales">
            <tns:IngresoAnual>
               <xsl:value-of select="/ns0:validarRiesgoCliente/ingresosAnuales"/>
            </tns:IngresoAnual>
         </xsl:if>
         <xsl:if test="/ns0:validarRiesgoCliente/canal">
            <tns:Canales>
                <xsl:value-of select="/ns0:validarRiesgoCliente/canal"/>
            </tns:Canales>
         </xsl:if>
         
      </tns:ValidarRiesgoClienteMsjSol>
   </xsl:template>
</xsl:stylesheet>