<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CajaUnica/Dat_ConsultarPolizaPremium/ConsultarPoliza" name="ConsultarPoliza-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="ConsultarPoliza.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/CajaUnica/Dat_ConsultarPolizaPremium/ConsultarPoliza"/>
    <wsdl:binding name="ConsultarPoliza_ptt-binding" type="con:ConsultarPoliza_ptt" xmlns:con="http://xmlns.oracle.com/pcbpel/adapter/db/CajaUnica/Dat_ConsultarPolizaPremium/ConsultarPoliza">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="ConsultarPoliza">
            <soap:operation soapAction="ConsultarPoliza"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>