<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:tns="http://www.sura.com/MensajeIntegracion/DominioPoliza/PolizaMIN/V1" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:ns0="http://sura.com.pa/integrationCCM/" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:dutidoc="http://xmlns.sura.com/ObjetoIntegracion/DominioUtilitario/GestionDocumental/V1"
                xmlns:dcomcom="http://xmlns.sura.com/ObjetoEmpresarial/DominioComun/Comun/V1">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../../../ComponentesComunes/WSDL_Externos/integrationCCM.wsdl"/>
            <oracle-xsl-mapper:rootElement name="generarDocumento" namespace="http://sura.com.pa/integrationCCM/"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../../../ComponentesComunes/WSDL/xsd/DominioPoliza/Poliza/V1/PolizaMINV1.xsd"/>
            <oracle-xsl-mapper:rootElement name="GenerarImprimibleMsjSol" namespace="http://www.sura.com/MensajeIntegracion/DominioPoliza/PolizaMIN/V1"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [MON JUN 29 20:04:19 COT 2020].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="idTransaccionOsb"/>
   <xsl:param name="codigoOperacion"/>
   <xsl:param name="fechaProcesamiento"/>
   <xsl:template match="/">
      <tns:GenerarImprimibleMsjSol>
         <tns:CabeceraSol>
            <dcomcom:CodigoOperacion>
               <xsl:value-of select="$codigoOperacion"/>
            </dcomcom:CodigoOperacion>
            <dcomcom:FechaProcesamiento>
               <xsl:value-of select="$fechaProcesamiento"/>
            </dcomcom:FechaProcesamiento>
            <dcomcom:FechaTransaccion>
               <xsl:value-of select="$fechaProcesamiento"/>
            </dcomcom:FechaTransaccion>
            <dcomcom:IdTransaccionOsb>
               <xsl:value-of select="$idTransaccionOsb"/>
            </dcomcom:IdTransaccionOsb>
            <dcomcom:SistemaDestino><xsl:value-of select="/ns0:generarDocumento/listParamAdditional/SistemaDestino"/></dcomcom:SistemaDestino>
            <dcomcom:SistemaOrigen>CCM</dcomcom:SistemaOrigen>
         </tns:CabeceraSol>
         <tns:CodigoPrintOut>
            <xsl:value-of select="/ns0:generarDocumento/codePO"/>
         </tns:CodigoPrintOut>
         <tns:CodigoOperacion>
            <xsl:value-of select="/ns0:generarDocumento/codeOper"/>
         </tns:CodigoOperacion>
         <tns:TipoEjecucion>
            <xsl:value-of select="/ns0:generarDocumento/tipoExec"/>
         </tns:TipoEjecucion>
         <xsl:if test="/ns0:generarDocumento/listEmail/FROM">
            <tns:EmailsFrom>
               <xsl:value-of select="/ns0:generarDocumento/listEmail/FROM"/>
            </tns:EmailsFrom>
         </xsl:if>
         <xsl:if test="/ns0:generarDocumento/listEmail/TO">
            <tns:EmailsTo>
               <xsl:value-of select="/ns0:generarDocumento/listEmail/TO"/>
            </tns:EmailsTo>
         </xsl:if>
         <xsl:if test="/ns0:generarDocumento/idDocINSIS">
            <tns:IdDocInsis>
               <xsl:value-of select="/ns0:generarDocumento/idDocINSIS"/>
            </tns:IdDocInsis>
         </xsl:if>
<tns:InfoImprimible>
         <xsl:for-each select="/ns0:generarDocumento/listParam">
               <xsl:if test="Key = &quot;policy_id&quot;">
                  <tns:NumeroPoliza>
                     <xsl:value-of select="Value"/>
                  </tns:NumeroPoliza>
               </xsl:if>
               <xsl:if test="Key = &quot;client_id&quot;">
                  <tns:CodigoCliente>
                     <xsl:value-of select="Value"/>
                  </tns:CodigoCliente>
               </xsl:if>
               <xsl:if test="Key = &quot;annex_id&quot;">
                  <tns:NumeroEndoso>
                     <xsl:value-of select="Value"/>
                  </tns:NumeroEndoso>
               </xsl:if>
                <xsl:if test="Key = &quot;man_id&quot;">
                  <tns:IdPersona>
                     <xsl:value-of select="Value"/>
                  </tns:IdPersona>
               </xsl:if>
                <xsl:if test="Key = &quot;agent_id&quot;">
                  <tns:CodigoAgente>
                     <xsl:value-of select="Value"/>
                  </tns:CodigoAgente>
               </xsl:if>
                <xsl:if test="Key = &quot;NumCession&quot;">
                  <tns:NumeroSesion>
                     <xsl:value-of select="Value"/>
                  </tns:NumeroSesion>
               </xsl:if>
                <xsl:if test="Key = &quot;sec_id&quot;">
                  <tns:SecuencialPoliza>
                     <xsl:value-of select="Value"/>
                  </tns:SecuencialPoliza>
               </xsl:if>
               <xsl:if test="Key = &quot;claim_id&quot;">
                  <tns:NumeroReclamo>
                     <xsl:value-of select="Value"/>
                  </tns:NumeroReclamo>
               </xsl:if>
            </xsl:for-each>
         </tns:InfoImprimible>
         <tns:InfoImprimibleCustom>
            <xsl:if test="/ns0:generarDocumento/listParamAdditional/Format">
               <tns:Formato>
                  <xsl:value-of select="/ns0:generarDocumento/listParamAdditional/Format"/>
               </tns:Formato>
            </xsl:if>
            <xsl:if test="/ns0:generarDocumento/listParamAdditional/Country">
               <tns:Pais>
                  <xsl:value-of select="/ns0:generarDocumento/listParamAdditional/Country"/>
               </tns:Pais>
            </xsl:if>
            <xsl:if test="/ns0:generarDocumento/listParamAdditional/Process">
               <tns:Proceso>
                  <xsl:value-of select="/ns0:generarDocumento/listParamAdditional/Process"/>
               </tns:Proceso>
            </xsl:if>
            <xsl:if test="/ns0:generarDocumento/listParamAdditional/Business">
               <tns:Negocio>
                  <xsl:value-of select="/ns0:generarDocumento/listParamAdditional/Business"/>
               </tns:Negocio>
            </xsl:if>
            <xsl:if test="/ns0:generarDocumento/listParamAdditional/CorrelationID">
               <tns:IdCorrelacion>
                  <xsl:value-of select="/ns0:generarDocumento/listParamAdditional/CorrelationID"/>
               </tns:IdCorrelacion>
            </xsl:if>
            <xsl:if test="/ns0:generarDocumento/listParamAdditional/Content">
               <tns:Contenido>
                  <xsl:value-of select="/ns0:generarDocumento/listParamAdditional/Content"/>
               </tns:Contenido>
            </xsl:if>
            <xsl:if test="/ns0:generarDocumento/listParamAdditional/SistemaOrigen">
               <tns:OrigenSolicitud>
                  <xsl:value-of select="/ns0:generarDocumento/listParamAdditional/SistemaOrigen"/>
               </tns:OrigenSolicitud>
            </xsl:if>
         </tns:InfoImprimibleCustom>
      </tns:GenerarImprimibleMsjSol>
   </xsl:template>
</xsl:stylesheet>
