<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ServiciosIntegracionSURA/Bss_GenerarImprimible_V2/dbLoadDataXML" name="dbLoadDataXML-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="dbLoadDataXML.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ServiciosIntegracionSURA/Bss_GenerarImprimible_V2/dbLoadDataXML"/>
    <wsdl:binding name="dbLoadDataXML_ptt-binding" type="dbl:dbLoadDataXML_ptt" xmlns:dbl="http://xmlns.oracle.com/pcbpel/adapter/db/ServiciosIntegracionSURA/Bss_GenerarImprimible_V2/dbLoadDataXML">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="dbLoadDataXML">
            <soap:operation soapAction="dbLoadDataXML"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>