<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:ns0="http://www.sura.com/GestionarCliente" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction"
                xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../../../ComponentesComunes/XSD_Externos/BssGestionarPersona.xsd"/>
            <oracle-xsl-mapper:rootElement name="OBJETO_PERSONA" namespace="http://www.sura.com/GestionarCliente"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../../../ComponentesComunes/XSD_Externos/GestionarCliente.xsd"/>
            <oracle-xsl-mapper:rootElement name="OBJETO_CLIENTE" namespace="http://www.sura.com/GestionarCliente"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [MON AUG 24 16:52:49 COT 2020].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="accion"/>
   <xsl:template match="/">
      <ns0:OBJETO_CLIENTE>
         <ns0:CABECERA>
            <ns0:FECHA_TRANSACCION>
               <xsl:value-of select="/ns0:OBJETO_PERSONA/ns0:CABECERA/ns0:FECHA_TRANSACCION"/>
            </ns0:FECHA_TRANSACCION>
            <ns0:FECHA_PROCESAMIENTO>
               <xsl:value-of select="/ns0:OBJETO_PERSONA/ns0:CABECERA/ns0:FECHA_PROCESAMIENTO"/>
            </ns0:FECHA_PROCESAMIENTO>
            <ns0:SISTEMA_DESTINO>
               <xsl:value-of select="/ns0:OBJETO_PERSONA/ns0:CABECERA/ns0:SISTEMA_DESTINO"/>
            </ns0:SISTEMA_DESTINO>
            <ns0:SISTEMA_ORIGEN>
               <xsl:value-of select="/ns0:OBJETO_PERSONA/ns0:CABECERA/ns0:SISTEMA_ORIGEN"/>
            </ns0:SISTEMA_ORIGEN>
            <ns0:CODIGO_OPERACION>
               <xsl:value-of select="/ns0:OBJETO_PERSONA/ns0:CABECERA/ns0:CODIGO_OPERACION"/>
            </ns0:CODIGO_OPERACION>
         </ns0:CABECERA>
         <ns0:ACCION>
            <xsl:value-of select="$accion"/>
         </ns0:ACCION>
         <xsl:choose>
            <xsl:when test="$accion = &quot;I&quot;">
               <ns0:PERSONA_ASEGURADA>
                  <xsl:if test="/ns0:OBJETO_PERSONA/ns0:PERSONA/ns0:SEGUNDO_NOMBRE">
                     <ns0:SEGUNDO_NOMBRE>
                        <xsl:value-of select="/ns0:OBJETO_PERSONA/ns0:PERSONA/ns0:SEGUNDO_NOMBRE"/>
                     </ns0:SEGUNDO_NOMBRE>
                  </xsl:if>
                  <xsl:if test="/ns0:OBJETO_PERSONA/ns0:PERSONA/ns0:INFO_ACTIVIDAD_ECONOMICA">
                     <ns0:INFO_ACTIVIDAD_ECONOMICA>
                        <xsl:if test="/ns0:OBJETO_PERSONA/ns0:PERSONA/ns0:INFO_ACTIVIDAD_ECONOMICA/ns0:FECHA_FIN_PEP">
                           <ns0:FECHA_FIN_PEP>
                              <xsl:value-of select="/ns0:OBJETO_PERSONA/ns0:PERSONA/ns0:INFO_ACTIVIDAD_ECONOMICA/ns0:FECHA_FIN_PEP"/>
                           </ns0:FECHA_FIN_PEP>
                        </xsl:if>
                        <xsl:if test="/ns0:OBJETO_PERSONA/ns0:PERSONA/ns0:INFO_ACTIVIDAD_ECONOMICA/ns0:CODIGO_INGRESO_ANUAL">
                           <ns0:CODIGO_INGRESO_ANUAL>
                              <xsl:value-of select="/ns0:OBJETO_PERSONA/ns0:PERSONA/ns0:INFO_ACTIVIDAD_ECONOMICA/ns0:CODIGO_INGRESO_ANUAL"/>
                           </ns0:CODIGO_INGRESO_ANUAL>
                        </xsl:if>
                        <xsl:if test="/ns0:OBJETO_PERSONA/ns0:PERSONA/ns0:INFO_ACTIVIDAD_ECONOMICA/ns0:CARGO_PUBLICO">
                           <ns0:CARGO_PUBLICO>
                              <xsl:value-of select="/ns0:OBJETO_PERSONA/ns0:PERSONA/ns0:INFO_ACTIVIDAD_ECONOMICA/ns0:CARGO_PUBLICO"/>
                           </ns0:CARGO_PUBLICO>
                        </xsl:if>
                        <xsl:if test="/ns0:OBJETO_PERSONA/ns0:PERSONA/ns0:INFO_ACTIVIDAD_ECONOMICA/ns0:ACTIVIDAD">
                           <ns0:ACTIVIDAD>
                              <xsl:value-of select="/ns0:OBJETO_PERSONA/ns0:PERSONA/ns0:INFO_ACTIVIDAD_ECONOMICA/ns0:ACTIVIDAD"/>
                           </ns0:ACTIVIDAD>
                        </xsl:if>
                        <xsl:if test="/ns0:OBJETO_PERSONA/ns0:PERSONA/ns0:INFO_ACTIVIDAD_ECONOMICA/ns0:PEP_ACTUAL">
                           <ns0:PEP_ACTUAL>
                              <xsl:value-of select="/ns0:OBJETO_PERSONA/ns0:PERSONA/ns0:INFO_ACTIVIDAD_ECONOMICA/ns0:PEP_ACTUAL"/>
                           </ns0:PEP_ACTUAL>
                        </xsl:if>
                        <xsl:if test="/ns0:OBJETO_PERSONA/ns0:PERSONA/ns0:INFO_ACTIVIDAD_ECONOMICA/ns0:COD_OTRO_INGRESO">
                           <ns0:COD_OTRO_INGRESO>
                              <xsl:value-of select="/ns0:OBJETO_PERSONA/ns0:PERSONA/ns0:INFO_ACTIVIDAD_ECONOMICA/ns0:COD_OTRO_INGRESO"/>
                           </ns0:COD_OTRO_INGRESO>
                        </xsl:if>
                        <xsl:if test="/ns0:OBJETO_PERSONA/ns0:PERSONA/ns0:INFO_ACTIVIDAD_ECONOMICA/ns0:COD_PAIS_RESIDENCIA_FISCAL">
                           <ns0:COD_PAIS_RESIDENCIA_FISCAL>
                              <xsl:value-of select="/ns0:OBJETO_PERSONA/ns0:PERSONA/ns0:INFO_ACTIVIDAD_ECONOMICA/ns0:COD_PAIS_RESIDENCIA_FISCAL"/>
                           </ns0:COD_PAIS_RESIDENCIA_FISCAL>
                        </xsl:if>
                        <xsl:if test="/ns0:OBJETO_PERSONA/ns0:PERSONA/ns0:INFO_ACTIVIDAD_ECONOMICA/ns0:FECHA_INICIO_PEP">
                           <ns0:FECHA_INICIO_PEP>
                              <xsl:value-of select="/ns0:OBJETO_PERSONA/ns0:PERSONA/ns0:INFO_ACTIVIDAD_ECONOMICA/ns0:FECHA_INICIO_PEP"/>
                           </ns0:FECHA_INICIO_PEP>
                        </xsl:if>
                        <xsl:if test="/ns0:OBJETO_PERSONA/ns0:PERSONA/ns0:INFO_ACTIVIDAD_ECONOMICA/ns0:ACTIVIDAD_ECONOMICA">
                           <ns0:ACTIVIDAD_ECONOMICA>
                              <xsl:value-of select="/ns0:OBJETO_PERSONA/ns0:PERSONA/ns0:INFO_ACTIVIDAD_ECONOMICA/ns0:ACTIVIDAD_ECONOMICA"/>
                           </ns0:ACTIVIDAD_ECONOMICA>
                        </xsl:if>
                        <xsl:if test="/ns0:OBJETO_PERSONA/ns0:PERSONA/ns0:INFO_ACTIVIDAD_ECONOMICA/ns0:CARGO_OCUPADO">
                           <ns0:CARGO_OCUPADO>
                              <xsl:value-of select="/ns0:OBJETO_PERSONA/ns0:PERSONA/ns0:INFO_ACTIVIDAD_ECONOMICA/ns0:CARGO_OCUPADO"/>
                           </ns0:CARGO_OCUPADO>
                        </xsl:if>
                     </ns0:INFO_ACTIVIDAD_ECONOMICA>
                  </xsl:if>
                  <xsl:if test="/ns0:OBJETO_PERSONA/ns0:PERSONA/ns0:APELLIDO">
                     <ns0:APELLIDO>
                        <xsl:value-of select="/ns0:OBJETO_PERSONA/ns0:PERSONA/ns0:APELLIDO"/>
                     </ns0:APELLIDO>
                  </xsl:if>
                  <xsl:if test="/ns0:OBJETO_PERSONA/ns0:PERSONA/ns0:DIRECCIONES">
                     <xsl:for-each select="/ns0:OBJETO_PERSONA/ns0:PERSONA/ns0:DIRECCIONES">
                        <ns0:DIRECCIONES>
                           <xsl:if test="ns0:DIRECCION">
                              <ns0:DIRECCION>
                                 <xsl:value-of select="ns0:DIRECCION"/>
                              </ns0:DIRECCION>
                           </xsl:if>
                           <xsl:if test="ns0:COD_PAIS">
                              <ns0:COD_PAIS>
                                 <xsl:value-of select="ns0:COD_PAIS"/>
                              </ns0:COD_PAIS>
                           </xsl:if>
                           <xsl:if test="ns0:COD_DISTRITO">
                              <ns0:COD_DISTRITO>
                                 <xsl:value-of select="ns0:COD_DISTRITO"/>
                              </ns0:COD_DISTRITO>
                           </xsl:if>
                           <xsl:if test="ns0:CALLE">
                              <ns0:CALLE>
                                 <xsl:value-of select="ns0:CALLE"/>
                              </ns0:CALLE>
                           </xsl:if>
                           <xsl:if test="ns0:EXTENSION">
                              <ns0:EXTENSION>
                                 <xsl:value-of select="ns0:EXTENSION"/>
                              </ns0:EXTENSION>
                           </xsl:if>
                           <xsl:if test="ns0:EMAIL">
                              <ns0:EMAIL>
                                 <xsl:value-of select="ns0:EMAIL"/>
                              </ns0:EMAIL>
                           </xsl:if>
                           <xsl:if test="ns0:COD_PROVINCIA">
                              <ns0:COD_PROVINCIA>
                                 <xsl:value-of select="ns0:COD_PROVINCIA"/>
                              </ns0:COD_PROVINCIA>
                           </xsl:if>
                           <xsl:if test="ns0:TIPO">
                              <ns0:TIPO>
                                 <xsl:value-of select="ns0:TIPO"/>
                              </ns0:TIPO>
                           </xsl:if>
                           <xsl:if test="ns0:CASA">
                              <ns0:CASA>
                                 <xsl:value-of select="ns0:CASA"/>
                              </ns0:CASA>
                           </xsl:if>
                           <xsl:if test="ns0:URBANIZACION">
                              <ns0:URBANIZACION>
                                 <xsl:value-of select="ns0:URBANIZACION"/>
                              </ns0:URBANIZACION>
                           </xsl:if>
                           <xsl:if test="ns0:TELEFONO">
                              <ns0:TELEFONO>
                                 <xsl:value-of select="ns0:TELEFONO"/>
                              </ns0:TELEFONO>
                           </xsl:if>
                           <xsl:if test="ns0:COD_CORREGIMIENTO">
                              <ns0:COD_CORREGIMIENTO>
                                 <xsl:value-of select="ns0:COD_CORREGIMIENTO"/>
                              </ns0:COD_CORREGIMIENTO>
                           </xsl:if>
                           <xsl:if test="ns0:COD_BARRIO">
                              <ns0:COD_BARRIO>
                                 <xsl:value-of select="ns0:COD_BARRIO"/>
                              </ns0:COD_BARRIO>
                           </xsl:if>
                        </ns0:DIRECCIONES>
                     </xsl:for-each>
                  </xsl:if>
                  <xsl:choose>
                     <xsl:when test="/ns0:OBJETO_PERSONA/ns0:PERSONA/ns0:CELULAR">
                        <xsl:if test="/ns0:OBJETO_PERSONA/ns0:PERSONA/ns0:CELULAR">
                           <ns0:CELULAR>
                              <xsl:value-of select="/ns0:OBJETO_PERSONA/ns0:PERSONA/ns0:CELULAR"/>
                           </ns0:CELULAR>
                        </xsl:if>
                     </xsl:when>
                     <xsl:when test="/ns0:OBJETO_PERSONA/ns0:PERSONA/ns0:TELEFONO">
                        <xsl:if test="/ns0:OBJETO_PERSONA/ns0:PERSONA/ns0:TELEFONO">
                           <ns0:CELULAR>
                              <xsl:value-of select="/ns0:OBJETO_PERSONA/ns0:PERSONA/ns0:TELEFONO"/>
                           </ns0:CELULAR>
                        </xsl:if>
                     </xsl:when>
                  </xsl:choose>
                  <xsl:if test="/ns0:OBJETO_PERSONA/ns0:PERSONA/ns0:SEGUNDO_APELLIDO">
                     <ns0:SEGUNDO_APELLIDO>
                        <xsl:value-of select="/ns0:OBJETO_PERSONA/ns0:PERSONA/ns0:SEGUNDO_APELLIDO"/>
                     </ns0:SEGUNDO_APELLIDO>
                  </xsl:if>
                  <xsl:if test="/ns0:OBJETO_PERSONA/ns0:PERSONA/ns0:NUMERO_IDENTIFICACION">
                     <ns0:NUMERO_IDENTIFICACION>
                        <xsl:value-of select="/ns0:OBJETO_PERSONA/ns0:PERSONA/ns0:NUMERO_IDENTIFICACION"/>
                     </ns0:NUMERO_IDENTIFICACION>
                  </xsl:if>
                  <xsl:if test="/ns0:OBJETO_PERSONA/ns0:PERSONA/ns0:NOMBRE">
                     <ns0:NOMBRE>
                        <xsl:value-of select="/ns0:OBJETO_PERSONA/ns0:PERSONA/ns0:NOMBRE"/>
                     </ns0:NOMBRE>
                  </xsl:if>
                  <xsl:if test="/ns0:OBJETO_PERSONA/ns0:PERSONA/ns0:FECHA_NACIMIENTO">
                     <ns0:FECHA_NACIMIENTO>
                        <xsl:value-of select="/ns0:OBJETO_PERSONA/ns0:PERSONA/ns0:FECHA_NACIMIENTO"/>
                     </ns0:FECHA_NACIMIENTO>
                  </xsl:if>
                  <xsl:if test="/ns0:OBJETO_PERSONA/ns0:PERSONA/ns0:SEXO">
                     <ns0:SEXO>
                        <xsl:value-of select="/ns0:OBJETO_PERSONA/ns0:PERSONA/ns0:SEXO"/>
                     </ns0:SEXO>
                  </xsl:if>
                  <xsl:if test="/ns0:OBJETO_PERSONA/ns0:PERSONA/ns0:ESTADO_CIVIL">
                     <ns0:ESTADO_CIVIL>
                        <xsl:value-of select="/ns0:OBJETO_PERSONA/ns0:PERSONA/ns0:ESTADO_CIVIL"/>
                     </ns0:ESTADO_CIVIL>
                  </xsl:if>
               </ns0:PERSONA_ASEGURADA>
            </xsl:when>
            <xsl:when test="$accion = &quot;A&quot;">
               <ns0:PERSONA_ASEGURADA>
                  <xsl:if test="/ns0:OBJETO_PERSONA/ns0:PERSONA/ns0:DIRECCIONES">
                     <xsl:for-each select="/ns0:OBJETO_PERSONA/ns0:PERSONA/ns0:DIRECCIONES">
                        <ns0:DIRECCIONES>
                           <xsl:if test="ns0:DIRECCION">
                              <ns0:DIRECCION>
                                 <xsl:value-of select="ns0:DIRECCION"/>
                              </ns0:DIRECCION>
                           </xsl:if>
                           <xsl:if test="ns0:COD_PAIS">
                              <ns0:COD_PAIS>
                                 <xsl:value-of select="ns0:COD_PAIS"/>
                              </ns0:COD_PAIS>
                           </xsl:if>
                           <xsl:if test="ns0:COD_DISTRITO">
                              <ns0:COD_DISTRITO>
                                 <xsl:value-of select="ns0:COD_DISTRITO"/>
                              </ns0:COD_DISTRITO>
                           </xsl:if>
                           <xsl:if test="ns0:CALLE">
                              <ns0:CALLE>
                                 <xsl:value-of select="ns0:CALLE"/>
                              </ns0:CALLE>
                           </xsl:if>
                           <xsl:if test="ns0:EXTENSION">
                              <ns0:EXTENSION>
                                 <xsl:value-of select="ns0:EXTENSION"/>
                              </ns0:EXTENSION>
                           </xsl:if>
                           <xsl:if test="ns0:EMAIL">
                              <ns0:EMAIL>
                                 <xsl:value-of select="ns0:EMAIL"/>
                              </ns0:EMAIL>
                           </xsl:if>
                           <xsl:if test="ns0:COD_PROVINCIA">
                              <ns0:COD_PROVINCIA>
                                 <xsl:value-of select="ns0:COD_PROVINCIA"/>
                              </ns0:COD_PROVINCIA>
                           </xsl:if>
                           <xsl:if test="ns0:TIPO">
                              <ns0:TIPO>
                                 <xsl:value-of select="ns0:TIPO"/>
                              </ns0:TIPO>
                           </xsl:if>
                           <xsl:if test="ns0:CASA">
                              <ns0:CASA>
                                 <xsl:value-of select="ns0:CASA"/>
                              </ns0:CASA>
                           </xsl:if>
                           <xsl:if test="ns0:URBANIZACION">
                              <ns0:URBANIZACION>
                                 <xsl:value-of select="ns0:URBANIZACION"/>
                              </ns0:URBANIZACION>
                           </xsl:if>
                           <xsl:if test="ns0:TELEFONO">
                              <ns0:TELEFONO>
                                 <xsl:value-of select="ns0:TELEFONO"/>
                              </ns0:TELEFONO>
                           </xsl:if>
                           <xsl:if test="ns0:COD_CORREGIMIENTO">
                              <ns0:COD_CORREGIMIENTO>
                                 <xsl:value-of select="ns0:COD_CORREGIMIENTO"/>
                              </ns0:COD_CORREGIMIENTO>
                           </xsl:if>
                           <xsl:if test="ns0:COD_BARRIO">
                              <ns0:COD_BARRIO>
                                 <xsl:value-of select="ns0:COD_BARRIO"/>
                              </ns0:COD_BARRIO>
                           </xsl:if>
                        </ns0:DIRECCIONES>
                     </xsl:for-each>
                  </xsl:if>
                  <xsl:choose>
                     <xsl:when test="/ns0:OBJETO_PERSONA/ns0:PERSONA/ns0:TELEFONO">
                        <ns0:CELULAR>
                           <xsl:value-of select="/ns0:OBJETO_PERSONA/ns0:PERSONA/ns0:TELEFONO"/>
                        </ns0:CELULAR>
                     </xsl:when>
                     <xsl:when test="/ns0:OBJETO_PERSONA/ns0:PERSONA/ns0:CELULAR">
                        <ns0:CELULAR>
                           <xsl:value-of select="/ns0:OBJETO_PERSONA/ns0:PERSONA/ns0:CELULAR"/>
                        </ns0:CELULAR>
                     </xsl:when>
                  </xsl:choose>
                  <xsl:if test="/ns0:OBJETO_PERSONA/ns0:PERSONA/ns0:NUMERO_IDENTIFICACION">
                     <ns0:NUMERO_IDENTIFICACION>
                        <xsl:value-of select="/ns0:OBJETO_PERSONA/ns0:PERSONA/ns0:NUMERO_IDENTIFICACION"/>
                     </ns0:NUMERO_IDENTIFICACION>
                  </xsl:if>
               </ns0:PERSONA_ASEGURADA>
            </xsl:when>
         </xsl:choose>
      </ns0:OBJETO_CLIENTE>
   </xsl:template>
</xsl:stylesheet>
