<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CajaUnica/Dat_ConsultarObjetoAsegPremium/ConsultarObjetoAseg" name="ConsultarObjetoAseg-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="ConsultarObjetoAseg.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/CajaUnica/Dat_ConsultarObjetoAsegPremium/ConsultarObjetoAseg"/>
    <wsdl:binding name="ConsultarObjetoAseg_ptt-binding" type="con:ConsultarObjetoAseg_ptt" xmlns:con="http://xmlns.oracle.com/pcbpel/adapter/db/CajaUnica/Dat_ConsultarObjetoAsegPremium/ConsultarObjetoAseg">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="ConsultarObjetoAseg">
            <soap:operation soapAction="ConsultarObjetoAseg"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>