<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:ns0="http://sura.com.pa/GestionarActividadDocumento/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:tns="http://sura.com.pa/CrearActividadGAD/" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../Schemas/GenerarActividadDocumentoRq.xsd"/>
            <oracle-xsl-mapper:rootElement name="GestionarActividadDocumentoReq" namespace="http://sura.com.pa/GestionarActividadDocumento/"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/Exp_CrearActividadGADPS.wsdl"/>
            <oracle-xsl-mapper:rootElement name="CrearActividadGADReq" namespace="http://sura.com.pa/CrearActividadGAD/"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [WED NOV 17 20:41:00 COT 2021].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:CrearActividadGADReq>
         <tns:CABECERA>
            <tns:CODIGO_OPERACION>
               <xsl:value-of select="/ns0:GestionarActividadDocumentoReq/ns0:CABECERA/ns0:CODIGO_OPERACION"/>
            </tns:CODIGO_OPERACION>
            <tns:FECHA_PROCESAMIENTO>
               <xsl:value-of select="/ns0:GestionarActividadDocumentoReq/ns0:CABECERA/ns0:FECHA_PROCESAMIENTO"/>
            </tns:FECHA_PROCESAMIENTO>
            <tns:FECHA_TRANSACCION>
               <xsl:value-of select="/ns0:GestionarActividadDocumentoReq/ns0:CABECERA/ns0:FECHA_TRANSACCION"/>
            </tns:FECHA_TRANSACCION>
            <tns:ID_TRANSACCION_OSB>
               <xsl:value-of select="/ns0:GestionarActividadDocumentoReq/ns0:CABECERA/ns0:ID_TRANSACCION_OSB"/>
            </tns:ID_TRANSACCION_OSB>
            <tns:SISTEMA_DESTINO>
               <xsl:value-of select="/ns0:GestionarActividadDocumentoReq/ns0:CABECERA/ns0:SISTEMA_DESTINO"/>
            </tns:SISTEMA_DESTINO>
            <tns:SISTEMA_ORIGEN>
               <xsl:value-of select="/ns0:GestionarActividadDocumentoReq/ns0:CABECERA/ns0:SISTEMA_ORIGEN"/>
            </tns:SISTEMA_ORIGEN>
         </tns:CABECERA>
         <tns:TipoReferencia>
            <xsl:value-of select="/ns0:GestionarActividadDocumentoReq/ns0:TipoReferencia"/>
         </tns:TipoReferencia>
         <tns:IdProceso>
            <xsl:value-of select="/ns0:GestionarActividadDocumentoReq/ns0:IdProceso"/>
         </tns:IdProceso>
         <tns:IdPlantillaActividad>
            <xsl:value-of select="/ns0:GestionarActividadDocumentoReq/ns0:IdPlantillaActividad"/>
         </tns:IdPlantillaActividad>
         <tns:IdUsuario>
            <xsl:value-of select="/ns0:GestionarActividadDocumentoReq/ns0:IdUsuario"/>
         </tns:IdUsuario>
         <tns:ParametrosActividad>
            <xsl:for-each select="/ns0:GestionarActividadDocumentoReq/ns0:ParametrosActividad/ns0:Parametro">
               <tns:Parametro>
                  <tns:Nombre>
                     <xsl:value-of select="ns0:Nombre"/>
                  </tns:Nombre>
                  <tns:Valor>
                     <xsl:value-of select="ns0:Valor"/>
                  </tns:Valor>
               </tns:Parametro>
            </xsl:for-each>
         </tns:ParametrosActividad>
      </tns:CrearActividadGADReq>
   </xsl:template>
</xsl:stylesheet>
