<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:ns0="http://xmlns.sura.com/MensajeIntegracion/DominioUtilitario/GestionDocumentalMI/V1" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction"
                xmlns:dpropro="http://xmlns.sura.com/ObjetoIntegracion/DominioProceso/Proceso/V1"
                xmlns:dutigdoc="http://xmlns.sura.com/ObjetoIntegracion/DominioUtilitario/GestionDocumental/V1"
                xmlns:dcomcom="http://xmlns.sura.com/ObjetoEmpresarial/DominioComun/Comun/V1">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../../../ComponentesComunes/WSDL/xsd/DominioUtilitario/GestionDocumental/V1/GestionDocumentalMIV1.xsd"/>
            <oracle-xsl-mapper:rootElement name="CargarDocumentoMsjSol" namespace="http://xmlns.sura.com/MensajeIntegracion/DominioUtilitario/GestionDocumentalMI/V1"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../../../ComponentesComunes/WSDL/xsd/DominioUtilitario/GestionDocumental/V1/GestionDocumentalMIV1.xsd"/>
            <oracle-xsl-mapper:rootElement name="GestionarParametrosECMInsisMsjSol" namespace="http://xmlns.sura.com/MensajeIntegracion/DominioUtilitario/GestionDocumentalMI/V1"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [MON MAY 04 11:12:07 COT 2020].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <ns0:GestionarParametrosECMInsisMsjSol>
         <xsl:if test="/ns0:CargarDocumentoMsjSol/ns0:CabeceraSol">
            <ns0:CabeceraSol>
               <dcomcom:CodigoOperacion>
                  <xsl:value-of select="/ns0:CargarDocumentoMsjSol/ns0:CabeceraSol/dcomcom:CodigoOperacion"/>
               </dcomcom:CodigoOperacion>
               <dcomcom:FechaProcesamiento>
                  <xsl:value-of select="/ns0:CargarDocumentoMsjSol/ns0:CabeceraSol/dcomcom:FechaProcesamiento"/>
               </dcomcom:FechaProcesamiento>
               <dcomcom:FechaTransaccion>
                  <xsl:value-of select="/ns0:CargarDocumentoMsjSol/ns0:CabeceraSol/dcomcom:FechaTransaccion"/>
               </dcomcom:FechaTransaccion>
               <dcomcom:IdTransaccionOsb>
                  <xsl:value-of select="/ns0:CargarDocumentoMsjSol/ns0:CabeceraSol/dcomcom:IdTransaccionOsb"/>
               </dcomcom:IdTransaccionOsb>
               <dcomcom:SistemaDestino>
                  <xsl:value-of select="/ns0:CargarDocumentoMsjSol/ns0:CabeceraSol/dcomcom:SistemaDestino"/>
               </dcomcom:SistemaDestino>
               <dcomcom:SistemaOrigen>
                  <xsl:value-of select="/ns0:CargarDocumentoMsjSol/ns0:CabeceraSol/dcomcom:SistemaOrigen"/>
               </dcomcom:SistemaOrigen>
            </ns0:CabeceraSol>
         </xsl:if>
         <ns0:IdentificacionPersona>
            <xsl:value-of select="/ns0:CargarDocumentoMsjSol/ns0:IdentificacionPersona"/>
         </ns0:IdentificacionPersona>
         <ns0:IdUsuario>
            <xsl:value-of select="/ns0:CargarDocumentoMsjSol/ns0:IdUsuario"/>
         </ns0:IdUsuario>
         <xsl:if test="/ns0:CargarDocumentoMsjSol/ns0:Documento">
            <ns0:Documento>
               <xsl:if test="/ns0:CargarDocumentoMsjSol/ns0:Documento/dutigdoc:IdDocumentoECM">
                  <dutigdoc:IdDocumentoECM>
                     <xsl:value-of select="/ns0:CargarDocumentoMsjSol/ns0:Documento/dutigdoc:IdDocumentoECM"/>
                  </dutigdoc:IdDocumentoECM>
               </xsl:if>
               <xsl:if test="/ns0:CargarDocumentoMsjSol/ns0:Documento/dutigdoc:IdDocumentoINSIS">
                  <dutigdoc:IdDocumentoINSIS>
                     <xsl:value-of select="/ns0:CargarDocumentoMsjSol/ns0:Documento/dutigdoc:IdDocumentoINSIS"/>
                  </dutigdoc:IdDocumentoINSIS>
               </xsl:if>
               <xsl:if test="/ns0:CargarDocumentoMsjSol/ns0:Documento/dutigdoc:Nombre">
                  <dutigdoc:Nombre>
                     <xsl:value-of select="/ns0:CargarDocumentoMsjSol/ns0:Documento/dutigdoc:Nombre"/>
                  </dutigdoc:Nombre>
               </xsl:if>
               <xsl:if test="/ns0:CargarDocumentoMsjSol/ns0:Documento/dutigdoc:TipoDocumento">
                  <dutigdoc:TipoDocumento>
                     <dcomcom:Codigo>
                        <xsl:value-of select="/ns0:CargarDocumentoMsjSol/ns0:Documento/dutigdoc:TipoDocumento/dcomcom:Codigo"/>
                     </dcomcom:Codigo>
                     <xsl:if test="/ns0:CargarDocumentoMsjSol/ns0:Documento/dutigdoc:TipoDocumento/dcomcom:Descripcion">
                        <dcomcom:Descripcion>
                           <xsl:value-of select="/ns0:CargarDocumentoMsjSol/ns0:Documento/dutigdoc:TipoDocumento/dcomcom:Descripcion"/>
                        </dcomcom:Descripcion>
                     </xsl:if>
                  </dutigdoc:TipoDocumento>
               </xsl:if>
               <xsl:if test="/ns0:CargarDocumentoMsjSol/ns0:Documento/dutigdoc:Extension">
                  <dutigdoc:Extension>
                     <xsl:value-of select="/ns0:CargarDocumentoMsjSol/ns0:Documento/dutigdoc:Extension"/>
                  </dutigdoc:Extension>
               </xsl:if>
               <xsl:if test="/ns0:CargarDocumentoMsjSol/ns0:Documento/dutigdoc:IdUltimaRevision">
                  <dutigdoc:IdUltimaRevision>
                     <xsl:value-of select="/ns0:CargarDocumentoMsjSol/ns0:Documento/dutigdoc:IdUltimaRevision"/>
                  </dutigdoc:IdUltimaRevision>
               </xsl:if>
               <xsl:if test="/ns0:CargarDocumentoMsjSol/ns0:Documento/dutigdoc:Comentario">
                  <dutigdoc:Comentario>
                     <xsl:value-of select="/ns0:CargarDocumentoMsjSol/ns0:Documento/dutigdoc:Comentario"/>
                  </dutigdoc:Comentario>
               </xsl:if>
               <xsl:if test="/ns0:CargarDocumentoMsjSol/ns0:Documento/dutigdoc:FechaCreacion">
                  <dutigdoc:FechaCreacion>
                     <xsl:value-of select="/ns0:CargarDocumentoMsjSol/ns0:Documento/dutigdoc:FechaCreacion"/>
                  </dutigdoc:FechaCreacion>
               </xsl:if>
               <xsl:if test="/ns0:CargarDocumentoMsjSol/ns0:Documento/dutigdoc:UrlPathINSIS">
                  <dutigdoc:UrlPathINSIS>
                     <xsl:value-of select="/ns0:CargarDocumentoMsjSol/ns0:Documento/dutigdoc:UrlPathINSIS"/>
                  </dutigdoc:UrlPathINSIS>
               </xsl:if>
               <xsl:if test="/ns0:CargarDocumentoMsjSol/ns0:Documento/dutigdoc:UrlPathTempINSIS">
                  <dutigdoc:UrlPathTempINSIS>
                     <xsl:value-of select="/ns0:CargarDocumentoMsjSol/ns0:Documento/dutigdoc:UrlPathTempINSIS"/>
                  </dutigdoc:UrlPathTempINSIS>
               </xsl:if>
               <xsl:if test="/ns0:CargarDocumentoMsjSol/ns0:Documento/dutigdoc:EstadoDocumento">
                  <dutigdoc:EstadoDocumento>
                     <xsl:value-of select="/ns0:CargarDocumentoMsjSol/ns0:Documento/dutigdoc:EstadoDocumento"/>
                  </dutigdoc:EstadoDocumento>
               </xsl:if>
               <xsl:if test="/ns0:CargarDocumentoMsjSol/ns0:Documento/dutigdoc:NumeroPaginas">
                  <dutigdoc:NumeroPaginas>
                     <xsl:value-of select="/ns0:CargarDocumentoMsjSol/ns0:Documento/dutigdoc:NumeroPaginas"/>
                  </dutigdoc:NumeroPaginas>
               </xsl:if>
               <xsl:if test="/ns0:CargarDocumentoMsjSol/ns0:Documento/dutigdoc:Paginas">
                  <dutigdoc:Paginas>
                     <xsl:for-each select="/ns0:CargarDocumentoMsjSol/ns0:Documento/dutigdoc:Paginas/dutigdoc:Pagina">
                        <dutigdoc:Pagina>
                           <xsl:if test="dutigdoc:Contenido">
                              <dutigdoc:Contenido>
                                 <xsl:value-of select="dutigdoc:Contenido"/>
                              </dutigdoc:Contenido>
                           </xsl:if>
                           <xsl:if test="dutigdoc:IdFormato">
                              <dutigdoc:IdFormato>
                                 <xsl:value-of select="dutigdoc:IdFormato"/>
                              </dutigdoc:IdFormato>
                           </xsl:if>
                        </dutigdoc:Pagina>
                     </xsl:for-each>
                  </dutigdoc:Paginas>
               </xsl:if>
            </ns0:Documento>
         </xsl:if>
         <ns0:TipoOperacion>
            <xsl:value-of select="/ns0:CargarDocumentoMsjSol/ns0:TipoOperacion"/>
         </ns0:TipoOperacion>
      </ns0:GestionarParametrosECMInsisMsjSol>
   </xsl:template>
</xsl:stylesheet>
