<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:ns0="http://xmlns.sura.com/MensajeIntegracion/DominioUtilitario/GestionDocumentalMI/V1" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction"
                xmlns:dpropro="http://xmlns.sura.com/ObjetoIntegracion/DominioProceso/Proceso/V1"
                xmlns:dutigdoc="http://xmlns.sura.com/ObjetoIntegracion/DominioUtilitario/GestionDocumental/V1"
                xmlns:dcomcom="http://xmlns.sura.com/ObjetoEmpresarial/DominioComun/Comun/V1">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../../../ComponentesComunes/WSDL/xsd/DominioUtilitario/GestionDocumental/V1/GestionDocumentalMIV1.xsd"/>
            <oracle-xsl-mapper:rootElement name="GestionarParametrosECMInsisMsjResp" namespace="http://xmlns.sura.com/MensajeIntegracion/DominioUtilitario/GestionDocumentalMI/V1"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../../../ComponentesComunes/WSDL/xsd/DominioUtilitario/GestionDocumental/V1/GestionDocumentalMIV1.xsd"/>
            <oracle-xsl-mapper:rootElement name="CargarDocumentoMsjSol"
                                           namespace="http://xmlns.sura.com/MensajeIntegracion/DominioUtilitario/GestionDocumentalMI/V1"/>
            <oracle-xsl-mapper:param name="CargarDocumentoMsjSol"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../../../ComponentesComunes/WSDL/xsd/DominioUtilitario/GestionDocumental/V1/GestionDocumentalMIV1.xsd"/>
            <oracle-xsl-mapper:rootElement name="AlmacenarDocumentoOnBaseMsjSol" namespace="http://xmlns.sura.com/MensajeIntegracion/DominioUtilitario/GestionDocumentalMI/V1"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [MON MAY 04 12:07:56 COT 2020].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="CargarDocumentoMsjSol"/>
   <xsl:template match="/">
      <ns0:AlmacenarDocumentoOnBaseMsjSol>
         <ns0:CabeceraSol>
            <dcomcom:CodigoOperacion>
               <xsl:value-of select="$CargarDocumentoMsjSol/ns0:CargarDocumentoMsjSol/ns0:CabeceraSol/dcomcom:CodigoOperacion"/>
            </dcomcom:CodigoOperacion>
            <dcomcom:FechaProcesamiento>
               <xsl:value-of select="$CargarDocumentoMsjSol/ns0:CargarDocumentoMsjSol/ns0:CabeceraSol/dcomcom:FechaProcesamiento"/>
            </dcomcom:FechaProcesamiento>
            <dcomcom:FechaTransaccion>
               <xsl:value-of select="$CargarDocumentoMsjSol/ns0:CargarDocumentoMsjSol/ns0:CabeceraSol/dcomcom:FechaTransaccion"/>
            </dcomcom:FechaTransaccion>
            <dcomcom:IdTransaccionOsb>
               <xsl:value-of select="$CargarDocumentoMsjSol/ns0:CargarDocumentoMsjSol/ns0:CabeceraSol/dcomcom:IdTransaccionOsb"/>
            </dcomcom:IdTransaccionOsb>
            <dcomcom:SistemaDestino>
               <xsl:value-of select="$CargarDocumentoMsjSol/ns0:CargarDocumentoMsjSol/ns0:CabeceraSol/dcomcom:SistemaDestino"/>
            </dcomcom:SistemaDestino>
            <dcomcom:SistemaOrigen>
               <xsl:value-of select="$CargarDocumentoMsjSol/ns0:CargarDocumentoMsjSol/ns0:CabeceraSol/dcomcom:SistemaOrigen"/>
            </dcomcom:SistemaOrigen>
         </ns0:CabeceraSol>
         <ns0:IdDocumental>
            <xsl:value-of select="/ns0:GestionarParametrosECMInsisMsjResp/ns0:TipoDocumental"/>
         </ns0:IdDocumental>
         <ns0:Atributos>
            <xsl:for-each select="/ns0:GestionarParametrosECMInsisMsjResp/ns0:Parametros/dutigdoc:Atributo">
               <dutigdoc:Atributo>
                  <xsl:if test="dutigdoc:IdParametro">
                     <dutigdoc:IdParametro>
                        <xsl:value-of select="dutigdoc:IdParametro"/>
                     </dutigdoc:IdParametro>
                  </xsl:if>
                  <xsl:if test="dutigdoc:Nombre">
                     <dutigdoc:Nombre>
                        <xsl:value-of select="dutigdoc:Nombre"/>
                     </dutigdoc:Nombre>
                  </xsl:if>
                  <xsl:if test="dutigdoc:Valor">
                     <dutigdoc:Valor>
                        <xsl:value-of select="dutigdoc:Valor"/>
                     </dutigdoc:Valor>
                  </xsl:if>
               </dutigdoc:Atributo>
            </xsl:for-each>
         </ns0:Atributos>
         <ns0:Paginas>
            <dutigdoc:Pagina>
               <dutigdoc:Contenido>
                  <xsl:value-of select="$CargarDocumentoMsjSol/ns0:CargarDocumentoMsjSol/ns0:Documento/dutigdoc:Paginas/dutigdoc:Pagina/dutigdoc:Contenido"/>
               </dutigdoc:Contenido>
               <dutigdoc:IdFormato>
                  <xsl:value-of select="/ns0:GestionarParametrosECMInsisMsjResp/ns0:IdFormato"/>
               </dutigdoc:IdFormato>
            </dutigdoc:Pagina>
         </ns0:Paginas>
      </ns0:AlmacenarDocumentoOnBaseMsjSol>
   </xsl:template>
</xsl:stylesheet>
