<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ServiciosIntegracionSURA/Dat_EmitirPolizaMPH/EmitirPolizaMPH" name="EmitirPolizaMPH-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="EmitirPolizaMPH.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ServiciosIntegracionSURA/Dat_EmitirPolizaMPH/EmitirPolizaMPH"/>
    <wsdl:binding name="EmitirPolizaMPH_ptt-binding" type="emit:EmitirPolizaMPH_ptt" xmlns:emit="http://xmlns.oracle.com/pcbpel/adapter/db/ServiciosIntegracionSURA/Dat_EmitirPolizaMPH/EmitirPolizaMPH">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="EmitirPolizaMPH">
            <soap:operation soapAction="EmitirPolizaMPH"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>