<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:tns="http://TargetNamespace.com/crearDetallePC" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction"
                xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source/>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../XSD/crearDetallePC.xsd"/>
            <oracle-xsl-mapper:rootElement name="RqCrearDetallePC" namespace="http://TargetNamespace.com/crearDetallePC"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [TUE JUL 27 18:18:07 COT 2021].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="ramo"/>
   <xsl:param name="subRamo"/>
   <xsl:param name="poliza"/>
   <xsl:param name="secuencia"/>
   <xsl:param name="numeroReferencia"/>
   <xsl:param name="fechaReferencia"/>
   <xsl:param name="monto"/>
   <xsl:param name="estadoPago"/>
   <xsl:param name="totalRegistro"/>
   <xsl:param name="observacion"/>
   <xsl:param name="fechaTransaccion"/>
   <xsl:param name="codigoOperacion"/>
   <xsl:param name="idTransaccionOSB"/>
   <xsl:param name="sistemaOrigen"/>
   <xsl:param name="sistemaDestino"/>
   <xsl:template match="/">
      <tns:RqCrearDetallePC>
         <tns:CABECERA>
            <tns:CODIGO_OPERACION>
               <xsl:value-of select="$codigoOperacion"/>
            </tns:CODIGO_OPERACION>
            <tns:FECHA_TRANSACCION>
               <xsl:value-of select="$fechaTransaccion"/>
            </tns:FECHA_TRANSACCION>
            <tns:ID_TRANSACCION_OSB>
               <xsl:value-of select="$idTransaccionOSB"/>
            </tns:ID_TRANSACCION_OSB>
            <tns:SISTEMA_DESTINO>
               <xsl:value-of select="$sistemaDestino"/>
            </tns:SISTEMA_DESTINO>
            <tns:SISTEMA_ORIGEN>
               <xsl:value-of select="$sistemaOrigen"/>
            </tns:SISTEMA_ORIGEN>
         </tns:CABECERA>
         <tns:RAMO>
            <xsl:value-of select="$ramo"/>
         </tns:RAMO>
         <tns:SUBRAMO>
            <xsl:value-of select="$subRamo"/>
         </tns:SUBRAMO>
         <tns:POLIZA>
            <xsl:value-of select="$poliza"/>
         </tns:POLIZA>
         <tns:SECUENCIA>
            <xsl:value-of select="$secuencia"/>
         </tns:SECUENCIA>
         <tns:NUMERO_DE_REFERENCIA>
            <xsl:value-of select="$numeroReferencia"/>
         </tns:NUMERO_DE_REFERENCIA>
         <tns:FECHA_REFERENCIA>
            <xsl:value-of select="$fechaReferencia"/>
         </tns:FECHA_REFERENCIA>
         <tns:FECHA_TRANSAC>
            <xsl:value-of select="$fechaTransaccion"/>
         </tns:FECHA_TRANSAC>
         <tns:MONTO>
            <xsl:value-of select="$monto"/>
         </tns:MONTO>
         <tns:ESTADO_PAGO>
            <xsl:value-of select="$estadoPago"/>
         </tns:ESTADO_PAGO>
         <tns:TOTAL_REGISTRO>
            <xsl:value-of select="$totalRegistro"/>
         </tns:TOTAL_REGISTRO>
         <tns:OBSERVACION>
            <xsl:value-of select="$observacion"/>
         </tns:OBSERVACION>
      </tns:RqCrearDetallePC>
   </xsl:template>
</xsl:stylesheet>
