<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:tns="http://sura.com.pa/expoServiceSOAP/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source/>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDL/crearDetallePC.wsdl"/>
            <oracle-xsl-mapper:rootElement name="crearDetallePCResponse" namespace="http://sura.com.pa/expoServiceSOAP/"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [THU JUL 29 09:44:11 COT 2021].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="codigo"/>
   <xsl:param name="detalle"/>
   <xsl:param name="componente"/>
   <xsl:param name="origen"/>
   <xsl:param name="fechaTransaccion"/>
   <xsl:param name="idTransaccionOSB"/>
   <xsl:param name="sistemaDestino"/>
   <xsl:param name="sistemaOrigen"/>
   <xsl:param name="codigoOperacion"/>
   <xsl:template match="/">
      <tns:crearDetallePCResponse>
         <STATUS>
            <DETALLE>
               <xsl:value-of select="$detalle"/>
            </DETALLE>
            <CODIGO>
               <xsl:value-of select="$codigo"/>
            </CODIGO>
            <COMPONENTE>
               <xsl:value-of select="$componente"/>
            </COMPONENTE>
            <ORIGEN>
               <xsl:value-of select="$origen"/>
            </ORIGEN>
         </STATUS>
         <CABECERA>
            <FECHA_TRANSACCION>
               <xsl:value-of select="$fechaTransaccion"/>
            </FECHA_TRANSACCION>
            <ID_TRANSACCION_OSB>
               <xsl:value-of select="$idTransaccionOSB"/>
            </ID_TRANSACCION_OSB>
            <FECHA_PROCESAMIENTO>
               <xsl:value-of select="$fechaTransaccion"/>
            </FECHA_PROCESAMIENTO>
            <SISTEMA_DESTINO>
               <xsl:value-of select="$sistemaDestino"/>
            </SISTEMA_DESTINO>
            <SISTEMA_ORIGEN>
               <xsl:value-of select="$sistemaOrigen"/>
            </SISTEMA_ORIGEN>
            <CODIGO_OPERACION>
               <xsl:value-of select="$codigoOperacion"/>
            </CODIGO_OPERACION>
         </CABECERA>
      </tns:crearDetallePCResponse>
   </xsl:template>
</xsl:stylesheet>
