<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/sp/sp_actualiza_poliza_integracion" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:ns0="http://www.sura.com.pa/GestionarTransaccionPremium" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction"
                xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../nxsd/RqGestionarTransaccionPremium.xsd"/>
            <oracle-xsl-mapper:rootElement name="OBJETO_TRANSACCION" namespace="http://www.sura.com.pa/GestionarTransaccionPremium"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../Database/sp_actualiza_poliza_integracion_sp.xsd"/>
            <oracle-xsl-mapper:rootElement name="InputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/sp_actualiza_poliza_integracion"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [FRI DEC 04 09:13:00 COT 2020].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="Ramo"/>
   <xsl:param name="SubRamo"/>
   <xsl:param name="Poliza"/>
   <xsl:param name="Secuencia"/>
   <xsl:template match="/">
      <tns:InputParameters>
         <xsl:if test="$Ramo">
            <tns:PV_RAMO>
               <xsl:value-of select="$Ramo"/>
            </tns:PV_RAMO>
         </xsl:if>
         <xsl:if test="$SubRamo">
            <tns:PV_SUB_RAMO>
               <xsl:value-of select="$SubRamo"/>
            </tns:PV_SUB_RAMO>
         </xsl:if>
         <xsl:if test="$Poliza">
            <tns:PN_POLIZA>
               <xsl:value-of select="$Poliza"/>
            </tns:PN_POLIZA>
         </xsl:if>
         <xsl:if test="$Secuencia">
            <tns:PN_SECUENCIA>
               <xsl:value-of select="$Secuencia"/>
            </tns:PN_SECUENCIA>
         </xsl:if>
         <xsl:if test="/ns0:OBJETO_TRANSACCION/ns0:ID != &quot;null&quot;">
            <tns:PN_ID_VOUCHER>
               <xsl:value-of select="/ns0:OBJETO_TRANSACCION/ns0:ID"/>
            </tns:PN_ID_VOUCHER>
         </xsl:if>
         <xsl:if test="/ns0:OBJETO_TRANSACCION/ns0:STATE != &quot;null&quot;" >
            <tns:PN_ESTADO_VOUCHER>
               <xsl:value-of select="/ns0:OBJETO_TRANSACCION/ns0:STATE"/>
            </tns:PN_ESTADO_VOUCHER>
         </xsl:if>
         <xsl:if test="/ns0:OBJETO_TRANSACCION/ns0:OPEN_DATE != &quot;null&quot;">
            <tns:PD_FECHA_DE_APERTURA_VOUCHER>
               <xsl:value-of select="/ns0:OBJETO_TRANSACCION/ns0:OPEN_DATE"/>
            </tns:PD_FECHA_DE_APERTURA_VOUCHER>
         </xsl:if>
         <xsl:if test="/ns0:OBJETO_TRANSACCION/ns0:LAST_MODIFIED != &quot;null&quot;">
            <tns:PD_FECHA_ACTUALIZACION_VOUCHER>
               <xsl:value-of select="/ns0:OBJETO_TRANSACCION/ns0:LAST_MODIFIED"/>
            </tns:PD_FECHA_ACTUALIZACION_VOUCHER>
         </xsl:if>
         <xsl:if test="/ns0:OBJETO_TRANSACCION/ns0:PROCESADO != &quot;null&quot;">
            <tns:PV_INDICADOR_PROCESADO>
               <xsl:value-of select="/ns0:OBJETO_TRANSACCION/ns0:PROCESADO"/>
            </tns:PV_INDICADOR_PROCESADO>
         </xsl:if>
         <xsl:if test="/ns0:OBJETO_TRANSACCION/ns0:REINTENTO != &quot;null&quot;">
            <tns:PN_CANTIDAD_REINTENTOS>
               <xsl:value-of select="/ns0:OBJETO_TRANSACCION/ns0:REINTENTO"/>
            </tns:PN_CANTIDAD_REINTENTOS>
         </xsl:if>
         <xsl:if test="/ns0:OBJETO_TRANSACCION/ns0:UUID">
            <tns:PV_UUID>
               <xsl:value-of select="/ns0:OBJETO_TRANSACCION/ns0:UUID"/>
            </tns:PV_UUID>
         </xsl:if>
         <xsl:if test="/ns0:OBJETO_TRANSACCION/ns0:MENSAJE != &quot;null&quot;">
            <tns:PV_MENSAJE>
               <xsl:value-of select="/ns0:OBJETO_TRANSACCION/ns0:MENSAJE"/>
            </tns:PV_MENSAJE>
         </xsl:if>
      </tns:InputParameters>
   </xsl:template>
</xsl:stylesheet>
