<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ServiciosIntegracionSURA/GestionarCliente/GestionarCliente" name="GestionarCliente-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="GestionarCliente.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ServiciosIntegracionSURA/GestionarCliente/GestionarCliente"/>
    <wsdl:binding name="GestionarCliente_ptt-binding" type="ges:GestionarCliente_ptt" xmlns:ges="http://xmlns.oracle.com/pcbpel/adapter/db/ServiciosIntegracionSURA/GestionarCliente/GestionarCliente">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="GestionarCliente">
            <soap:operation soapAction="GestionarCliente"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>