<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="expoAplicaPagoInsisSOAP"
     targetNamespace="http://sura.com.pa/expoAplicaPagoInsisSOAP/"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:ccm="http://sura.com.pa/expoAplicaPagoInsisSOAP/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="Exp_AplicaPagoInsis">
        <plnk:role name="expoAplicaPagoInsisSOAP" portType="ccm:expoAplicaPagoInsisSOAP"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://sura.com.pa/expoAplicaPagoInsisSOAP/" location="aplicarPagoInsis.wsdl"/>
</wsdl:definitions>
