<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:ns0="http://www.sura.com/EmitirPolizaMPH" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/sp/EmitirPolizaMPH" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction"
                xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd" xmlns:x2r="http://www.oracle.com/odi/xml-mapping">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../xsd/EmitirPolizaMPH.xsd"/>
            <oracle-xsl-mapper:rootElement name="OBJETO_POLIZA" namespace="http://www.sura.com/EmitirPolizaMPH"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../DBadapter/EmitirPolizaMPH_sp.xsd"/>
            <oracle-xsl-mapper:rootElement name="InputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/EmitirPolizaMPH"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [THU AUG 06 16:37:47 COT 2020].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:InputParameters>
         <xsl:if test="/ns0:OBJETO_POLIZA/ns0:POLIZA/ns0:PLAN">
            <tns:P_PLAN>
               <xsl:value-of select="/ns0:OBJETO_POLIZA/ns0:POLIZA/ns0:PLAN"/>
            </tns:P_PLAN>
         </xsl:if>
         <xsl:if test="/ns0:OBJETO_POLIZA/ns0:POLIZA/ns0:NUMERO_POLIZA">
            <tns:P_NUMERO_DE_POLIZA>
               <xsl:value-of select="/ns0:OBJETO_POLIZA/ns0:POLIZA/ns0:NUMERO_POLIZA"/>
            </tns:P_NUMERO_DE_POLIZA>
         </xsl:if>
         <xsl:if test="/ns0:OBJETO_POLIZA/ns0:NUMERO_IDENTIFICACION_ASEGURADO">
            <tns:P_ASEGURADO>
               <xsl:value-of select="/ns0:OBJETO_POLIZA/ns0:NUMERO_IDENTIFICACION_ASEGURADO"/>
            </tns:P_ASEGURADO>
         </xsl:if>
         <xsl:if test="/ns0:OBJETO_POLIZA/ns0:POLIZA/ns0:VIGENCIA_DESDE">
            <tns:P_DESDE>
               <xsl:value-of select="/ns0:OBJETO_POLIZA/ns0:POLIZA/ns0:VIGENCIA_DESDE"/>
            </tns:P_DESDE>
         </xsl:if>
         <xsl:if test="/ns0:OBJETO_POLIZA/ns0:POLIZA/ns0:VIGENCIA_HASTA">
            <tns:P_HASTA>
               <xsl:value-of select="/ns0:OBJETO_POLIZA/ns0:POLIZA/ns0:VIGENCIA_HASTA"/>
            </tns:P_HASTA>
         </xsl:if>
         <xsl:if test="/ns0:OBJETO_POLIZA/ns0:POLIZA/ns0:OBSERVACION">
            <tns:P_OBSERVACION>
               <xsl:value-of select="/ns0:OBJETO_POLIZA/ns0:POLIZA/ns0:OBSERVACION"/>
            </tns:P_OBSERVACION>
         </xsl:if>
         <xsl:if test="/ns0:OBJETO_POLIZA/ns0:VIVIENDA/ns0:DESCRIPCION_UNIDAD">
            <tns:P_DESCRIPCION_UNIDAD>
               <xsl:value-of select="/ns0:OBJETO_POLIZA/ns0:VIVIENDA/ns0:DESCRIPCION_UNIDAD"/>
            </tns:P_DESCRIPCION_UNIDAD>
         </xsl:if>
         <xsl:if test="/ns0:OBJETO_POLIZA/ns0:VIVIENDA/ns0:DURACION">
            <tns:P_DURACION>
               <xsl:value-of select="/ns0:OBJETO_POLIZA/ns0:VIVIENDA/ns0:DURACION"/>
            </tns:P_DURACION>
         </xsl:if>
         <xsl:if test="/ns0:OBJETO_POLIZA/ns0:VIVIENDA/ns0:NIVEL_3">
            <tns:P_NIVEL_3>
               <xsl:value-of select="/ns0:OBJETO_POLIZA/ns0:VIVIENDA/ns0:NIVEL_3"/>
            </tns:P_NIVEL_3>
         </xsl:if>
         <xsl:if test="/ns0:OBJETO_POLIZA/ns0:VIVIENDA/ns0:UBICACION_UNIDAD">
            <tns:P_UBICACION_UNIDAD>
               <xsl:value-of select="/ns0:OBJETO_POLIZA/ns0:VIVIENDA/ns0:UBICACION_UNIDAD"/>
            </tns:P_UBICACION_UNIDAD>
         </xsl:if>
         <xsl:if test="/ns0:OBJETO_POLIZA/ns0:VIVIENDA/ns0:TIPO_OCUPACION">
            <tns:P_TIPO_DE_OCUPACION>
               <xsl:value-of select="/ns0:OBJETO_POLIZA/ns0:VIVIENDA/ns0:TIPO_OCUPACION"/>
            </tns:P_TIPO_DE_OCUPACION>
         </xsl:if>
         <xsl:if test="/ns0:OBJETO_POLIZA/ns0:VIVIENDA/ns0:OCUPACION">
            <tns:P_OCUPACION>
               <xsl:value-of select="/ns0:OBJETO_POLIZA/ns0:VIVIENDA/ns0:OCUPACION"/>
            </tns:P_OCUPACION>
         </xsl:if>
         <xsl:if test="/ns0:OBJETO_POLIZA/ns0:VIVIENDA/ns0:CONTENIDO">
            <tns:P_SA_CONTENIDO>
               <xsl:value-of select="/ns0:OBJETO_POLIZA/ns0:VIVIENDA/ns0:CONTENIDO"/>
            </tns:P_SA_CONTENIDO>
         </xsl:if>
         <xsl:if test="/ns0:OBJETO_POLIZA/ns0:VIVIENDA/ns0:ESTRUCTURA">
            <tns:P_SA_ESTRUCTURA>
               <xsl:value-of select="/ns0:OBJETO_POLIZA/ns0:VIVIENDA/ns0:ESTRUCTURA"/>
            </tns:P_SA_ESTRUCTURA>
         </xsl:if>
         <xsl:if test="/ns0:OBJETO_POLIZA/ns0:VIVIENDA/ns0:TIPO_CONSTRUCCION">
            <tns:P_TIPO_DE_CONSTRUCCION>
               <xsl:value-of select="/ns0:OBJETO_POLIZA/ns0:VIVIENDA/ns0:TIPO_CONSTRUCCION"/>
            </tns:P_TIPO_DE_CONSTRUCCION>
         </xsl:if>
         <xsl:if test="/ns0:OBJETO_POLIZA/ns0:VIVIENDA/ns0:ACREEDOR">
            <tns:P_ACREEDOR>
               <xsl:value-of select="/ns0:OBJETO_POLIZA/ns0:VIVIENDA/ns0:ACREEDOR"/>
            </tns:P_ACREEDOR>
         </xsl:if>
         <xsl:if test="/ns0:OBJETO_POLIZA/ns0:VIVIENDA/ns0:MEDIDAS_SEGURIDAD">
            <tns:P_MEDIDAS_DE_SEGURIDAD>
               <xsl:value-of select="/ns0:OBJETO_POLIZA/ns0:VIVIENDA/ns0:MEDIDAS_SEGURIDAD"/>
            </tns:P_MEDIDAS_DE_SEGURIDAD>
         </xsl:if>
         <xsl:if test="/ns0:OBJETO_POLIZA/ns0:INFO_PAGO/ns0:CONDUCTO">
            <tns:P_CONDUCTO>
               <xsl:value-of select="/ns0:OBJETO_POLIZA/ns0:INFO_PAGO/ns0:CONDUCTO"/>
            </tns:P_CONDUCTO>
         </xsl:if>
         <xsl:if test="/ns0:OBJETO_POLIZA/ns0:INFO_PAGO/ns0:NUMERO_CUENTA">
            <tns:P_NUMERO_DE_CUENTA>
               <xsl:value-of select="/ns0:OBJETO_POLIZA/ns0:INFO_PAGO/ns0:NUMERO_CUENTA"/>
            </tns:P_NUMERO_DE_CUENTA>
         </xsl:if>
         <xsl:if test="/ns0:OBJETO_POLIZA/ns0:INFO_PAGO/ns0:TIPO_CUENTA">
            <tns:P_TIPO_DE_CUENTA>
               <xsl:value-of select="/ns0:OBJETO_POLIZA/ns0:INFO_PAGO/ns0:TIPO_CUENTA"/>
            </tns:P_TIPO_DE_CUENTA>
         </xsl:if>
         <xsl:if test="/ns0:OBJETO_POLIZA/ns0:INFO_PAGO/ns0:VENCIMIENTO_CUENTA">
            <tns:P_VENCIMIENTO_DE_CUENTA>
               <xsl:value-of select="/ns0:OBJETO_POLIZA/ns0:INFO_PAGO/ns0:VENCIMIENTO_CUENTA"/>
            </tns:P_VENCIMIENTO_DE_CUENTA>
         </xsl:if>
         <xsl:if test="/ns0:OBJETO_POLIZA/ns0:INFO_PAGO/ns0:CEDULA_CUENTAHABIENTE">
            <tns:P_CEDULA_DEL_CUENTAHABIENTE>
               <xsl:value-of select="/ns0:OBJETO_POLIZA/ns0:INFO_PAGO/ns0:CEDULA_CUENTAHABIENTE"/>
            </tns:P_CEDULA_DEL_CUENTAHABIENTE>
         </xsl:if>
         <xsl:if test="/ns0:OBJETO_POLIZA/ns0:INFO_PAGO/ns0:NOMBRE_CUENTAHABIENTE">
            <tns:P_NOMBRE_DEL_CUENTAHABIENTE>
               <xsl:value-of select="/ns0:OBJETO_POLIZA/ns0:INFO_PAGO/ns0:NOMBRE_CUENTAHABIENTE"/>
            </tns:P_NOMBRE_DEL_CUENTAHABIENTE>
         </xsl:if>
         <xsl:if test="/ns0:OBJETO_POLIZA/ns0:INFO_PAGO/ns0:APELLIDO_CUENTAHABIENTE">
            <tns:P_APELLIDO_DEL_CUENTAHABIENTE>
               <xsl:value-of select="/ns0:OBJETO_POLIZA/ns0:INFO_PAGO/ns0:APELLIDO_CUENTAHABIENTE"/>
            </tns:P_APELLIDO_DEL_CUENTAHABIENTE>
         </xsl:if>
         <xsl:if test="/ns0:OBJETO_POLIZA/ns0:INFO_PAGO/ns0:BANCO">
            <tns:P_BANCO>
               <xsl:value-of select="/ns0:OBJETO_POLIZA/ns0:INFO_PAGO/ns0:BANCO"/>
            </tns:P_BANCO>
         </xsl:if>
         <xsl:if test="/ns0:OBJETO_POLIZA/ns0:ESTRUCTURA_COMERCIAL/ns0:REFERENCIA">
            <tns:P_REFERENCIA>
               <xsl:value-of select="/ns0:OBJETO_POLIZA/ns0:ESTRUCTURA_COMERCIAL/ns0:REFERENCIA"/>
            </tns:P_REFERENCIA>
         </xsl:if>
         <xsl:if test="/ns0:OBJETO_POLIZA/ns0:ESTRUCTURA_COMERCIAL/ns0:CODIGO_FUNCIONARIO">
            <tns:P_COD_FUNCIONARIO>
               <xsl:value-of select="/ns0:OBJETO_POLIZA/ns0:ESTRUCTURA_COMERCIAL/ns0:CODIGO_FUNCIONARIO"/>
            </tns:P_COD_FUNCIONARIO>
         </xsl:if>
         <xsl:if test="/ns0:OBJETO_POLIZA/ns0:ESTRUCTURA_COMERCIAL/ns0:SUCURSAL">
            <tns:P_BS_SUCURSAL>
               <xsl:value-of select="/ns0:OBJETO_POLIZA/ns0:ESTRUCTURA_COMERCIAL/ns0:SUCURSAL"/>
            </tns:P_BS_SUCURSAL>
         </xsl:if>
         <xsl:if test="/ns0:OBJETO_POLIZA/ns0:ESTRUCTURA_COMERCIAL/ns0:SECUENCIA_ASIGNACION">
            <tns:P_SECUENCIA_ASIGNACION>
               <xsl:value-of select="/ns0:OBJETO_POLIZA/ns0:ESTRUCTURA_COMERCIAL/ns0:SECUENCIA_ASIGNACION"/>
            </tns:P_SECUENCIA_ASIGNACION>
         </xsl:if>
         <xsl:if test="/ns0:OBJETO_POLIZA/ns0:ESTRUCTURA_COMERCIAL/ns0:CODIGO_ESTRATEGIA">
            <tns:P_COD_ESTRATEGIA>
               <xsl:value-of select="/ns0:OBJETO_POLIZA/ns0:ESTRUCTURA_COMERCIAL/ns0:CODIGO_ESTRATEGIA"/>
            </tns:P_COD_ESTRATEGIA>
         </xsl:if>
         <xsl:if test="/ns0:OBJETO_POLIZA/ns0:CONTRATANTE/ns0:NUMERO_IDENTIFICACION">
            <tns:P_CONTRATANTE>
               <xsl:value-of select="/ns0:OBJETO_POLIZA/ns0:CONTRATANTE/ns0:NUMERO_IDENTIFICACION"/>
            </tns:P_CONTRATANTE>
         </xsl:if>
         <xsl:if test="/ns0:OBJETO_POLIZA/ns0:CONTRATANTE/ns0:NOMBRE">
            <tns:P_NOMBRE_CONTRATANTE>
               <xsl:value-of select="/ns0:OBJETO_POLIZA/ns0:CONTRATANTE/ns0:NOMBRE"/>
            </tns:P_NOMBRE_CONTRATANTE>
         </xsl:if>
         <xsl:if test="/ns0:OBJETO_POLIZA/ns0:CONTRATANTE/ns0:DIRECCION">
            <tns:P_DIRECCION_CONTRATANTE>
               <xsl:value-of select="/ns0:OBJETO_POLIZA/ns0:CONTRATANTE/ns0:DIRECCION"/>
            </tns:P_DIRECCION_CONTRATANTE>
         </xsl:if>
         <xsl:if test="/ns0:OBJETO_POLIZA/ns0:CONTRATANTE/ns0:TELEFONO">
            <tns:P_TELEFONO_CONTRATANTE>
               <xsl:value-of select="/ns0:OBJETO_POLIZA/ns0:CONTRATANTE/ns0:TELEFONO"/>
            </tns:P_TELEFONO_CONTRATANTE>
         </xsl:if>
         <xsl:if test="/ns0:OBJETO_POLIZA/ns0:CONTRATANTE/ns0:EMAIL">
            <tns:P_EMAIL_CONTRATANTE>
               <xsl:value-of select="/ns0:OBJETO_POLIZA/ns0:CONTRATANTE/ns0:EMAIL"/>
            </tns:P_EMAIL_CONTRATANTE>
         </xsl:if>
         <xsl:if test="/ns0:OBJETO_POLIZA/ns0:CONTRATANTE/ns0:USUARIO">
            <tns:P_USUARIO>
               <xsl:value-of select="/ns0:OBJETO_POLIZA/ns0:CONTRATANTE/ns0:USUARIO"/>
            </tns:P_USUARIO>
         </xsl:if>
      </tns:InputParameters>
   </xsl:template>
</xsl:stylesheet>
