<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:ns0="http://sura.com.pa/matrizRiesgoCliente/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/sp/dbInsis" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../../../Exp_ValidarRiesgoCliente/Resources/matrizRiesgoCliente.wsdl"/>
            <oracle-xsl-mapper:rootElement name="validarRiesgoCliente" namespace="http://sura.com.pa/matrizRiesgoCliente/"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../database/dbInsis_sp.xsd"/>
            <oracle-xsl-mapper:rootElement name="InputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/dbInsis"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [SUN MAR 15 16:55:28 COT 2020].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:InputParameters>
         <xsl:if test="/ns0:validarRiesgoCliente/idPersona">
            <tns:PI_IDPEOPLE>
               <xsl:value-of select="/ns0:validarRiesgoCliente/idPersona"/>
            </tns:PI_IDPEOPLE>
         </xsl:if>
         <xsl:if test="/ns0:validarRiesgoCliente/tipoID">
            <tns:PI_TYPEIDPEOPLE>
               <xsl:value-of select="/ns0:validarRiesgoCliente/tipoID"/>
            </tns:PI_TYPEIDPEOPLE>
         </xsl:if>
         <xsl:if test="/ns0:validarRiesgoCliente/codigoActividadEconomica">
            <tns:PI_CODEECONOMICACTIVITY>
               <xsl:value-of select="/ns0:validarRiesgoCliente/codigoActividadEconomica"/>
            </tns:PI_CODEECONOMICACTIVITY>
         </xsl:if>
         <xsl:if test="/ns0:validarRiesgoCliente/codigoOcupacion">
            <tns:PI_CODEOCCUPATION>
               <xsl:value-of select="/ns0:validarRiesgoCliente/codigoOcupacion"/>
            </tns:PI_CODEOCCUPATION>
         </xsl:if>
         <xsl:if test="/ns0:validarRiesgoCliente/codigoPais">
            <tns:PI_CODECOUNTRY>
               <xsl:value-of select="/ns0:validarRiesgoCliente/codigoPais"/>
            </tns:PI_CODECOUNTRY>
         </xsl:if>
         <xsl:if test="/ns0:validarRiesgoCliente/codigoProvincia">
            <tns:PI_CODESTATE>
               <xsl:value-of select="/ns0:validarRiesgoCliente/codigoProvincia"/>
            </tns:PI_CODESTATE>
         </xsl:if>
         <xsl:if test="/ns0:validarRiesgoCliente/ingresosAnuales">
            <tns:PI_ANNUALINCOME>
               <xsl:value-of select="/ns0:validarRiesgoCliente/ingresosAnuales"/>
            </tns:PI_ANNUALINCOME>
         </xsl:if>
         <xsl:if test="/ns0:validarRiesgoCliente/expuestoPolitico">
            <tns:PI_EXPOSEDPOLITIC>
               <xsl:value-of select="/ns0:validarRiesgoCliente/expuestoPolitico"/>
            </tns:PI_EXPOSEDPOLITIC>
         </xsl:if>
         <xsl:if test="/ns0:validarRiesgoCliente/familiar_expuestoPolitico">
            <tns:PI_EXPOSEDFAMILYPOLITIC>
               <xsl:value-of select="/ns0:validarRiesgoCliente/familiar_expuestoPolitico"/>
            </tns:PI_EXPOSEDFAMILYPOLITIC>
         </xsl:if>
         <xsl:if test="/ns0:validarRiesgoCliente/codigoProducto">
            <tns:PI_CODEPRODUCT>
               <xsl:value-of select="/ns0:validarRiesgoCliente/codigoProducto"/>
            </tns:PI_CODEPRODUCT>
         </xsl:if>
         <xsl:if test="/ns0:validarRiesgoCliente/primaAnual">
            <tns:PI_ANNUALPREMIUM>
               <xsl:value-of select="/ns0:validarRiesgoCliente/primaAnual"/>
            </tns:PI_ANNUALPREMIUM>
         </xsl:if>
         <xsl:if test="/ns0:validarRiesgoCliente/formaPago">
            <tns:PI_WAYPAY>
               <xsl:value-of select="/ns0:validarRiesgoCliente/formaPago"/>
            </tns:PI_WAYPAY>
         </xsl:if>
      </tns:InputParameters>
   </xsl:template>
</xsl:stylesheet>