<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ServiciosIntegracionSURA/Dat_ObtenerPolizasCorredores/sp_get_polizas_corredores" name="sp_get_polizas_corredores-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="sp_get_polizas_corredores.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ServiciosIntegracionSURA/Dat_ObtenerPolizasCorredores/sp_get_polizas_corredores"/>
    <wsdl:binding name="sp_get_polizas_corredores_ptt-binding" type="sp:sp_get_polizas_corredores_ptt" xmlns:sp="http://xmlns.oracle.com/pcbpel/adapter/db/ServiciosIntegracionSURA/Dat_ObtenerPolizasCorredores/sp_get_polizas_corredores">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="sp_get_polizas_corredores">
            <soap:operation soapAction="sp_get_polizas_corredores"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>