<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="BPELProcesarPago"
     targetNamespace="http://xmlns.oracle.com/e2e_1201_composites/ProcesarPago/BPELProcesarPago"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:client="http://xmlns.oracle.com/e2e_1201_composites/ProcesarPago/BPELProcesarPago"
     xmlns:ns1="http://TargetNamespace.com/jmsProcesarPago"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:ns2="http://TargetNamespace.com/ConsultarPcPremium"
     xmlns:ns3="http://TargetNamespace.com/CrearDetallePC"
     xmlns:ns4="http://TargetNamespace.com/ConsultarNumeroPC"
     xmlns:ns5="http://TargetNamespace.com/FinalizarPC"
     xmlns:ns6="http://schemas.oracle.com/bpel/extension"
    >
    <wsdl:import namespace="http://schemas.oracle.com/bpel/extension" location="RuntimeFault.wsdl"/>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
             xmlns:client="http://xmlns.oracle.com/e2e_1201_composites/ProcesarPago/BPELProcesarPago"
             xmlns:ns1="http://TargetNamespace.com/jmsProcesarPago" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
             xmlns:ns2="http://TargetNamespace.com/ConsultarPcPremium" xmlns:ns3="http://TargetNamespace.com/CrearDetallePC"
             xmlns:ns4="http://TargetNamespace.com/ConsultarNumeroPC" xmlns:ns5="http://TargetNamespace.com/FinalizarPC">
            <import namespace="http://TargetNamespace.com/jmsProcesarPago" schemaLocation="../Schemas/ProcesarPagoRq.xsd"/>
        </schema>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
             xmlns:client="http://xmlns.oracle.com/e2e_1201_composites/ProcesarPago/BPELProcesarPago"
             xmlns:ns1="http://TargetNamespace.com/jmsProcesarPago" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
             xmlns:ns2="http://TargetNamespace.com/ConsultarPcPremium" xmlns:ns3="http://TargetNamespace.com/CrearDetallePC"
             xmlns:ns4="http://TargetNamespace.com/ConsultarNumeroPC" xmlns:ns5="http://TargetNamespace.com/FinalizarPC">
            <xsd:import namespace="http://TargetNamespace.com/ConsultarPcPremium" schemaLocation="../Schemas/RsConsultarPcPremium.xsd"/>
        </xsd:schema>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
             xmlns:client="http://xmlns.oracle.com/e2e_1201_composites/ProcesarPago/BPELProcesarPago"
             xmlns:ns1="http://TargetNamespace.com/jmsProcesarPago" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
             xmlns:ns2="http://TargetNamespace.com/ConsultarPcPremium" xmlns:ns3="http://TargetNamespace.com/CrearDetallePC"
             xmlns:ns4="http://TargetNamespace.com/ConsultarNumeroPC" xmlns:ns5="http://TargetNamespace.com/FinalizarPC">
            <xsd:import namespace="http://TargetNamespace.com/CrearDetallePC" schemaLocation="../Schemas/RqCrearDetallePC.xsd"/>
        </xsd:schema>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
             xmlns:client="http://xmlns.oracle.com/e2e_1201_composites/ProcesarPago/BPELProcesarPago"
             xmlns:ns1="http://TargetNamespace.com/jmsProcesarPago" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
             xmlns:ns2="http://TargetNamespace.com/ConsultarPcPremium" xmlns:ns3="http://TargetNamespace.com/CrearDetallePC"
             xmlns:ns4="http://TargetNamespace.com/ConsultarNumeroPC" xmlns:ns5="http://TargetNamespace.com/FinalizarPC">
            <xsd:import namespace="http://TargetNamespace.com/ConsultarNumeroPC" schemaLocation="../Schemas/RsConsultarNumeroPC.xsd"/>
        </xsd:schema>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
             xmlns:client="http://xmlns.oracle.com/e2e_1201_composites/ProcesarPago/BPELProcesarPago"
             xmlns:ns1="http://TargetNamespace.com/jmsProcesarPago" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
             xmlns:ns2="http://TargetNamespace.com/ConsultarPcPremium" xmlns:ns3="http://TargetNamespace.com/CrearDetallePC"
             xmlns:ns4="http://TargetNamespace.com/ConsultarNumeroPC" xmlns:ns5="http://TargetNamespace.com/FinalizarPC">
            <xsd:import namespace="http://TargetNamespace.com/CrearDetallePC" schemaLocation="../Schemas/RsCrearDetallePC.xsd"/>
        </xsd:schema>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
             xmlns:client="http://xmlns.oracle.com/e2e_1201_composites/ProcesarPago/BPELProcesarPago"
             xmlns:ns1="http://TargetNamespace.com/jmsProcesarPago" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
             xmlns:ns2="http://TargetNamespace.com/ConsultarPcPremium" xmlns:ns3="http://TargetNamespace.com/CrearDetallePC"
             xmlns:ns4="http://TargetNamespace.com/ConsultarNumeroPC" xmlns:ns5="http://TargetNamespace.com/FinalizarPC">
            <xsd:import namespace="http://TargetNamespace.com/FinalizarPC" schemaLocation="../Schemas/RqFinalizarPC.xsd"/>
        </xsd:schema>
    </wsdl:types>
</wsdl:definitions>
