<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:tns="http://xmlns.sura.com/MensajeIntegracion/DominioUtilitario/GestionDocumentalMI/V1" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:ns0="http://xmlns.sura.com/MensajeIntegracion/DominioProceso/BPMMI/V1" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction"
                xmlns:dpropro="http://www.sura.com/ObjetoEmpresarial/DominioProceso/Proceso/V1"
                xmlns:dcomcom="http://xmlns.sura.com/ObjetoEmpresarial/DominioComun/Comun/V1"
                xmlns:ns1="http://xmlns.sura.com/ObjetoIntegracion/DominioProceso/Proceso/V1"
                xmlns:dutigdoc="http://xmlns.sura.com/ObjetoIntegracion/DominioUtilitario/GestionDocumental/V1"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:ns2="http://sura.com.pa/GestionarActividadDocumento/">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../wsdl/GestionarActividadDocumento.wsdl"/>
            <oracle-xsl-mapper:rootElement name="GestionarActividadDocumentoReq" namespace="http://sura.com.pa/GestionarActividadDocumento/"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../../../ComponentesComunes/WSDL/xsd/DominioUtilitario/GestionDocumental/V1/GestionDocumentalMIV1.xsd"/>
            <oracle-xsl-mapper:rootElement name="AlmacenarDocumentoOnBaseMsjSol" namespace="http://xmlns.sura.com/MensajeIntegracion/DominioUtilitario/GestionDocumentalMI/V1"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [THU OCT 21 21:30:21 COT 2021].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:AlmacenarDocumentoOnBaseMsjSol>
         <tns:CabeceraSol>
            <dcomcom:CodigoOperacion>
               <xsl:value-of select="/ns2:GestionarActividadDocumentoReq/ns2:CABECERA/ns2:CODIGO_OPERACION"/>
            </dcomcom:CodigoOperacion>
            <dcomcom:FechaProcesamiento>
               <xsl:value-of select="/ns2:GestionarActividadDocumentoReq/ns2:CABECERA/ns2:FECHA_PROCESAMIENTO"/>
            </dcomcom:FechaProcesamiento>
            <dcomcom:FechaTransaccion>
               <xsl:value-of select="/ns2:GestionarActividadDocumentoReq/ns2:CABECERA/ns2:FECHA_TRANSACCION"/>
            </dcomcom:FechaTransaccion>
            <dcomcom:IdTransaccionOsb>
               <xsl:value-of select="/ns2:GestionarActividadDocumentoReq/ns2:CABECERA/ns2:ID_TRANSACCION_OSB"/>
            </dcomcom:IdTransaccionOsb>
            <dcomcom:SistemaDestino>
               <xsl:value-of select="/ns2:GestionarActividadDocumentoReq/ns2:CABECERA/ns2:SISTEMA_DESTINO"/>
            </dcomcom:SistemaDestino>
            <dcomcom:SistemaOrigen>
               <xsl:value-of select="/ns2:GestionarActividadDocumentoReq/ns2:CABECERA/ns2:SISTEMA_ORIGEN"/>
            </dcomcom:SistemaOrigen>
         </tns:CabeceraSol>
         <tns:IdDocumental>
            <xsl:value-of select="/ns2:GestionarActividadDocumentoReq/ns2:Documento/ns2:IdDocumental"/>
         </tns:IdDocumental>
         <tns:Atributos>
            <xsl:for-each select="/ns2:GestionarActividadDocumentoReq/ns2:Documento/ns2:AtributosRelacion/ns2:Atributo">
               <dutigdoc:Atributo>
                  <dutigdoc:IdParametro>
                     <xsl:value-of select="ns2:Id"/>
                  </dutigdoc:IdParametro>
                  <dutigdoc:Nombre>
                     <xsl:value-of select="ns2:Nombre"/>
                  </dutigdoc:Nombre>
                  <dutigdoc:Valor>
                     <xsl:value-of select="ns2:Valor"/>
                  </dutigdoc:Valor>
               </dutigdoc:Atributo>
            </xsl:for-each>
         </tns:Atributos>
         <tns:Paginas>
            <xsl:for-each select="/ns2:GestionarActividadDocumentoReq/ns2:Documento/ns2:Adjunto">
               <dutigdoc:Pagina>
                  <dutigdoc:Contenido>
                     <xsl:value-of select="ns2:Contenido"/>
                  </dutigdoc:Contenido>
                  <dutigdoc:IdFormato>
                     <xsl:value-of select="ns2:IdFormato"/>
                  </dutigdoc:IdFormato>
               </dutigdoc:Pagina>
            </xsl:for-each>
         </tns:Paginas>
      </tns:AlmacenarDocumentoOnBaseMsjSol>
   </xsl:template>
</xsl:stylesheet>
