<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:ns0="http://www.sura.com/BssEmisionAP" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:tns="http://www.sura.com/EmitirPolizaAP" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../../../Jms_EmitirPolizaNubeSeguros/Resources/nxsd/BssEmisionAP.xsd"/>
            <oracle-xsl-mapper:rootElement name="EmisionAP" namespace="http://www.sura.com/BssEmisionAP"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../../../ComponentesComunes/XSD_Externos/EmitirPolizaAP.xsd"/>
            <oracle-xsl-mapper:rootElement name="OBJETO_POLIZA" namespace="http://www.sura.com/EmitirPolizaAP"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [FRI AUG 07 14:05:23 COT 2020].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:OBJETO_POLIZA>
         <tns:CABECERA>
            <tns:FECHA_TRANSACCION>
               <xsl:value-of select="/ns0:EmisionAP/ns0:CABECERA/ns0:FECHA_TRANSACCION"/>
            </tns:FECHA_TRANSACCION>
            <tns:FECHA_PROCESAMIENTO>
               <xsl:value-of select="/ns0:EmisionAP/ns0:CABECERA/ns0:FECHA_PROCESAMIENTO"/>
            </tns:FECHA_PROCESAMIENTO>
            <tns:SISTEMA_DESTINO>
               <xsl:value-of select="/ns0:EmisionAP/ns0:CABECERA/ns0:SISTEMA_DESTINO"/>
            </tns:SISTEMA_DESTINO>
            <tns:SISTEMA_ORIGEN>
               <xsl:value-of select="/ns0:EmisionAP/ns0:CABECERA/ns0:SISTEMA_ORIGEN"/>
            </tns:SISTEMA_ORIGEN>
            <tns:CODIGO_OPERACION>
               <xsl:value-of select="/ns0:EmisionAP/ns0:CABECERA/ns0:CODIGO_OPERACION"/>
            </tns:CODIGO_OPERACION>
         </tns:CABECERA>
         <tns:CORE>
            <xsl:value-of select="/ns0:EmisionAP/ns0:CORE"/>
         </tns:CORE>
         <xsl:if test="/ns0:EmisionAP/ns0:CONTRATANTE/ns0:NUMERO_IDENTIFICACION">
            <tns:NUMERO_IDENTIFICACION_ASEGURADO>
               <xsl:value-of select="/ns0:EmisionAP/ns0:CONTRATANTE/ns0:NUMERO_IDENTIFICACION"/>
            </tns:NUMERO_IDENTIFICACION_ASEGURADO>
         </xsl:if>
         <tns:POLIZA>
            <xsl:if test="/ns0:EmisionAP/ns0:POLIZA/ns0:PLAN">
               <tns:PLAN>
                  <xsl:value-of select="/ns0:EmisionAP/ns0:POLIZA/ns0:PLAN"/>
               </tns:PLAN>
            </xsl:if>
            <xsl:if test="/ns0:EmisionAP/ns0:POLIZA/ns0:NUMERO_POLIZA">
               <tns:NUMERO_POLIZA>
                  <xsl:value-of select="/ns0:EmisionAP/ns0:POLIZA/ns0:NUMERO_POLIZA"/>
               </tns:NUMERO_POLIZA>
            </xsl:if>
            <xsl:if test="/ns0:EmisionAP/ns0:POLIZA/ns0:VIGENCIA_DESDE">
               <tns:VIGENCIA_DESDE>
                  <xsl:value-of select="/ns0:EmisionAP/ns0:POLIZA/ns0:VIGENCIA_DESDE"/>
               </tns:VIGENCIA_DESDE>
            </xsl:if>
            <xsl:if test="/ns0:EmisionAP/ns0:POLIZA/ns0:VIGENCIA_HASTA">
               <tns:VIGENCIA_HASTA>
                  <xsl:value-of select="/ns0:EmisionAP/ns0:POLIZA/ns0:VIGENCIA_HASTA"/>
               </tns:VIGENCIA_HASTA>
            </xsl:if>
            <xsl:if test="/ns0:EmisionAP/ns0:POLIZA/ns0:OBSERVACION">
               <tns:OBSERVACION>
                  <xsl:value-of select="/ns0:EmisionAP/ns0:POLIZA/ns0:OBSERVACION"/>
               </tns:OBSERVACION>
            </xsl:if>
            <xsl:if test="/ns0:EmisionAP/ns0:POLIZA/ns0:SUMA_ASEGURADA">
               <tns:SUMA_ASEGURADA>
                  <xsl:value-of select="/ns0:EmisionAP/ns0:POLIZA/ns0:SUMA_ASEGURADA"/>
               </tns:SUMA_ASEGURADA>
            </xsl:if>
            <xsl:if test="/ns0:EmisionAP/ns0:POLIZA/ns0:CLASE">
               <tns:CLASE>
                  <xsl:value-of select="/ns0:EmisionAP/ns0:POLIZA/ns0:CLASE"/>
               </tns:CLASE>
            </xsl:if>
            <xsl:if test="/ns0:EmisionAP/ns0:POLIZA/ns0:DURACION">
               <tns:DURACION>
                  <xsl:value-of select="/ns0:EmisionAP/ns0:POLIZA/ns0:DURACION"/>
               </tns:DURACION>
            </xsl:if>
            <xsl:if test="/ns0:EmisionAP/ns0:POLIZA/ns0:USUARIO">
               <tns:USUARIO>
                  <xsl:value-of select="/ns0:EmisionAP/ns0:POLIZA/ns0:USUARIO"/>
               </tns:USUARIO>
            </xsl:if>
         </tns:POLIZA>
         <tns:CONTRATANTE>
            <xsl:if test="/ns0:EmisionAP/ns0:CONTRATANTE/ns0:NUMERO_IDENTIFICACION">
               <tns:NUMERO_IDENTIFICACION>
                  <xsl:value-of select="/ns0:EmisionAP/ns0:CONTRATANTE/ns0:NUMERO_IDENTIFICACION"/>
               </tns:NUMERO_IDENTIFICACION>
            </xsl:if>
            <xsl:if test="/ns0:EmisionAP/ns0:CONTRATANTE/ns0:NOMBRE">
               <tns:NOMBRE>
                  <xsl:value-of select="concat (/ns0:EmisionAP/ns0:CONTRATANTE/ns0:NOMBRE, &quot; &quot;, /ns0:EmisionAP/ns0:CONTRATANTE/ns0:SEGUNDO_NOMBRE, &quot; &quot;, /ns0:EmisionAP/ns0:CONTRATANTE/ns0:APELLIDO, &quot; &quot;, /ns0:EmisionAP/ns0:CONTRATANTE/ns0:SEGUNDO_APELLIDO )"/>
               </tns:NOMBRE>
            </xsl:if>
            <xsl:if test="/ns0:EmisionAP/ns0:CONTRATANTE/ns0:APELLIDO">
               <tns:APELLIDO>
                  <xsl:value-of select="/ns0:EmisionAP/ns0:CONTRATANTE/ns0:APELLIDO"/>
               </tns:APELLIDO>
            </xsl:if>
            <xsl:if test="/ns0:EmisionAP/ns0:CONTRATANTE/ns0:TELEFONO">
               <tns:TELEFONO>
                  <xsl:value-of select="/ns0:EmisionAP/ns0:CONTRATANTE/ns0:TELEFONO"/>
               </tns:TELEFONO>
            </xsl:if>
         </tns:CONTRATANTE>
         <xsl:for-each select="/ns0:EmisionAP/ns0:OBJETO_ASEGURADO/ns0:PERSONA_ASEGURADA/ns0:BENEFICIARIO">
            <tns:BENEFICIARIOS>
               <xsl:if test="ns0:NOMBRE">
                  <tns:NOMBRE>
                     <xsl:value-of select="ns0:NOMBRE"/>
                  </tns:NOMBRE>
               </xsl:if>
               <xsl:if test="ns0:APELLIDO">
                  <tns:APELLIDO>
                     <xsl:value-of select="ns0:APELLIDO"/>
                  </tns:APELLIDO>
               </xsl:if>
               <xsl:if test="ns0:NUMERO_IDENTIFICACION">
                  <tns:NUMERO_IDENTIFICACION>
                     <xsl:value-of select="ns0:NUMERO_IDENTIFICACION"/>
                  </tns:NUMERO_IDENTIFICACION>
               </xsl:if>
               <xsl:if test="ns0:PARENTESCO">
                  <tns:PARENTESCO>
                     <xsl:value-of select="ns0:PARENTESCO"/>
                  </tns:PARENTESCO>
               </xsl:if>
               <xsl:if test="ns0:TIPO_PERSONA">
                  <tns:TIPO_PERSONA>
                     <xsl:value-of select="ns0:TIPO_PERSONA"/>
                  </tns:TIPO_PERSONA>
               </xsl:if>
               <xsl:if test="ns0:FECHA_NACIMIENTO">
                  <tns:FECHA_NACIMIENTO>
                     <xsl:value-of select="ns0:FECHA_NACIMIENTO"/>
                  </tns:FECHA_NACIMIENTO>
               </xsl:if>
               <xsl:if test="ns0:SEXO">
                  <tns:SEXO>
                     <xsl:value-of select="ns0:SEXO"/>
                  </tns:SEXO>
               </xsl:if>
               <xsl:if test="ns0:ADMINISTRADOR_FIDUCIARIO">
                  <tns:ADMINISTRADOR_FIDUCIARIO>
                     <xsl:value-of select="ns0:ADMINISTRADOR_FIDUCIARIO"/>
                  </tns:ADMINISTRADOR_FIDUCIARIO>
               </xsl:if>
               <xsl:if test="ns0:JERARQUIA">
                  <tns:JERARQUIA>
                     <xsl:value-of select="ns0:JERARQUIA"/>
                  </tns:JERARQUIA>
               </xsl:if>
               <xsl:if test="ns0:PORCENTAJE_BENEFICIARIO">
                  <tns:PORCENTAJE_BENEFICIARIO>
                     <xsl:value-of select="ns0:PORCENTAJE_BENEFICIARIO"/>
                  </tns:PORCENTAJE_BENEFICIARIO>
               </xsl:if>
            </tns:BENEFICIARIOS>
         </xsl:for-each>
         <tns:ESTRUCTURA_COMERCIAL>
            <xsl:if test="/ns0:EmisionAP/ns0:ESTRUCTURA_COMERCIAL/ns0:REFERENCIA">
               <tns:REFERENCIA>
                  <xsl:value-of select="/ns0:EmisionAP/ns0:ESTRUCTURA_COMERCIAL/ns0:REFERENCIA"/>
               </tns:REFERENCIA>
            </xsl:if>
            <xsl:if test="/ns0:EmisionAP/ns0:ESTRUCTURA_COMERCIAL/ns0:CODIGO_FUNCIONARIO">
               <tns:CODIGO_FUNCIONARIO>
                  <xsl:value-of select="/ns0:EmisionAP/ns0:ESTRUCTURA_COMERCIAL/ns0:CODIGO_FUNCIONARIO"/>
               </tns:CODIGO_FUNCIONARIO>
            </xsl:if>
            <xsl:if test="/ns0:EmisionAP/ns0:ESTRUCTURA_COMERCIAL/ns0:SUCURSAL">
               <tns:SUCURSAL>
                  <xsl:value-of select="/ns0:EmisionAP/ns0:ESTRUCTURA_COMERCIAL/ns0:SUCURSAL"/>
               </tns:SUCURSAL>
            </xsl:if>
            <xsl:if test="/ns0:EmisionAP/ns0:ESTRUCTURA_COMERCIAL/ns0:SECUENCIA_ASIGNACION">
               <tns:SECUENCIA_ASIGNACION>
                  <xsl:value-of select="/ns0:EmisionAP/ns0:ESTRUCTURA_COMERCIAL/ns0:SECUENCIA_ASIGNACION"/>
               </tns:SECUENCIA_ASIGNACION>
            </xsl:if>
            <xsl:if test="/ns0:EmisionAP/ns0:ESTRUCTURA_COMERCIAL/ns0:CODIGO_ESTRATEGIA">
               <tns:CODIGO_ESTRATEGIA>
                  <xsl:value-of select="/ns0:EmisionAP/ns0:ESTRUCTURA_COMERCIAL/ns0:CODIGO_ESTRATEGIA"/>
               </tns:CODIGO_ESTRATEGIA>
            </xsl:if>
         </tns:ESTRUCTURA_COMERCIAL>
      </tns:OBJETO_POLIZA>
   </xsl:template>
</xsl:stylesheet>