<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:ns0="http://www.sura.com/BssEmisionMPH" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:tns="http://www.sura.com/EmitirPolizaMPH" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd" xmlns:x2r="http://www.oracle.com/odi/xml-mapping">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../../../Jms_EmitirPolizaNubeSeguros/Resources/nxsd/BssEmisionMPH.xsd"/>
            <oracle-xsl-mapper:rootElement name="EmisionMPH" namespace="http://www.sura.com/BssEmisionMPH"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../../../ComponentesComunes/XSD_Externos/EmitirPolizaMPH.xsd"/>
            <oracle-xsl-mapper:rootElement name="OBJETO_POLIZA" namespace="http://www.sura.com/EmitirPolizaMPH"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [FRI AUG 07 10:30:29 COT 2020].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:OBJETO_POLIZA>
         
         <tns:CABECERA>
            <tns:FECHA_TRANSACCION>
               <xsl:value-of select="/ns0:EmisionMPH/ns0:CABECERA/ns0:FECHA_TRANSACCION"/>
            </tns:FECHA_TRANSACCION>
            <tns:FECHA_PROCESAMIENTO>
               <xsl:value-of select="/ns0:EmisionMPH/ns0:CABECERA/ns0:FECHA_PROCESAMIENTO"/>
            </tns:FECHA_PROCESAMIENTO>
            <tns:SISTEMA_DESTINO>
               <xsl:value-of select="/ns0:EmisionMPH/ns0:CABECERA/ns0:SISTEMA_DESTINO"/>
            </tns:SISTEMA_DESTINO>
            <tns:SISTEMA_ORIGEN>
               <xsl:value-of select="/ns0:EmisionMPH/ns0:CABECERA/ns0:SISTEMA_ORIGEN"/>
            </tns:SISTEMA_ORIGEN>
            <tns:CODIGO_OPERACION>
               <xsl:value-of select="/ns0:EmisionMPH/ns0:CABECERA/ns0:CODIGO_OPERACION"/>
            </tns:CODIGO_OPERACION>
         </tns:CABECERA>
         <tns:CORE>
            <xsl:value-of select="/ns0:EmisionMPH/ns0:CORE"/>
         </tns:CORE>
         <tns:POLIZA>
            <xsl:if test="/ns0:EmisionMPH/ns0:POLIZA/ns0:PLAN">
               <tns:PLAN>
                  <xsl:value-of select="/ns0:EmisionMPH/ns0:POLIZA/ns0:PLAN"/>
               </tns:PLAN>
            </xsl:if>
            <xsl:if test="/ns0:EmisionMPH/ns0:POLIZA/ns0:NUMERO_POLIZA">
               <tns:NUMERO_POLIZA>
                  <xsl:value-of select="/ns0:EmisionMPH/ns0:POLIZA/ns0:NUMERO_POLIZA"/>
               </tns:NUMERO_POLIZA>
            </xsl:if>
            <xsl:if test="/ns0:EmisionMPH/ns0:POLIZA/ns0:VIGENCIA_DESDE">
               <tns:VIGENCIA_DESDE>
                  <xsl:value-of select="/ns0:EmisionMPH/ns0:POLIZA/ns0:VIGENCIA_DESDE"/>
               </tns:VIGENCIA_DESDE>
            </xsl:if>
            <xsl:if test="/ns0:EmisionMPH/ns0:POLIZA/ns0:VIGENCIA_HASTA">
               <tns:VIGENCIA_HASTA>
                  <xsl:value-of select="/ns0:EmisionMPH/ns0:POLIZA/ns0:VIGENCIA_HASTA"/>
               </tns:VIGENCIA_HASTA>
            </xsl:if>
            <xsl:if test="/ns0:EmisionMPH/ns0:POLIZA/ns0:OBSERVACION">
               <tns:OBSERVACION>
                  <xsl:value-of select="/ns0:EmisionMPH/ns0:POLIZA/ns0:OBSERVACION"/>
               </tns:OBSERVACION>
            </xsl:if>
            <xsl:if test="/ns0:EmisionMPH/ns0:POLIZA/ns0:SUMA_ASEGURADA">
               <tns:SUMA_ASEGURADA>
                  <xsl:value-of select="/ns0:EmisionMPH/ns0:POLIZA/ns0:SUMA_ASEGURADA"/>
               </tns:SUMA_ASEGURADA>
            </xsl:if>
         </tns:POLIZA>
         <tns:CONTRATANTE>
            
            <xsl:if test="/ns0:EmisionMPH/ns0:CONTRATANTE/ns0:DIRECCIONES/ns0:DIRECCION">
               <tns:DIRECCION>
                  <xsl:value-of select="/ns0:EmisionMPH/ns0:CONTRATANTE/ns0:DIRECCIONES/ns0:DIRECCION"/>
               </tns:DIRECCION>
            </xsl:if>
            <xsl:if test="/ns0:EmisionMPH/ns0:CONTRATANTE/ns0:NUMERO_IDENTIFICACION">
               <tns:NUMERO_IDENTIFICACION>
                  <xsl:value-of select="/ns0:EmisionMPH/ns0:CONTRATANTE/ns0:NUMERO_IDENTIFICACION"/>
               </tns:NUMERO_IDENTIFICACION>
            </xsl:if>
            <xsl:if test="/ns0:EmisionMPH/ns0:CONTRATANTE/ns0:DIRECCIONES/ns0:TELEFONO">
               <tns:TELEFONO>
                  <xsl:value-of select="/ns0:EmisionMPH/ns0:CONTRATANTE/ns0:DIRECCIONES/ns0:TELEFONO"/>
               </tns:TELEFONO>
            </xsl:if>
            <xsl:if test="/ns0:EmisionMPH/ns0:CONTRATANTE/ns0:DIRECCIONES/ns0:EMAIL">
               <tns:EMAIL>
                  <xsl:value-of select="/ns0:EmisionMPH/ns0:CONTRATANTE/ns0:DIRECCIONES/ns0:EMAIL"/>
               </tns:EMAIL>
            </xsl:if>
            <xsl:if test="/ns0:EmisionMPH/ns0:CONTRATANTE/ns0:NOMBRE">
               <tns:NOMBRE>
                  <xsl:value-of select="concat (/ns0:EmisionMPH/ns0:CONTRATANTE/ns0:NOMBRE, &quot; &quot;, /ns0:EmisionMPH/ns0:CONTRATANTE/ns0:SEGUNDO_NOMBRE, &quot; &quot;, /ns0:EmisionMPH/ns0:CONTRATANTE/ns0:APELLIDO, &quot; &quot;, /ns0:EmisionMPH/ns0:CONTRATANTE/ns0:SEGUNDO_APELLIDO )"/>
               </tns:NOMBRE>
            </xsl:if>
            <xsl:if test="/ns0:EmisionMPH/ns0:POLIZA/ns0:USUARIO">
               <tns:USUARIO>
                  <xsl:value-of select="/ns0:EmisionMPH/ns0:POLIZA/ns0:USUARIO"/>
               </tns:USUARIO>
            </xsl:if>
            <xsl:if test="/ns0:EmisionMPH/ns0:CONTRATANTE/ns0:TELEFONO">
               <tns:CELULAR>
                  <xsl:value-of select="/ns0:EmisionMPH/ns0:CONTRATANTE/ns0:TELEFONO"/>
               </tns:CELULAR>
            </xsl:if>
         </tns:CONTRATANTE>
         <xsl:if test="/ns0:EmisionMPH/ns0:CONTRATANTE/ns0:NUMERO_IDENTIFICACION">
            <tns:NUMERO_IDENTIFICACION_ASEGURADO>
               <xsl:value-of select="/ns0:EmisionMPH/ns0:CONTRATANTE/ns0:NUMERO_IDENTIFICACION"/>
            </tns:NUMERO_IDENTIFICACION_ASEGURADO>
         </xsl:if>
         <tns:VIVIENDA>
            <xsl:if test="/ns0:EmisionMPH/ns0:OBJETO_ASEGURADO/ns0:VIVIENDA/ns0:DESCRIPCION_UNIDAD">
               <tns:DESCRIPCION_UNIDAD>
                  <xsl:value-of select="/ns0:EmisionMPH/ns0:OBJETO_ASEGURADO/ns0:VIVIENDA/ns0:DESCRIPCION_UNIDAD"/>
               </tns:DESCRIPCION_UNIDAD>
            </xsl:if>
            
            <xsl:if test="/ns0:EmisionMPH/ns0:OBJETO_ASEGURADO/ns0:VIVIENDA/ns0:NIVEL_3">
               <tns:NIVEL_3>
                  <xsl:value-of select="/ns0:EmisionMPH/ns0:OBJETO_ASEGURADO/ns0:VIVIENDA/ns0:NIVEL_3"/>
               </tns:NIVEL_3>
            </xsl:if>
            <xsl:if test="/ns0:EmisionMPH/ns0:OBJETO_ASEGURADO/ns0:VIVIENDA/ns0:OCUPACION">
               <tns:OCUPACION>
                  <xsl:value-of select="/ns0:EmisionMPH/ns0:OBJETO_ASEGURADO/ns0:VIVIENDA/ns0:OCUPACION"/>
               </tns:OCUPACION>
            </xsl:if>
            <xsl:if test="/ns0:EmisionMPH/ns0:OBJETO_ASEGURADO/ns0:VIVIENDA/ns0:UBICACION_UNIDAD">
               <tns:UBICACION_UNIDAD>
                  <xsl:value-of select="/ns0:EmisionMPH/ns0:OBJETO_ASEGURADO/ns0:VIVIENDA/ns0:UBICACION_UNIDAD"/>
               </tns:UBICACION_UNIDAD>
            </xsl:if>
            <xsl:if test="/ns0:EmisionMPH/ns0:OBJETO_ASEGURADO/ns0:VIVIENDA/ns0:MEDIDAS_SEGURIDAD">
               <tns:MEDIDAS_SEGURIDAD>
                  <xsl:value-of select="/ns0:EmisionMPH/ns0:OBJETO_ASEGURADO/ns0:VIVIENDA/ns0:MEDIDAS_SEGURIDAD"/>
               </tns:MEDIDAS_SEGURIDAD>
            </xsl:if>
            <xsl:if test="/ns0:EmisionMPH/ns0:OBJETO_ASEGURADO/ns0:VIVIENDA/ns0:DURACION">
               <tns:DURACION>
                  <xsl:value-of select="/ns0:EmisionMPH/ns0:OBJETO_ASEGURADO/ns0:VIVIENDA/ns0:DURACION"/>
               </tns:DURACION>
            </xsl:if>
            <xsl:if test="/ns0:EmisionMPH/ns0:OBJETO_ASEGURADO/ns0:VIVIENDA/ns0:CONTENIDO">
               <tns:CONTENIDO>
                  <xsl:value-of select="/ns0:EmisionMPH/ns0:OBJETO_ASEGURADO/ns0:VIVIENDA/ns0:CONTENIDO"/>
               </tns:CONTENIDO>
            </xsl:if>
            <xsl:if test="/ns0:EmisionMPH/ns0:OBJETO_ASEGURADO/ns0:VIVIENDA/ns0:ESTRUCTURA">
               <tns:ESTRUCTURA>
                  <xsl:value-of select="/ns0:EmisionMPH/ns0:OBJETO_ASEGURADO/ns0:VIVIENDA/ns0:ESTRUCTURA"/>
               </tns:ESTRUCTURA>
            </xsl:if>
            <xsl:if test="/ns0:EmisionMPH/ns0:OBJETO_ASEGURADO/ns0:VIVIENDA/ns0:TIPO_CONSTRUCCION">
               <tns:TIPO_CONSTRUCCION>
                  <xsl:value-of select="/ns0:EmisionMPH/ns0:OBJETO_ASEGURADO/ns0:VIVIENDA/ns0:TIPO_CONSTRUCCION"/>
               </tns:TIPO_CONSTRUCCION>
            </xsl:if>
            <xsl:if test="/ns0:EmisionMPH/ns0:OBJETO_ASEGURADO/ns0:VIVIENDA/ns0:TIPO_OCUPACION">
               <tns:TIPO_OCUPACION>
                  <xsl:value-of select="/ns0:EmisionMPH/ns0:OBJETO_ASEGURADO/ns0:VIVIENDA/ns0:TIPO_OCUPACION"/>
               </tns:TIPO_OCUPACION>
            </xsl:if>
            <xsl:if test="/ns0:EmisionMPH/ns0:OBJETO_ASEGURADO/ns0:VIVIENDA/ns0:ACREEDOR">
               <tns:ACREEDOR>
                  <xsl:value-of select="/ns0:EmisionMPH/ns0:OBJETO_ASEGURADO/ns0:VIVIENDA/ns0:ACREEDOR"/>
               </tns:ACREEDOR>
            </xsl:if>
         </tns:VIVIENDA>
         <tns:ESTRUCTURA_COMERCIAL>
            <xsl:if test="/ns0:EmisionMPH/ns0:ESTRUCTURA_COMERCIAL/ns0:CODIGO_ESTRATEGIA">
               <tns:CODIGO_ESTRATEGIA>
                  <xsl:value-of select="/ns0:EmisionMPH/ns0:ESTRUCTURA_COMERCIAL/ns0:CODIGO_ESTRATEGIA"/>
               </tns:CODIGO_ESTRATEGIA>
            </xsl:if>
            <xsl:if test="/ns0:EmisionMPH/ns0:ESTRUCTURA_COMERCIAL/ns0:SECUENCIA_ASIGNACION">
               <tns:SECUENCIA_ASIGNACION>
                  <xsl:value-of select="/ns0:EmisionMPH/ns0:ESTRUCTURA_COMERCIAL/ns0:SECUENCIA_ASIGNACION"/>
               </tns:SECUENCIA_ASIGNACION>
            </xsl:if>
            <xsl:if test="/ns0:EmisionMPH/ns0:ESTRUCTURA_COMERCIAL/ns0:REFERENCIA">
               <tns:REFERENCIA>
                  <xsl:value-of select="/ns0:EmisionMPH/ns0:ESTRUCTURA_COMERCIAL/ns0:REFERENCIA"/>
               </tns:REFERENCIA>
            </xsl:if>
            <xsl:if test="/ns0:EmisionMPH/ns0:ESTRUCTURA_COMERCIAL/ns0:SUCURSAL">
               <tns:SUCURSAL>
                  <xsl:value-of select="/ns0:EmisionMPH/ns0:ESTRUCTURA_COMERCIAL/ns0:SUCURSAL"/>
               </tns:SUCURSAL>
            </xsl:if>
            <xsl:if test="/ns0:EmisionMPH/ns0:ESTRUCTURA_COMERCIAL/ns0:CODIGO_FUNCIONARIO">
               <tns:CODIGO_FUNCIONARIO>
                  <xsl:value-of select="/ns0:EmisionMPH/ns0:ESTRUCTURA_COMERCIAL/ns0:CODIGO_FUNCIONARIO"/>
               </tns:CODIGO_FUNCIONARIO>
            </xsl:if>
         </tns:ESTRUCTURA_COMERCIAL>
      </tns:OBJETO_POLIZA>
   </xsl:template>
</xsl:stylesheet>