<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/sp/sp_get_polizas_persona" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:tns="http://www.sura.com.pa/RsObtenerPolizasPersonas" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction"
                xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../Database/sp_get_polizas_persona_sp.xsd"/>
            <oracle-xsl-mapper:rootElement name="OutputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/sp_get_polizas_persona"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../nxsd/RsObtenerPolizasPersonas.xsd"/>
            <oracle-xsl-mapper:rootElement name="INFO_POLIZAS_PERSONAS" namespace="http://www.sura.com.pa/RsObtenerPolizasPersonas"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [MON DEC 28 22:29:03 COT 2020].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="codigoOperacion"/>
   <xsl:param name="fechaProcesamiento"/>
   <xsl:param name="fechaTransaccion"/>
   <xsl:param name="idTransaccion"/>
   <xsl:param name="sistemaDestino"/>
   <xsl:param name="sistemaOrigen"/>
   <xsl:param name="componente"/>
   <xsl:param name="origen"/>
   <xsl:template match="/">
      <tns:INFO_POLIZAS_PERSONAS>
         <tns:CABECERA>
            <xsl:if test="$fechaTransaccion">
               <tns:FECHA_TRANSACCION>
                  <xsl:value-of select="$fechaTransaccion"/>
               </tns:FECHA_TRANSACCION>
            </xsl:if>
            <xsl:if test="$sistemaDestino">
               <tns:SISTEMA_DESTINO>
                  <xsl:value-of select="$sistemaDestino"/>
               </tns:SISTEMA_DESTINO>
            </xsl:if>
            <xsl:if test="$sistemaOrigen">
               <tns:SISTEMA_ORIGEN>
                  <xsl:value-of select="$sistemaOrigen"/>
               </tns:SISTEMA_ORIGEN>
            </xsl:if>
            <xsl:if test="$idTransaccion">
               <tns:ID_TRANSACCION_OSB>
                  <xsl:value-of select="$idTransaccion"/>
               </tns:ID_TRANSACCION_OSB>
            </xsl:if>
            <xsl:if test="$fechaProcesamiento">
               <tns:FECHA_PROCESAMIENTO>
                  <xsl:value-of select="$fechaProcesamiento"/>
               </tns:FECHA_PROCESAMIENTO>
            </xsl:if>
            <xsl:if test="$codigoOperacion">
               <tns:CODIGO_OPERACION>
                  <xsl:value-of select="$codigoOperacion"/>
               </tns:CODIGO_OPERACION>
            </xsl:if>
            <tns:PAGINACION>
               <xsl:if test="/ns0:OutputParameters/ns0:totalPages">
                  <tns:CANTIDAD_DE_PAGINAS>
                     <xsl:value-of select="/ns0:OutputParameters/ns0:totalPages"/>
                  </tns:CANTIDAD_DE_PAGINAS>
               </xsl:if>
            </tns:PAGINACION>
         </tns:CABECERA>
         <tns:STATUS>
            <xsl:if test="/ns0:OutputParameters/ns0:statusMSG">
               <tns:CODIGO>200</tns:CODIGO>
            </xsl:if>
            <xsl:if test="$componente">
               <tns:COMPONENTE>
                  <xsl:value-of select="$componente"/>
               </tns:COMPONENTE>
            </xsl:if>
            <xsl:if test="/ns0:OutputParameters/ns0:descMSG">
               <tns:DETALLE>
                  <xsl:value-of select="/ns0:OutputParameters/ns0:descMSG"/>
               </tns:DETALLE>
            </xsl:if>
            <xsl:if test="$origen">
               <tns:ORIGEN>
                  <xsl:value-of select="$origen"/>
               </tns:ORIGEN>
            </xsl:if>
         </tns:STATUS>
         <xsl:for-each select="/ns0:OutputParameters/ns0:RowSet/ns0:Row">
            <tns:POLIZAS_PERSONAS>
               <xsl:if test="ns0:Column[@name='Cod_corredor']">
                  <tns:CODIGO_CORREDOR>
                     <xsl:value-of select="ns0:Column[@name='Cod_corredor']"/>
                  </tns:CODIGO_CORREDOR>
               </xsl:if>
               <xsl:if test="ns0:Column[@name='Pais']">
                  <tns:PAIS>
                     <xsl:value-of select="ns0:Column[@name='Pais']"/>
                  </tns:PAIS>
               </xsl:if>
               <tns:OBJETO_POLIZA>
                  <xsl:if test="ns0:Column[@name='Id_poliza']">
                     <tns:ID_POLIZA>
                        <xsl:value-of select="ns0:Column[@name='Id_poliza']"/>
                     </tns:ID_POLIZA>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Poliza_inicial']">
                     <tns:NUMERO_POLIZA_INICIAL>
                        <xsl:value-of select="ns0:Column[@name='Poliza_inicial']"/>
                     </tns:NUMERO_POLIZA_INICIAL>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Id_endoso']">
                     <tns:ID_ENDOSO>
                        <xsl:value-of select="ns0:Column[@name='Id_endoso']"/>
                     </tns:ID_ENDOSO>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Poliza_Secuencia']">
                     <tns:SECUENCIAL_POLIZA>
                        <xsl:value-of select="ns0:Column[@name='Poliza_Secuencia']"/>
                     </tns:SECUENCIAL_POLIZA>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Id_item_padre']">
                     <tns:ID_ITEM_PADRE>
                        <xsl:value-of select="ns0:Column[@name='Id_item_padre']"/>
                     </tns:ID_ITEM_PADRE>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Nro_certificado']">
                     <tns:NUMERO_CERTIFICADO>
                        <xsl:value-of select="ns0:Column[@name='Nro_certificado']"/>
                     </tns:NUMERO_CERTIFICADO>
                  </xsl:if>
               </tns:OBJETO_POLIZA>
               <tns:PERSONA_ASEGURADA>
                  <xsl:if test="ns0:Column[@name='Direccion']">
                     <tns:DIRECCION>
                        <xsl:value-of select="ns0:Column[@name='Direccion']"/>
                     </tns:DIRECCION>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Apellido']">
                     <tns:APELLIDO>
                        <xsl:value-of select="ns0:Column[@name='Apellido']"/>
                     </tns:APELLIDO>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Telefono1']">
                     <tns:TELEFONO_OFICINA>
                        <xsl:value-of select="ns0:Column[@name='Telefono1']"/>
                     </tns:TELEFONO_OFICINA>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Identificacion']">
                     <tns:NUMERO_IDENTIFICACION>
                        <xsl:value-of select="ns0:Column[@name='Identificacion']"/>
                     </tns:NUMERO_IDENTIFICACION>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Telefono2']">
                     <tns:TELEFONO>
                        <xsl:value-of select="ns0:Column[@name='Telefono2']"/>
                     </tns:TELEFONO>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Email']">
                     <tns:EMAIL>
                        <xsl:value-of select="ns0:Column[@name='Email']"/>
                     </tns:EMAIL>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Nombre']">
                     <tns:NOMBRE>
                        <xsl:value-of select="ns0:Column[@name='Nombre']"/>
                     </tns:NOMBRE>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Fecha_nacimiento']">
                     <tns:FECHA_NACIMIENTO>
                        <xsl:value-of select="ns0:Column[@name='Fecha_nacimiento']"/>
                     </tns:FECHA_NACIMIENTO>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Estado_civil']">
                     <tns:ESTADO_CIVIL>
                        <xsl:value-of select="ns0:Column[@name='Estado_civil']"/>
                     </tns:ESTADO_CIVIL>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Sexo']">
                     <tns:SEXO>
                        <xsl:value-of select="ns0:Column[@name='Sexo']"/>
                     </tns:SEXO>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Ocupacion']">
                     <tns:OCUPACION>
                        <xsl:value-of select="ns0:Column[@name='Ocupacion']"/>
                     </tns:OCUPACION>
                  </xsl:if>
               </tns:PERSONA_ASEGURADA>
               <tns:DETALLE_POLIZA>
                  <xsl:if test="ns0:Column[@name='Prima_bruta']">
                     <tns:PRIMA_BRUTA>
                        <xsl:value-of select="ns0:Column[@name='Prima_bruta']"/>
                     </tns:PRIMA_BRUTA>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Porc_impuesto']">
                     <tns:PORCENTAJE_IMPUESTO>
                        <xsl:value-of select="ns0:Column[@name='Porc_impuesto']"/>
                     </tns:PORCENTAJE_IMPUESTO>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Impuesto']">
                     <tns:IMPUESTO>
                        <xsl:value-of select="ns0:Column[@name='Impuesto']"/>
                     </tns:IMPUESTO>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Prima_neta']">
                     <tns:PRIMA_NETA>
                        <xsl:value-of select="ns0:Column[@name='Prima_neta']"/>
                     </tns:PRIMA_NETA>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Suma_asegurada']">
                     <tns:SUMA_ASEGURADA>
                        <xsl:value-of select="ns0:Column[@name='Suma_asegurada']"/>
                     </tns:SUMA_ASEGURADA>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Copago']">
                     <tns:COPAGO>
                        <xsl:value-of select="ns0:Column[@name='Copago']"/>
                     </tns:COPAGO>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Fecha_alta']">
                     <tns:FECHA_ALTA>
                        <xsl:value-of select="ns0:Column[@name='Fecha_alta']"/>
                     </tns:FECHA_ALTA>
                  </xsl:if>
               </tns:DETALLE_POLIZA>
            </tns:POLIZAS_PERSONAS>
         </xsl:for-each>
      </tns:INFO_POLIZAS_PERSONAS>
   </xsl:template>
</xsl:stylesheet>
