<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:ns0="http://xmlns.sura.com/MensajeIntegracion/DominioPago/PagoMI/V1" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/sp/dbReferenceInsis" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:dcomcom="http://xmlns.sura.com/ObjetoEmpresarial/DominioComun/Comun/V1" xmlns:dpagpag="http://xmlns.sura.com/ObjetoIntegracion/DominioPago/Pago/V1">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../../../ComponentesComunes/WSDL/xsd/DominioPago/Pago/V1/PagoMIV1.xsd"/>
            <oracle-xsl-mapper:rootElement name="ConfirmarPagoInsisMsjSol" namespace="http://xmlns.sura.com/MensajeIntegracion/DominioPago/PagoMI/V1"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../Databases/dbReferenceInsis_sp.xsd"/>
            <oracle-xsl-mapper:rootElement name="InputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/dbReferenceInsis"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [WED MAY 20 17:03:10 COT 2020].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:InputParameters>
         <xsl:if test="/ns0:ConfirmarPagoInsisMsjSol/ns0:Pago/dpagpag:InfoPolizaPago/dpagpag:NumeroPoliza">
            <tns:PI_POLICYID>
               <xsl:value-of select="/ns0:ConfirmarPagoInsisMsjSol/ns0:Pago/dpagpag:InfoPolizaPago/dpagpag:NumeroPoliza"/>
            </tns:PI_POLICYID>
         </xsl:if>
         <xsl:if test="/ns0:ConfirmarPagoInsisMsjSol/ns0:IdPagoInsis">
            <tns:PI_DOCPAYID>
               <xsl:value-of select="/ns0:ConfirmarPagoInsisMsjSol/ns0:IdPagoInsis"/>
            </tns:PI_DOCPAYID>
         </xsl:if>
         <xsl:if test="/ns0:ConfirmarPagoInsisMsjSol/ns0:Pago/dpagpag:UsuarioPago">
            <tns:PI_USERPAY>
               <xsl:value-of select="/ns0:ConfirmarPagoInsisMsjSol/ns0:Pago/dpagpag:UsuarioPago"/>
            </tns:PI_USERPAY>
         </xsl:if>
         <xsl:if test="/ns0:ConfirmarPagoInsisMsjSol/ns0:Pago/dpagpag:Sucursal">
            <tns:PI_BRANCHOFFICE>
               <xsl:value-of select="/ns0:ConfirmarPagoInsisMsjSol/ns0:Pago/dpagpag:Sucursal"/>
            </tns:PI_BRANCHOFFICE>
         </xsl:if>
         <xsl:if test="/ns0:ConfirmarPagoInsisMsjSol/ns0:CabeceraSol/dcomcom:SistemaOrigen">
            <tns:PI_APPPAY>
               <xsl:value-of select="/ns0:ConfirmarPagoInsisMsjSol/ns0:CabeceraSol/dcomcom:SistemaOrigen"/>
            </tns:PI_APPPAY>
         </xsl:if>
         <xsl:if test="/ns0:ConfirmarPagoInsisMsjSol/ns0:Pago/dpagpag:IdTransaccion">
            <tns:PI_REFERENCE>
               <xsl:value-of select="/ns0:ConfirmarPagoInsisMsjSol/ns0:Pago/dpagpag:IdTransaccion"/>
            </tns:PI_REFERENCE>
         </xsl:if>
      </tns:InputParameters>
   </xsl:template>
</xsl:stylesheet>