<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:tns="http://www.sura.com.pa/ObtenerMorosidad" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/sp/sp_get_morosidad" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction"
                xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../Database/sp_get_morosidad_sp.xsd"/>
            <oracle-xsl-mapper:rootElement name="OutputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/sp_get_morosidad"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../nxsd/RsObtenerMorosidad.xsd"/>
            <oracle-xsl-mapper:rootElement name="OBJETO_MOROSIDAD" namespace="http://www.sura.com.pa/ObtenerMorosidad"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [SUN NOV 15 21:35:52 COT 2020].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="codigoOperacion"/>
   <xsl:param name="fechaProcesamiento"/>
   <xsl:param name="fechaTransaccion"/>
   <xsl:param name="idTransaccion"/>
   <xsl:param name="sistemaDestino"/>
   <xsl:param name="sistemaOrigen"/>
   <xsl:param name="componente"/>
   <xsl:param name="origen"/>
   <xsl:template match="/">
      <tns:OBJETO_MOROSIDAD>
         <tns:CABECERA>
            <xsl:if test="$fechaTransaccion">
               <tns:FECHA_TRANSACCION>
                  <xsl:value-of select="$fechaTransaccion"/>
               </tns:FECHA_TRANSACCION>
            </xsl:if>
            <xsl:if test="$sistemaDestino">
               <tns:SISTEMA_DESTINO>
                  <xsl:value-of select="$sistemaDestino"/>
               </tns:SISTEMA_DESTINO>
            </xsl:if>
            <xsl:if test="$sistemaOrigen">
               <tns:SISTEMA_ORIGEN>
                  <xsl:value-of select="$sistemaOrigen"/>
               </tns:SISTEMA_ORIGEN>
            </xsl:if>
            <xsl:if test="$idTransaccion">
               <tns:ID_TRANSACCION_OSB>
                  <xsl:value-of select="$idTransaccion"/>
               </tns:ID_TRANSACCION_OSB>
            </xsl:if>
            <xsl:if test="$fechaProcesamiento">
               <tns:FECHA_PROCESAMIENTO>
                  <xsl:value-of select="$fechaProcesamiento"/>
               </tns:FECHA_PROCESAMIENTO>
            </xsl:if>
            <xsl:if test="$codigoOperacion">
               <tns:CODIGO_OPERACION>
                  <xsl:value-of select="$codigoOperacion"/>
               </tns:CODIGO_OPERACION>
            </xsl:if>
            <tns:PAGINACION>
               <xsl:if test="/ns0:OutputParameters/ns0:totalPages">
                  <tns:CANTIDAD_DE_PAGINAS>
                     <xsl:value-of select="/ns0:OutputParameters/ns0:totalPages"/>
                  </tns:CANTIDAD_DE_PAGINAS>
               </xsl:if>
            </tns:PAGINACION>
         </tns:CABECERA>
         <tns:STATUS>
            <xsl:if test="/ns0:OutputParameters/ns0:descMSG">
               <tns:DETALLE>
                  <xsl:value-of select="/ns0:OutputParameters/ns0:descMSG"/>
               </tns:DETALLE>
            </xsl:if>
            <xsl:choose>
               <xsl:when test="/ns0:OutputParameters/ns0:statusMSG = 1">
                  <tns:CODIGO>
                     <xsl:value-of select="200"/>
                  </tns:CODIGO>
               </xsl:when>
            </xsl:choose>
            <xsl:if test="$componente">
               <tns:COMPONENTE>
                  <xsl:value-of select="$componente"/>
               </tns:COMPONENTE>
            </xsl:if>
            <xsl:if test="$origen">
               <tns:ORIGEN>
                  <xsl:value-of select="$origen"/>
               </tns:ORIGEN>
            </xsl:if>
         </tns:STATUS>
         <xsl:for-each select="/ns0:OutputParameters/ns0:RowSet/ns0:Row">
            <tns:INFO_MOROSIDAD>
               <xsl:if test="ns0:Column[@name='Cod_corredor']">
                  <tns:COD_CORREDOR>
                     <xsl:value-of select="ns0:Column[@name='Cod_corredor']"/>
                  </tns:COD_CORREDOR>
               </xsl:if>
               <xsl:if test="ns0:Column[@name='Prima_suscrita']">
                  <tns:PRIMA_SUSCRITA>
                     <xsl:value-of select="ns0:Column[@name='Prima_suscrita']"/>
                  </tns:PRIMA_SUSCRITA>
               </xsl:if>
               <xsl:if test="ns0:Column[@name='Cobrado']">
                  <tns:COBRADO>
                     <xsl:value-of select="ns0:Column[@name='Cobrado']"/>
                  </tns:COBRADO>
               </xsl:if>
               <xsl:if test="ns0:Column[@name='Saldo']">
                  <tns:SALDO>
                     <xsl:value-of select="ns0:Column[@name='Saldo']"/>
                  </tns:SALDO>
               </xsl:if>
               <xsl:if test="ns0:Column[@name='Saldo_30_dias']">
                  <tns:SALDO_30>
                     <xsl:value-of select="ns0:Column[@name='Saldo_30_dias']"/>
                  </tns:SALDO_30>
               </xsl:if>
               <xsl:if test="ns0:Column[@name='Saldo_60_dias']">
                  <tns:SALDO_60>
                     <xsl:value-of select="ns0:Column[@name='Saldo_60_dias']"/>
                  </tns:SALDO_60>
               </xsl:if>
               <xsl:if test="ns0:Column[@name='Saldo_90_dias']">
                  <tns:SALDO_90>
                     <xsl:value-of select="ns0:Column[@name='Saldo_90_dias']"/>
                  </tns:SALDO_90>
               </xsl:if>
               <xsl:if test="ns0:Column[@name='Saldo_120_dias']">
                  <tns:SALDO_120>
                     <xsl:value-of select="ns0:Column[@name='Saldo_120_dias']"/>
                  </tns:SALDO_120>
               </xsl:if>
               <xsl:if test="ns0:Column[@name='Saldo_mas_120_dias']">
                  <tns:SALDO_MAS_120>
                     <xsl:value-of select="ns0:Column[@name='Saldo_mas_120_dias']"/>
                  </tns:SALDO_MAS_120>
               </xsl:if>
               <tns:OBJETO_POLIZA>
                  <xsl:if test="ns0:Column[@name='Cod_ramo']">
                     <tns:COD_RAMO>
                        <xsl:value-of select="ns0:Column[@name='Cod_ramo']"/>
                     </tns:COD_RAMO>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Ramo']">
                     <tns:DESC_RAMO>
                        <xsl:value-of select="ns0:Column[@name='Ramo']"/>
                     </tns:DESC_RAMO>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Nro_poliza']">
                     <tns:NUMERO_POLIZA>
                        <xsl:value-of select="ns0:Column[@name='Nro_poliza']"/>
                     </tns:NUMERO_POLIZA>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Fecha_desde']">
                     <tns:VIGENCIA_DESDE>
                        <xsl:value-of select="ns0:Column[@name='Fecha_desde']"/>
                     </tns:VIGENCIA_DESDE>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Fecha_Hasta']">
                     <tns:VIGENCIA_HASTA>
                        <xsl:value-of select="ns0:Column[@name='Fecha_Hasta']"/>
                     </tns:VIGENCIA_HASTA>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Id_poliza']">
                     <tns:ID_POLIZA>
                        <xsl:value-of select="ns0:Column[@name='Id_poliza']"/>
                     </tns:ID_POLIZA>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Poliza_inicial']">
                     <tns:NUMERO_POLIZA_INICIAL>
                        <xsl:value-of select="ns0:Column[@name='Poliza_inicial']"/>
                     </tns:NUMERO_POLIZA_INICIAL>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Poliza_secuencia']">
                     <tns:SECUENCIAL_POLIZA>
                        <xsl:value-of select="ns0:Column[@name='Poliza_secuencia']"/>
                     </tns:SECUENCIAL_POLIZA>
                  </xsl:if>
               </tns:OBJETO_POLIZA>
               <tns:CONTRATANTE>
                  <xsl:if test="ns0:Column[@name='Id_cont']">
                     <tns:ID_CONTRATANTE>
                        <xsl:value-of select="ns0:Column[@name='Id_cont']"/>
                     </tns:ID_CONTRATANTE>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Nombre_cont']">
                     <tns:NOMBRE>
                        <xsl:value-of select="ns0:Column[@name='Nombre_cont']"/>
                     </tns:NOMBRE>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Apellido_cont']">
                     <tns:APELLIDO>
                        <xsl:value-of select="ns0:Column[@name='Apellido_cont']"/>
                     </tns:APELLIDO>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Razon_social_cont']">
                     <tns:RAZON_SOCIAL>
                        <xsl:value-of select="ns0:Column[@name='Razon_social_cont']"/>
                     </tns:RAZON_SOCIAL>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Id_tipo_persona_cont']">
                     <tns:TIPO_PERSONA>
                        <xsl:value-of select="ns0:Column[@name='Id_tipo_persona_cont']"/>
                     </tns:TIPO_PERSONA>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Identificacion_cont']">
                     <tns:NUMERO_IDENTIFICACION>
                        <xsl:value-of select="ns0:Column[@name='Identificacion_cont']"/>
                     </tns:NUMERO_IDENTIFICACION>
                  </xsl:if>
               </tns:CONTRATANTE>
               <tns:PERSONA_ASEGURADA>
                  <xsl:if test="ns0:Column[@name='Id_aseg']">
                     <tns:ID_ASEGURADO>
                        <xsl:value-of select="ns0:Column[@name='Id_aseg']"/>
                     </tns:ID_ASEGURADO>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Razon_social_aseg']">
                     <tns:RAZON_SOCIAL_ASEGURADO>
                        <xsl:value-of select="ns0:Column[@name='Razon_social_aseg']"/>
                     </tns:RAZON_SOCIAL_ASEGURADO>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Id_tipo_persona_aseg']">
                     <tns:ID_TIPO_PERSONA>
                        <xsl:value-of select="ns0:Column[@name='Id_tipo_persona_aseg']"/>
                     </tns:ID_TIPO_PERSONA>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Nombre_aseg']">
                     <tns:NOMBRE>
                        <xsl:value-of select="ns0:Column[@name='Nombre_aseg']"/>
                     </tns:NOMBRE>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Apellido_aseg']">
                     <tns:APELLIDO>
                        <xsl:value-of select="ns0:Column[@name='Apellido_aseg']"/>
                     </tns:APELLIDO>
                  </xsl:if>
                  <xsl:if test="ns0:Column[@name='Identificacion_aseg']">
                     <tns:NUMERO_IDENTIFICACION>
                        <xsl:value-of select="ns0:Column[@name='Identificacion_aseg']"/>
                     </tns:NUMERO_IDENTIFICACION>
                  </xsl:if>
               </tns:PERSONA_ASEGURADA>
            </tns:INFO_MOROSIDAD>
         </xsl:for-each>
      </tns:OBJETO_MOROSIDAD>
   </xsl:template>
</xsl:stylesheet>
