<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:tns="http://TargetNamespace.com/registrarPagoBitacora" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction"
                xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source/>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../XSD/registrarPagoBitacora.xsd"/>
            <oracle-xsl-mapper:rootElement name="RqRegistrarPagoBitacora" namespace="http://TargetNamespace.com/registrarPagoBitacora"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [WED AUG 04 22:06:34 COT 2021].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="idRecibo"/>
   <xsl:param name="estadoPago"/>
   <xsl:param name="monto"/>
   <xsl:param name="fecha"/>
   <xsl:param name="identificacion"/>
   <xsl:param name="numeroPoliza"/>
   <xsl:param name="respuestaAplicaP"/>
   <xsl:param name="core"/>
   <xsl:param name="fechaTransaccion"/>
   <xsl:param name="codigoOperacion"/>
   <xsl:param name="idTransaccionOSB"/>
   <xsl:param name="sistemaOrigen"/>
   <xsl:param name="sistemaDestino"/>
   <xsl:template match="/">
      <tns:RqRegistrarPagoBitacora>
         <tns:CABECERA>
            <tns:CODIGO_OPERACION>
               <xsl:value-of select="$codigoOperacion"/>
            </tns:CODIGO_OPERACION>
            <tns:FECHA_TRANSACCION>
               <xsl:value-of select="$fechaTransaccion"/>
            </tns:FECHA_TRANSACCION>
            <tns:ID_TRANSACCION_OSB>
               <xsl:value-of select="$idTransaccionOSB"/>
            </tns:ID_TRANSACCION_OSB>
            <tns:SISTEMA_DESTINO>
               <xsl:value-of select="$sistemaDestino"/>
            </tns:SISTEMA_DESTINO>
            <tns:SISTEMA_ORIGEN>
               <xsl:value-of select="$sistemaOrigen"/>
            </tns:SISTEMA_ORIGEN>
         </tns:CABECERA>
         <tns:ID_RECIBO>
            <xsl:value-of select="$idRecibo"/>
         </tns:ID_RECIBO>
         <tns:ESTADO_PAGO>
            <xsl:value-of select="$estadoPago"/>
         </tns:ESTADO_PAGO>
         <tns:MONTO>
            <xsl:value-of select="$monto"/>
         </tns:MONTO>
         <tns:FECHA>
            <xsl:value-of select="$fecha"/>
         </tns:FECHA>
         <tns:IDENTIFICACION>
            <xsl:value-of select="$identificacion"/>
         </tns:IDENTIFICACION>
         <tns:NUMERO_POLIZA>
            <xsl:value-of select="$numeroPoliza"/>
         </tns:NUMERO_POLIZA>
         <tns:RESPUESTA_APLICAP>
            <xsl:value-of select="$respuestaAplicaP"/>
         </tns:RESPUESTA_APLICAP>
         <tns:CORE>
            <xsl:value-of select="$core"/>
         </tns:CORE>
      </tns:RqRegistrarPagoBitacora>
   </xsl:template>
</xsl:stylesheet>
