<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:ns0="http://xmlns.sura.com/MensajeIntegracion/DominioUtilitario/GestionDocumentalMI/V1" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/sp/dbReferenceInsis" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction"
                xmlns:dpropro="http://xmlns.sura.com/ObjetoIntegracion/DominioProceso/Proceso/V1"
                xmlns:dutigdoc="http://xmlns.sura.com/ObjetoIntegracion/DominioUtilitario/GestionDocumental/V1"
                xmlns:dcomcom="http://xmlns.sura.com/ObjetoEmpresarial/DominioComun/Comun/V1">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../../../ComponentesComunes/WSDL/xsd/DominioUtilitario/GestionDocumental/V1/GestionDocumentalMIV1.xsd"/>
            <oracle-xsl-mapper:rootElement name="GestionarParametrosECMInsisMsjSol" namespace="http://xmlns.sura.com/MensajeIntegracion/DominioUtilitario/GestionDocumentalMI/V1"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../Database/dbReferenceInsis_sp.xsd"/>
            <oracle-xsl-mapper:rootElement name="InputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/dbReferenceInsis"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [SAT MAY 02 15:38:44 COT 2020].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:InputParameters>
         <tns:PI_OPERID>
            <xsl:value-of select="/ns0:GestionarParametrosECMInsisMsjSol/ns0:TipoOperacion"/>
         </tns:PI_OPERID>
         <xsl:if test="/ns0:GestionarParametrosECMInsisMsjSol/ns0:Documento/dutigdoc:IdDocumentoINSIS">
            <tns:PI_IDINSIS>
               <xsl:value-of select="/ns0:GestionarParametrosECMInsisMsjSol/ns0:Documento/dutigdoc:IdDocumentoINSIS"/>
            </tns:PI_IDINSIS>
         </xsl:if>
         <xsl:if test="/ns0:GestionarParametrosECMInsisMsjSol/ns0:Documento/dutigdoc:TipoDocumento/dcomcom:Codigo">
            <tns:PI_TIPODOC>
               <xsl:value-of select="/ns0:GestionarParametrosECMInsisMsjSol/ns0:Documento/dutigdoc:TipoDocumento/dcomcom:Codigo"/>
            </tns:PI_TIPODOC>
         </xsl:if>
         <xsl:if test="/ns0:GestionarParametrosECMInsisMsjSol/ns0:Documento/dutigdoc:Extension">
            <tns:PI_EXTDOC>
               <xsl:value-of select="/ns0:GestionarParametrosECMInsisMsjSol/ns0:Documento/dutigdoc:Extension"/>
            </tns:PI_EXTDOC>
         </xsl:if>
         <xsl:if test="/ns0:GestionarParametrosECMInsisMsjSol/ns0:Documento/dutigdoc:IdDocumentoECM">
            <tns:PI_IDECM>
               <xsl:value-of select="/ns0:GestionarParametrosECMInsisMsjSol/ns0:Documento/dutigdoc:IdDocumentoECM"/>
            </tns:PI_IDECM>
         </xsl:if>
         <xsl:if test="/ns0:GestionarParametrosECMInsisMsjSol/ns0:Documento/dutigdoc:FechaCreacion">
            <tns:PI_DOCDATECR>
               <xsl:value-of select="/ns0:GestionarParametrosECMInsisMsjSol/ns0:Documento/dutigdoc:FechaCreacion"/>
            </tns:PI_DOCDATECR>
         </xsl:if>
         <xsl:if test="/ns0:GestionarParametrosECMInsisMsjSol/ns0:Documento/dutigdoc:EstadoDocumento">
            <tns:PI_DOCSTATE>
               <xsl:value-of select="/ns0:GestionarParametrosECMInsisMsjSol/ns0:Documento/dutigdoc:EstadoDocumento"/>
            </tns:PI_DOCSTATE>
         </xsl:if>
         <xsl:if test="/ns0:GestionarParametrosECMInsisMsjSol/ns0:Documento/dutigdoc:Comentario">
            <tns:PI_DOCNOTES>
               <xsl:value-of select="/ns0:GestionarParametrosECMInsisMsjSol/ns0:Documento/dutigdoc:Comentario"/>
            </tns:PI_DOCNOTES>
         </xsl:if>
      </tns:InputParameters>
   </xsl:template>
</xsl:stylesheet>
