<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:ns0="http://sura.com.pa/GestionarActividadDocumento/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction"
                xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd"
                xmlns:ns1="http://www.sura.com.pa/GestionarActividadDocumento">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../nxsd/RqExpGestionarActividadDocumento.xsd"/>
            <oracle-xsl-mapper:rootElement name="GestionarActividadDocumentoReq" namespace="http://sura.com.pa/GestionarActividadDocumento/"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../nxsd/RqExpGestionarActividadDocumento.xsd"/>
            <oracle-xsl-mapper:rootElement name="GestionarActividadDocumentoReq" namespace="http://sura.com.pa/GestionarActividadDocumento/"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [MON NOV 01 11:13:20 COT 2021].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="idTransaccionOsb"/>
   <xsl:param name="codigoOperacion"/>
   <xsl:template match="/">
      <ns0:GestionarActividadDocumentoReq>
         <ns0:CABECERA>
            <ns0:FECHA_TRANSACCION>
               <xsl:value-of select="/ns0:GestionarActividadDocumentoReq/ns0:CABECERA/ns0:FECHA_TRANSACCION"/>
            </ns0:FECHA_TRANSACCION>
            <ns0:FECHA_PROCESAMIENTO>
               <xsl:value-of select="/ns0:GestionarActividadDocumentoReq/ns0:CABECERA/ns0:FECHA_PROCESAMIENTO"/>
            </ns0:FECHA_PROCESAMIENTO>
            <ns0:SISTEMA_DESTINO>
               <xsl:value-of select="/ns0:GestionarActividadDocumentoReq/ns0:CABECERA/ns0:SISTEMA_DESTINO"/>
            </ns0:SISTEMA_DESTINO>
            <ns0:ID_TRANSACCION_OSB>
               <xsl:value-of select="$idTransaccionOsb"/>
            </ns0:ID_TRANSACCION_OSB>
            <ns0:SISTEMA_ORIGEN>
               <xsl:value-of select="/ns0:GestionarActividadDocumentoReq/ns0:CABECERA/ns0:SISTEMA_ORIGEN"/>
            </ns0:SISTEMA_ORIGEN>
            <ns0:CODIGO_OPERACION>
               <xsl:value-of select="$codigoOperacion"/>
            </ns0:CODIGO_OPERACION>
         </ns0:CABECERA>
         <ns0:TipoReferencia>
            <xsl:value-of select="/ns0:GestionarActividadDocumentoReq/ns0:TipoReferencia"/>
         </ns0:TipoReferencia>
         <ns0:IdProceso>
            <xsl:value-of select="/ns0:GestionarActividadDocumentoReq/ns0:IdProceso"/>
         </ns0:IdProceso>
         <ns0:IdPlantillaActividad>
            <xsl:value-of select="/ns0:GestionarActividadDocumentoReq/ns0:IdPlantillaActividad"/>
         </ns0:IdPlantillaActividad>
         <ns0:IdUsuario>
            <xsl:value-of select="/ns0:GestionarActividadDocumentoReq/ns0:IdUsuario"/>
         </ns0:IdUsuario>
         <ns0:ParametrosActividad>
            <xsl:for-each select="/ns0:GestionarActividadDocumentoReq/ns0:ParametrosActividad/ns0:Parametro">
               <ns0:Parametro>
                  <ns0:Nombre>
                     <xsl:value-of select="ns0:Nombre"/>
                  </ns0:Nombre>
                  <ns0:Valor>
                     <xsl:value-of select="ns0:Valor"/>
                  </ns0:Valor>
               </ns0:Parametro>
            </xsl:for-each>
         </ns0:ParametrosActividad>
         <ns0:Documentos>
            <xsl:for-each select="/ns0:GestionarActividadDocumentoReq/ns0:Documentos/ns0:Documento">
               <ns0:Documento>
                  <ns0:IdDocumental>
                     <xsl:value-of select="ns0:IdDocumental"/>
                  </ns0:IdDocumental>
                  <xsl:for-each select="ns0:Adjunto">
                     <ns0:Adjunto>
                        <ns0:Contenido>
                           <xsl:value-of select="ns0:Contenido"/>
                        </ns0:Contenido>
                        <ns0:IdFormato>
                           <xsl:value-of select="ns0:IdFormato"/>
                        </ns0:IdFormato>
                     </ns0:Adjunto>
                  </xsl:for-each>
                  <ns0:AtributosRelacion>
                     <xsl:for-each select="ns0:AtributosRelacion/ns0:Atributo">
                        <ns0:Atributo>
                           <ns0:Nombre>
                              <xsl:value-of select="ns0:Nombre"/>
                           </ns0:Nombre>
                           <ns0:Valor>
                              <xsl:value-of select="ns0:Valor"/>
                           </ns0:Valor>
                           <ns0:Id>
                              <xsl:value-of select="ns0:Id"/>
                           </ns0:Id>
                        </ns0:Atributo>
                     </xsl:for-each>
                  </ns0:AtributosRelacion>
               </ns0:Documento>
            </xsl:for-each>
         </ns0:Documentos>
      </ns0:GestionarActividadDocumentoReq>
   </xsl:template>
</xsl:stylesheet>
