<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/sp/dbInsis" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:tns="http://www.sura.com/MensajeIntegracion/DominioPoliza/PolizaMIN/V1" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction"
                xmlns:dcomcom="http://xmlns.sura.com/ObjetoEmpresarial/DominioComun/Comun/V1"
                xmlns:dutidoc="http://xmlns.sura.com/ObjetoIntegracion/DominioUtilitario/GestionDocumental/V1">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../Database/dbInsis_sp.xsd"/>
            <oracle-xsl-mapper:rootElement name="OutputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/dbInsis"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../../../ComponentesComunes/WSDL/xsd/DominioPoliza/Poliza/V1/PolizaMINV1.xsd"/>
            <oracle-xsl-mapper:rootElement name="ConsultarDocumentoInsisMsjResp" namespace="http://www.sura.com/MensajeIntegracion/DominioPoliza/PolizaMIN/V1"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [SUN MAY 31 16:10:56 COT 2020].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:ConsultarDocumentoInsisMsjResp>
         <tns:CabeceraResp>
            <dcomcom:EstadoGeneral>
               <dcomcom:Status>
                  <xsl:value-of select="/ns0:OutputParameters/ns0:PO_MSG_STATUS"/>
               </dcomcom:Status>
               <dcomcom:Descripcion>
                  <xsl:value-of select="/ns0:OutputParameters/ns0:PO_MSG_ERROR"/>
               </dcomcom:Descripcion>
            </dcomcom:EstadoGeneral>
         </tns:CabeceraResp>
         <xsl:if test="/ns0:OutputParameters/ns0:PO_XML">
            <tns:Contenido>
               <xsl:value-of select="/ns0:OutputParameters/ns0:PO_XML"/>
            </tns:Contenido>
         </xsl:if>
         <xsl:if test="/ns0:OutputParameters/ns0:PO_PROCID">
            <tns:IdPlantillaDoc>
               <xsl:value-of select="/ns0:OutputParameters/ns0:PO_PROCID"/>
            </tns:IdPlantillaDoc>
         </xsl:if>
         <xsl:if test="/ns0:OutputParameters/ns0:PO_DOCNAME">
            <tns:NombreDocumento>
               <xsl:value-of select="/ns0:OutputParameters/ns0:PO_DOCNAME"/>
            </tns:NombreDocumento>
         </xsl:if>
         <xsl:if test="/ns0:OutputParameters/ns0:PO_CORRELATIONID">
            <tns:IdCorrelation>
               <xsl:value-of select="/ns0:OutputParameters/ns0:PO_CORRELATIONID"/>
            </tns:IdCorrelation>
         </xsl:if>
         <xsl:if test="/ns0:OutputParameters/ns0:PO_ROUTINKEY">
            <tns:RoutingKey>
               <xsl:value-of select="/ns0:OutputParameters/ns0:PO_ROUTINKEY"/>
            </tns:RoutingKey>
         </xsl:if>
         <xsl:if test="/ns0:OutputParameters/ns0:PO_ACTION">
            <tns:Accion>
               <xsl:value-of select="/ns0:OutputParameters/ns0:PO_ACTION"/>
            </tns:Accion>
         </xsl:if>
         <xsl:if test="/ns0:OutputParameters/ns0:PO_IDCOMMUNICATION">
            <tns:IdComunicacion>
               <xsl:value-of select="/ns0:OutputParameters/ns0:PO_IDCOMMUNICATION"/>
            </tns:IdComunicacion>
         </xsl:if>
      </tns:ConsultarDocumentoInsisMsjResp>
   </xsl:template>
</xsl:stylesheet>
