<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:tns="http://TargetNamespace.com/consultarPolizaDano" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction"
                xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source/>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../XSD/consultarPolizaDano.xsd"/>
            <oracle-xsl-mapper:rootElement name="PolizaDano" namespace="http://TargetNamespace.com/consultarPolizaDano"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [THU DEC 10 13:22:57 COT 2020].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="tipoBusqueda"/>
   <xsl:param name="valor"/>
   <xsl:param name="fechaTransaccion"/>
   <xsl:param name="codigoOperacion"/>
   <xsl:param name="idTransaccionOSB"/>
   <xsl:param name="sistemaOrigen"/>
   <xsl:param name="sistemaDestino"/>
   <xsl:template match="/">
      <tns:PolizaDano>
         <tns:CABECERA>
            <tns:CODIGO_OPERACION>
               <xsl:value-of select="$codigoOperacion"/>
            </tns:CODIGO_OPERACION>
            <tns:FECHA_TRANSACCION>
               <xsl:value-of select="$fechaTransaccion"/>
            </tns:FECHA_TRANSACCION>
            <tns:ID_TRANSACCION_OSB>
               <xsl:value-of select="$idTransaccionOSB"/>
            </tns:ID_TRANSACCION_OSB>
            <tns:SISTEMA_DESTINO>
               <xsl:value-of select="$sistemaDestino"/>
            </tns:SISTEMA_DESTINO>
            <tns:SISTEMA_ORIGEN>
               <xsl:value-of select="$sistemaOrigen"/>
            </tns:SISTEMA_ORIGEN>
         </tns:CABECERA>
         <tns:TIPO_BUSQUEDA>
            <xsl:value-of select="$tipoBusqueda"/>
         </tns:TIPO_BUSQUEDA>
         <tns:VALOR>
            <xsl:value-of select="$valor"/>
         </tns:VALOR>
      </tns:PolizaDano>
   </xsl:template>
</xsl:stylesheet>
