<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:ns0="http://www.sura.com.pa/RqCrearActividadBPM" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:tns="http://xmlns.sura.com/MensajeIntegracion/DominioProceso/BPMMI/V1" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction"
                xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd"
                xmlns:dpropro="http://www.sura.com/ObjetoEmpresarial/DominioProceso/Proceso/V1"
                xmlns:dcomcom="http://xmlns.sura.com/ObjetoEmpresarial/DominioComun/Comun/V1">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../nsxd/RqCrearActividadBPMNxsd.xsd"/>
            <oracle-xsl-mapper:rootElement name="OBJ_BPM" namespace="http://www.sura.com.pa/RqCrearActividadBPM"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../../../ComponentesComunes/WSDL/xsd/DominioProceso/BPM/V1/ProcesoMIV1.xsd"/>
            <oracle-xsl-mapper:rootElement name="CrearActividadBPMMsjSol" namespace="http://xmlns.sura.com/MensajeIntegracion/DominioProceso/BPMMI/V1"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [FRI OCT 22 16:32:49 COT 2021].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="codigoOperacion"/>
   <xsl:param name="fechaTransaccion"/>
   <xsl:param name="idTransaccionOSB"/>
   <xsl:template match="/">
      <tns:CrearActividadBPMMsjSol>
         <tns:CabeceraSol>
            <dcomcom:CodigoOperacion>
               <xsl:value-of select="/ns0:OBJ_BPM/ns0:CABECERA/ns0:CODIGO_OPERACION"/>
            </dcomcom:CodigoOperacion>
            <xsl:if test="/ns0:OBJ_BPM/ns0:CABECERA/ns0:FECHA_PROCESAMIENTO">
               <dcomcom:FechaProcesamiento>
                  <xsl:value-of select="/ns0:OBJ_BPM/ns0:CABECERA/ns0:FECHA_PROCESAMIENTO"/>
               </dcomcom:FechaProcesamiento>
            </xsl:if>
            <dcomcom:FechaTransaccion>
               <xsl:value-of select="/ns0:OBJ_BPM/ns0:CABECERA/ns0:FECHA_TRANSACCION"/>
            </dcomcom:FechaTransaccion>
            <dcomcom:IdTransaccionOsb>
               <xsl:value-of select="$idTransaccionOSB"/>
            </dcomcom:IdTransaccionOsb>
            <dcomcom:SistemaDestino>
               <xsl:value-of select="/ns0:OBJ_BPM/ns0:CABECERA/ns0:SISTEMA_DESTINO"/>
            </dcomcom:SistemaDestino>
            <dcomcom:SistemaOrigen>
               <xsl:value-of select="/ns0:OBJ_BPM/ns0:CABECERA/ns0:SISTEMA_ORIGEN"/>
            </dcomcom:SistemaOrigen>
         </tns:CabeceraSol>
         <xsl:if test="/ns0:OBJ_BPM/ns0:TipoActividad">
            <tns:TipoActividad>
               <xsl:value-of select="/ns0:OBJ_BPM/ns0:TipoActividad"/>
            </tns:TipoActividad>
         </xsl:if>
         <xsl:if test="/ns0:OBJ_BPM/ns0:AsuntoActividad">
            <tns:AsuntoActividad>
               <xsl:value-of select="/ns0:OBJ_BPM/ns0:AsuntoActividad"/>
            </tns:AsuntoActividad>
         </xsl:if>
         <xsl:if test="/ns0:OBJ_BPM/ns0:IdUsuario">
            <tns:IdUsuario>
               <xsl:value-of select="/ns0:OBJ_BPM/ns0:IdUsuario"/>
            </tns:IdUsuario>
         </xsl:if>
         <xsl:if test="/ns0:OBJ_BPM/ns0:IdProceso">
            <tns:IdProceso>
               <xsl:value-of select="/ns0:OBJ_BPM/ns0:IdProceso"/>
            </tns:IdProceso>
         </xsl:if>
         <xsl:if test="/ns0:OBJ_BPM/ns0:IdPersona">
            <tns:IdPersona>
               <xsl:value-of select="/ns0:OBJ_BPM/ns0:IdPersona"/>
            </tns:IdPersona>
         </xsl:if>
         <xsl:if test="/ns0:OBJ_BPM/ns0:NumPoliza">
            <tns:NumPoliza>
               <xsl:value-of select="/ns0:OBJ_BPM/ns0:NumPoliza"/>
            </tns:NumPoliza>
         </xsl:if>
         <xsl:if test="/ns0:OBJ_BPM/ns0:TipoReferencia">
            <tns:TipoReferencia>
               <xsl:value-of select="/ns0:OBJ_BPM/ns0:TipoReferencia"/>
            </tns:TipoReferencia>
         </xsl:if>
         <xsl:if test="/ns0:OBJ_BPM/ns0:NumReferencia">
            <tns:NumReferencia>
               <xsl:value-of select="/ns0:OBJ_BPM/ns0:NumReferencia"/>
            </tns:NumReferencia>
         </xsl:if>
         <xsl:if test="/ns0:OBJ_BPM/ns0:IdPlantillaActividad">
            <tns:IdPlantillaActividad>
               <xsl:value-of select="/ns0:OBJ_BPM/ns0:IdPlantillaActividad"/>
            </tns:IdPlantillaActividad>
         </xsl:if>
         <tns:ParametrosActividad>
            <xsl:for-each select="/ns0:OBJ_BPM/ns0:ParametrosActividad/ns0:Parametro">
               <dcomcom:ParametroActividad Elemento="{ns0:Nombre}">
                  <dcomcom:Valor>
                     <xsl:value-of select="ns0:Valor"/>
                  </dcomcom:Valor>
               </dcomcom:ParametroActividad>
            </xsl:for-each>
         </tns:ParametrosActividad>
      </tns:CrearActividadBPMMsjSol>
   </xsl:template>
</xsl:stylesheet>
