<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/sp/sp_consultar_polizas_x_proceso" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:tns="http://www.sura.com.pa/RqCrearVoucher" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/ServiciosIntegracionSURA/Bpel_Gestionar_Voucher/sp_consultar_polizas_x_proceso"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ns2="http://www.sura.com.pa/Exp_RqCrearVoucher" xmlns:ns3="http://www.sura.com.pa/RsCrearVoucher"
                xmlns:ns4="http://www.sura.com.pa/ObjectResponse"
                xmlns:ns5="http://TargetNamespace.com/EnviarAuditoria"
                xmlns:ns6="http://www.sura.com.pa/GestionarTransaccionPremium">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/sp_consultar_polizas_x_proceso.wsdl"/>
            <oracle-xsl-mapper:rootElement name="OutputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/sp_consultar_polizas_x_proceso"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/sp_consultar_polizas_x_proceso.wsdl"/>
            <oracle-xsl-mapper:rootElement name="OBJETO_VOUCHER" namespace="http://www.sura.com.pa/RqCrearVoucher"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [WED DEC 23 12:46:07 COT 2020].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:OBJETO_VOUCHER>
         <xsl:for-each select="/ns0:OutputParameters/ns0:RFC_POLIZAS/ns0:Row">
            <tns:VOUCHER>
               <xsl:if test="ns0:Column[@name='FECHA_ACTIVACION']">
                  <tns:ACTIVATION_DATE>
                     <xsl:value-of select="ns0:Column[@name='FECHA_ACTIVACION']"/>
                  </tns:ACTIVATION_DATE>
               </xsl:if>
               <xsl:if test="ns0:Column[@name='ID_AGENTE']">
                  <tns:AGENT_ID>
                     <xsl:value-of select="ns0:Column[@name='ID_AGENTE']"/>
                  </tns:AGENT_ID>
               </xsl:if>
               <xsl:if test="ns0:Column[@name='ANO_AUTOMOVIL']">
                  <tns:ANIO>
                     <xsl:value-of select="ns0:Column[@name='ANO_AUTOMOVIL']"/>
                  </tns:ANIO>
               </xsl:if>
               <xsl:if test="ns0:Column[@name='APELLIDO_ASEGURADO']">
                  <tns:APELLIDO>
                     <xsl:value-of select="ns0:Column[@name='APELLIDO_ASEGURADO']"/>
                  </tns:APELLIDO>
               </xsl:if>
               <xsl:if test="ns0:Column[@name='FECHA_ASIGNACION']">
                  <tns:ASSOCIATION_DATE>
                     <xsl:value-of select="ns0:Column[@name='FECHA_ASIGNACION']"/>
                  </tns:ASSOCIATION_DATE>
               </xsl:if>
               <xsl:if test="ns0:Column[@name='TAFIRA_BASE']">
                  <tns:BASE_RATE>
                     <xsl:value-of select="ns0:Column[@name='TARIFA_BASE']"/>
                  </tns:BASE_RATE>
               </xsl:if>
               <xsl:if test="ns0:Column[@name='CICLO_FACTURACION']">
                  <tns:BILLING_CYCLE>
                     <xsl:value-of select="ns0:Column[@name='CICLO_FACTURACION']"/>
                  </tns:BILLING_CYCLE>
               </xsl:if>
               <xsl:if test="ns0:Column[@name='CANAL']">
                  <tns:CHANNEL>
                     <xsl:value-of select="ns0:Column[@name='CANAL']"/>
                  </tns:CHANNEL>
               </xsl:if>
               <xsl:if test="ns0:Column[@name='CHASIS_AUTOMOVIL']">
                  <tns:CHASIS>
                     <xsl:value-of select="ns0:Column[@name='CHASIS_AUTOMOVIL']"/>
                  </tns:CHASIS>
               </xsl:if>
               <xsl:if test="ns0:Column[@name='CIUDAD_ASEGURADO']">
                  <tns:CIUDAD>
                     <xsl:value-of select="ns0:Column[@name='CIUDAD_ASEGURADO']"/>
                  </tns:CIUDAD>
               </xsl:if>
               <xsl:if test="ns0:Column[@name='ID_CLIENTE']">
                  <tns:CLIENT_ID>
                     <xsl:value-of select="ns0:Column[@name='ID_CLIENTE']"/>
                  </tns:CLIENT_ID>
               </xsl:if>
               <xsl:if test="ns0:Column[@name='COLOR_AUTOMOVIL']">
                  <tns:COLOR>
                     <xsl:value-of select="ns0:Column[@name='COLOR_AUTOMOVIL']"/>
                  </tns:COLOR>
               </xsl:if>
               <xsl:if test="ns0:Column[@name='DEDUCIBLE']">
                  <tns:DEDUCTIBLE>
                     <xsl:value-of select="ns0:Column[@name='DEDUCIBLE']"/>
                  </tns:DEDUCTIBLE>
               </xsl:if>
               <xsl:if test="ns0:Column[@name='TIPO_DISPOSITIVO']">
                  <tns:DEVICE_TYPE>
                     <xsl:value-of select="ns0:Column[@name='TIPO_DISPOSITIVO']"/>
                  </tns:DEVICE_TYPE>
               </xsl:if>
               <xsl:if test="ns0:Column[@name='DIRECCION_ASEGURADO']">
                  <tns:DIRECCION>
                     <xsl:value-of select="ns0:Column[@name='DIRECCION_ASEGURADO']"/>
                  </tns:DIRECCION>
               </xsl:if>
               <xsl:if test="ns0:Column[@name='DIRECCION_EXTRA']">
                  <tns:DIRECCION_EXTRA>
                     <xsl:value-of select="ns0:Column[@name='DIRECCION_EXTRA']"/>
                  </tns:DIRECCION_EXTRA>
               </xsl:if>
               <xsl:if test="ns0:Column[@name='EMAIL_ASEGURADO']">
                  <tns:EMAIL>
                     <xsl:value-of select="ns0:Column[@name='EMAIL_ASEGURADO']"/>
                  </tns:EMAIL>
               </xsl:if>
               <xsl:if test="ns0:Column[@name='EMAIL_COMPANIA']">
                  <tns:EMAIL_COMPANIA>
                     <xsl:value-of select="ns0:Column[@name='EMAIL_COMPANIA']"/>
                  </tns:EMAIL_COMPANIA>
               </xsl:if>
               <xsl:if test="ns0:Column[@name='INDICADOR_ES_COMPANIA']">
                  <xsl:choose>
                     <xsl:when test="ns0:Column[@name='INDICADOR_ES_COMPANIA'] = &quot;Y&quot;">
                        <tns:ES_COMPAÑIA>true</tns:ES_COMPAÑIA>
                     </xsl:when>
                      <xsl:when test="ns0:Column[@name='INDICADOR_ES_COMPANIA'] = &quot;N&quot;">
                        <tns:ES_COMPAÑIA>false</tns:ES_COMPAÑIA>
                     </xsl:when>
                  </xsl:choose>
               </xsl:if>
               <xsl:if test="ns0:Column[@name='ID_VOUCHER_ANTERIOR']">
                  <tns:FROM_PREVIOUS_VOUCHER_ID>
                     <xsl:value-of select="ns0:Column[@name='ID_VOUCHER_ANTERIOR']"/>
                  </tns:FROM_PREVIOUS_VOUCHER_ID>
               </xsl:if>
               <xsl:if test="ns0:Column[@name='REPARACION_TALLER']">
                  <tns:GARAGE_REPAIR>
                     <xsl:value-of select="ns0:Column[@name='REPARACION_TALLER']"/>
                  </tns:GARAGE_REPAIR>
               </xsl:if>
               <xsl:if test="ns0:Column[@name='ID_VOUCHER']">
                  <tns:ID>
                     <xsl:value-of select="ns0:Column[@name='ID_VOUCHER']"/>
                  </tns:ID>
               </xsl:if>
               <xsl:if test="ns0:Column[@name='ID_ASEGURADO']">
                  <tns:IDENTIFICACION>
                     <xsl:value-of select="ns0:Column[@name='ID_ASEGURADO']"/>
                  </tns:IDENTIFICACION>
               </xsl:if>
               <xsl:if test="ns0:Column[@name='IMEI']">
                  <tns:IMEI>
                     <xsl:value-of select="ns0:Column[@name='IMEI']"/>
                  </tns:IMEI>
               </xsl:if>
               <xsl:if test="ns0:Column[@name='VALOR_KM']">
                  <tns:KM_RATE>
                     <xsl:value-of select="ns0:Column[@name='VALOR_KM']"/>
                  </tns:KM_RATE>
               </xsl:if>
               <xsl:if test="ns0:Column[@name='FECHA_ULTIMA_COMUNICACION']">
                  <tns:LAST_COMMUNICATION>
                     <xsl:value-of select="ns0:Column[@name='FECHA_ULTIMA_COMUNICACION']"/>
                  </tns:LAST_COMMUNICATION>
               </xsl:if>
               <xsl:if test="ns0:Column[@name='FECHA_ACTUALIZACION_VOUCHER']">
                  <tns:LAST_MODIFIED>
                     <xsl:value-of select="ns0:Column[@name='FECHA_ACTUALIZACION_VOUCHER']"/>
                  </tns:LAST_MODIFIED>
               </xsl:if>
               <xsl:if test="ns0:Column[@name='ULTIMO_VIAJE']">
                  <tns:LAST_TRIP>
                     <xsl:value-of select="ns0:Column[@name='ULTIMO_VIAJE']"/>
                  </tns:LAST_TRIP>
               </xsl:if>
               <xsl:if test="ns0:Column[@name='MARCA_AUTOMOVIL']">
                  <tns:MARCA>
                     <xsl:value-of select="ns0:Column[@name='MARCA_AUTOMOVIL']"/>
                  </tns:MARCA>
               </xsl:if>
               <xsl:if test="ns0:Column[@name='MENSAJE_ERROR']">
                  <tns:MENSAJE>
                     <xsl:value-of select="ns0:Column[@name='MENSAJE_ERROR']"/>
                  </tns:MENSAJE>
               </xsl:if>
               <xsl:if test="ns0:Column[@name='MODELO_AUTOMOVIL']">
                  <tns:MODELO>
                     <xsl:value-of select="ns0:Column[@name='MODELO_AUTOMOVIL']"/>
                  </tns:MODELO>
               </xsl:if>
               <xsl:if test="ns0:Column[@name='NOMBRE_ASEGURADO']">
                  <tns:NOMBRE>
                     <xsl:value-of select="ns0:Column[@name='NOMBRE_ASEGURADO']"/>
                  </tns:NOMBRE>
               </xsl:if>
               <xsl:if test="ns0:Column[@name='NUMERO_DE_POLIZA']">
                  <tns:NUMERO_DE_POLIZA>
                     <xsl:value-of select="ns0:Column[@name='NUMERO_DE_POLIZA']"/>
                  </tns:NUMERO_DE_POLIZA>
               </xsl:if>
               <xsl:if test="ns0:Column[@name='ESTADO_DISPOSITIVO_OCTO']">
                  <tns:OCTO_DEVICE_STATE>
                     <xsl:value-of select="ns0:Column[@name='ESTADO_DISPOSITIVO_OCTO']"/>
                  </tns:OCTO_DEVICE_STATE>
               </xsl:if>
               <xsl:if test="ns0:Column[@name='ESTADO_OCTO']">
                  <tns:OCTO_STATE>
                     <xsl:value-of select="ns0:Column[@name='ESTADO_OCTO']"/>
                  </tns:OCTO_STATE>
               </xsl:if>
               <xsl:if test="ns0:Column[@name='FECHA_APERTURA_VOUCHER']">
                  <tns:OPEN_DATE>
                     <xsl:value-of select="ns0:Column[@name='FECHA_APERTURA_VOUCHER']"/>
                  </tns:OPEN_DATE>
               </xsl:if>
               <xsl:if test="ns0:Column[@name='TIPO_OPERACION']">
                  <tns:OPERATION_TYPE>
                     <xsl:value-of select="ns0:Column[@name='TIPO_OPERACION']"/>
                  </tns:OPERATION_TYPE>
               </xsl:if>
               <xsl:if test="ns0:Column[@name='PAIS_ASEGURADO']">
                  <tns:PAIS>
                     <xsl:value-of select="ns0:Column[@name='PAIS_ASEGURADO']"/>
                  </tns:PAIS>
               </xsl:if>
               <xsl:if test="ns0:Column[@name='PLACA_AUTOMOVIL']">
                  <tns:PLACA>
                     <xsl:value-of select="ns0:Column[@name='PLACA_AUTOMOVIL']"/>
                  </tns:PLACA>
               </xsl:if>
               <xsl:if test="ns0:Column[@name='KM_MES_ANTERIOR']">
                  <tns:PREV_MONTH_TRAVELED_KM>
                     <xsl:value-of select="ns0:Column[@name='KM_MES_ANTERIOR']"/>
                  </tns:PREV_MONTH_TRAVELED_KM>
               </xsl:if>
               <xsl:if test="ns0:Column[@name='PROVINCIA_ASEGURADO']">
                  <tns:PROVINCIA>
                     <xsl:value-of select="ns0:Column[@name='PROVINCIA_ASEGURADO']"/>
                  </tns:PROVINCIA>
               </xsl:if>
               <xsl:if test="ns0:Column[@name='CANTIDAD_REINTENTOS']">
                  <tns:REINTENTO>
                     <xsl:value-of select="ns0:Column[@name='CANTIDAD_REINTENTOS']"/>
                  </tns:REINTENTO>
               </xsl:if>
               <xsl:if test="ns0:Column[@name='VEHICULO_REEMPLAZO']">
                  <tns:REPLACE_VEHICLE_TIME>
                     <xsl:value-of select="ns0:Column[@name='VEHICULO_REEMPLAZO']"/>
                  </tns:REPLACE_VEHICLE_TIME>
               </xsl:if>
               <xsl:if test="ns0:Column[@name='DANIO_RESPONSABILIDAD_CIVIL']">
                  <tns:RESPONSABILITY_DAMAGE>
                     <xsl:value-of select="ns0:Column[@name='DANIO_RESPONSABILIDAD_CIVIL']"/>
                  </tns:RESPONSABILITY_DAMAGE>
               </xsl:if>
               <xsl:if test="ns0:Column[@name='KM_ULTIMOS_SEIS_MESES']">
                  <tns:SEMESTER_TRAVELED_KM>
                     <xsl:value-of select="ns0:Column[@name='KM_ULTIMOS_SEIS_MESES']"/>
                  </tns:SEMESTER_TRAVELED_KM>
               </xsl:if>
               <xsl:if test="ns0:Column[@name='INDICADOR_PROCESADO']">
                  <tns:PROCESADO>
                     <xsl:value-of select="ns0:Column[@name='INDICADOR_PROCESADO']"/>
                  </tns:PROCESADO>
               </xsl:if>
               <xsl:if test="ns0:Column[@name='SENDER_ID']">
                  <tns:SENDER_ID>
                     <xsl:value-of select="ns0:Column[@name='SENDER_ID']"/>
                  </tns:SENDER_ID>
               </xsl:if>
               <xsl:if test="ns0:Column[@name='ESTADO_VOUCHER']">
                  <tns:STATE>
                     <xsl:value-of select="ns0:Column[@name='ESTADO_VOUCHER']"/>
                  </tns:STATE>
               </xsl:if>
               <xsl:if test="ns0:Column[@name='TELEFONO_ASEGURADO']">
                  <tns:TELEFONO>
                     <xsl:value-of select="ns0:Column[@name='TELEFONO_ASEGURADO']"/>
                  </tns:TELEFONO>
               </xsl:if>
               <xsl:if test="ns0:Column[@name='FECHA_DEVOLUCION']">
                  <tns:TERMINAL_RETURN_DATE>
                     <xsl:value-of select="ns0:Column[@name='FECHA_DEVOLUCION']"/>
                  </tns:TERMINAL_RETURN_DATE>
               </xsl:if>
               <xsl:if test="ns0:Column[@name='TIPO_DE_COBERTURA']">
                  <tns:TIPO_DE_COBERTURA>
                     <xsl:value-of select="ns0:Column[@name='TIPO_DE_COBERTURA']"/>
                  </tns:TIPO_DE_COBERTURA>
               </xsl:if>
               <xsl:if test="ns0:Column[@name='TIPO_DE_PROCESO']">
                  <tns:TIPO_PROCESO>
                     <xsl:value-of select="ns0:Column[@name='TIPO_DE_PROCESO']"/>
                  </tns:TIPO_PROCESO>
               </xsl:if>
               <xsl:if test="ns0:Column[@name='TIPO']">
                  <tns:TYPE>
                     <xsl:value-of select="ns0:Column[@name='TIPO']"/>
                  </tns:TYPE>
               </xsl:if>
               <xsl:if test="ns0:Column[@name='UUID']">
                  <tns:UUID>
                     <xsl:value-of select="ns0:Column[@name='UUID']"/>
                  </tns:UUID>
               </xsl:if>
               <xsl:if test="ns0:Column[@name='VIGENCIA_FINAL_POLIZA']">
                  <tns:VIGENCIA_FINAL>
                     <xsl:value-of select="ns0:Column[@name='VIGENCIA_FINAL_POLIZA']"/>
                  </tns:VIGENCIA_FINAL>
               </xsl:if>
               <xsl:if test="ns0:Column[@name='VIGENCIA_INICIAL_POLIZA']">
                  <tns:VIGENCIA_INICIAL>
                     <xsl:value-of select="ns0:Column[@name='VIGENCIA_INICIAL_POLIZA']"/>
                  </tns:VIGENCIA_INICIAL>
               </xsl:if>
               <xsl:if test="ns0:Column[@name='ZONA_POSTAL_ASEGURADO']">
                  <tns:ZONA_POSTAL>
                     <xsl:value-of select="ns0:Column[@name='ZONA_POSTAL_ASEGURADO']"/>
                  </tns:ZONA_POSTAL>
               </xsl:if>
            </tns:VOUCHER>
         </xsl:for-each>
      </tns:OBJETO_VOUCHER>
   </xsl:template>
</xsl:stylesheet>
