<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:tns="http://TargetNamespace.com/legalizarRecibo" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd" xmlns:ns0="http://sura.com.pa/LegalizarRecibosCS">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source/>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../XSD/legalizarRecibos.xsd"/>
            <oracle-xsl-mapper:rootElement name="LegalizarRecibo" namespace="http://sura.com.pa/LegalizarRecibosCS"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [TUE MAR 30 11:03:20 COT 2021].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="numPoliza"/>
   <xsl:param name="numReferencia"/>
   <xsl:param name="monto"/>
   <xsl:param name="cedula"/>
   <xsl:param name="tipoCedula"/>
   <xsl:param name="sucursal"/>
   <xsl:param name="fechaOperacion"/>
   <xsl:param name="usuario"/>
   <xsl:param name="formaPago"/>
   <xsl:template match="/">
      <tns:LegalizarRecibo>
         <tns:NUMERO_POLIZA>
            <xsl:value-of select="$numPoliza"/>
         </tns:NUMERO_POLIZA>
         <tns:NUMERO_REFERENCIA>
            <xsl:value-of select="$numReferencia"/>
         </tns:NUMERO_REFERENCIA>
         <tns:MONTO>
            <xsl:value-of select="$monto"/>
         </tns:MONTO>
         <tns:CEDULA>
            <xsl:value-of select="$cedula"/>
         </tns:CEDULA>
         <tns:TIPO_CEDULA>
            <xsl:value-of select="$tipoCedula"/>
         </tns:TIPO_CEDULA>
         <tns:SUCURSAL>
            <xsl:value-of select="$sucursal"/>
         </tns:SUCURSAL>
         <tns:FECHA_OPERACION>
            <xsl:value-of select="$fechaOperacion"/>
         </tns:FECHA_OPERACION>
         <tns:USUARIO>
            <xsl:value-of select="$usuario"/>
         </tns:USUARIO>
         <tns:FORMA_PAGO>
            <xsl:value-of select="$formaPago"/>
         </tns:FORMA_PAGO>
      </tns:LegalizarRecibo>
   </xsl:template>
</xsl:stylesheet>