<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ServiciosIntegracionSURA/Dat_ObtenerMarcasModelos/sp_gt_marcas_modelos" name="sp_gt_marcas_modelos-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="sp_gt_marcas_modelos.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ServiciosIntegracionSURA/Dat_ObtenerMarcasModelos/sp_gt_marcas_modelos"/>
    <wsdl:binding name="sp_gt_marcas_modelos_ptt-binding" type="sp:sp_gt_marcas_modelos_ptt" xmlns:sp="http://xmlns.oracle.com/pcbpel/adapter/db/ServiciosIntegracionSURA/Dat_ObtenerMarcasModelos/sp_gt_marcas_modelos">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="sp_gt_marcas_modelos">
            <soap:operation soapAction="sp_gt_marcas_modelos"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>