<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ServiciosIntegracionSURA/Dat_ConsultarRegistroRecibo/ConsultarRegistroRecibo" name="ConsultarRegistroRecibo-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="ConsultarRegistroRecibo.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ServiciosIntegracionSURA/Dat_ConsultarRegistroRecibo/ConsultarRegistroRecibo"/>
    <wsdl:binding name="ConsultarRegistroRecibo_ptt-binding" type="con:ConsultarRegistroRecibo_ptt" xmlns:con="http://xmlns.oracle.com/pcbpel/adapter/db/ServiciosIntegracionSURA/Dat_ConsultarRegistroRecibo/ConsultarRegistroRecibo">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="ConsultarRegistroRecibo">
            <soap:operation soapAction="ConsultarRegistroRecibo"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>