<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:tns="http://xmlns.sura.com/MensajeIntegracion/DominioPago/PagoMI/V1" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:ns0="http://sura.com.pa/afiliarInfoBnk/" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:dcomcom="http://xmlns.sura.com/ObjetoEmpresarial/DominioComun/Comun/V1"
                xmlns:dpagpag="http://xmlns.sura.com/ObjetoIntegracion/DominioPago/Pago/V1">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../../../ComponentesComunes/WSDL_Externos/afiliarInfoBnk.wsdl"/>
            <oracle-xsl-mapper:rootElement name="desvincularInfoBnk" namespace="http://sura.com.pa/afiliarInfoBnk/"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../../../ComponentesComunes/WSDL/xsd/DominioPago/Pago/V1/PagoMIV1.xsd"/>
            <oracle-xsl-mapper:rootElement name="DesvincularClienteInfoBancariaMsjSol" namespace="http://xmlns.sura.com/MensajeIntegracion/DominioPago/PagoMI/V1"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [THU JUN 11 01:19:07 COT 2020].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="codigoOperacion"/>
   <xsl:param name="idTransaccion"/>
   <xsl:param name="fechaProcesamiento"/>
   <xsl:template match="/">
      <tns:DesvincularClienteInfoBancariaMsjSol>
         <tns:CabeceraSol>
            <dcomcom:CodigoOperacion>
               <xsl:value-of select="$codigoOperacion"/>
            </dcomcom:CodigoOperacion>
            <dcomcom:FechaProcesamiento>
               <xsl:value-of select="$fechaProcesamiento"/>
            </dcomcom:FechaProcesamiento>
            <dcomcom:FechaTransaccion>
               <xsl:value-of select="$fechaProcesamiento"/>
            </dcomcom:FechaTransaccion>
            <dcomcom:IdTransaccionOsb>
               <xsl:value-of select="$idTransaccion"/>
            </dcomcom:IdTransaccionOsb>
            <dcomcom:SistemaDestino>PP</dcomcom:SistemaDestino>
            <dcomcom:SistemaOrigen>Pasarela</dcomcom:SistemaOrigen>
         </tns:CabeceraSol>
         <tns:Beneficiario>
            <dcomcom:NumeroIdentificacion>
               <xsl:value-of select="/ns0:desvincularInfoBnk/idCliente"/>
            </dcomcom:NumeroIdentificacion>
         </tns:Beneficiario>
         <tns:Pago>
            <dpagpag:TipoPago>
               <xsl:value-of select="/ns0:desvincularInfoBnk/medioPago"/>
            </dpagpag:TipoPago>
            <dpagpag:InfoPolizaPago>
               <dpagpag:NumeroPoliza>
                  <xsl:value-of select="/ns0:desvincularInfoBnk/numPoliza"/>
               </dpagpag:NumeroPoliza>
            </dpagpag:InfoPolizaPago>
         </tns:Pago>
      </tns:DesvincularClienteInfoBancariaMsjSol>
   </xsl:template>
</xsl:stylesheet>
